// Mor'ia 9.11-9.16 — editable seed content for the Living Realm.
const node=(id,name,mapId,specialization,x,y)=>({id,name,mapId,specialization,x,y,radius:12,enabled:true,maxHp:5000,stageThresholds:[0,150,450,1100,2400,4800,9000],taxRate:5});
export const LIVING_REALM_CONTENT=Object.freeze({
  nodes:Object.freeze([
    node('node_eldoria','Eldoria Crownlands','eldoria','commercial',40,40),
    node('node_emberhold','Emberhold Forge March','emberhold','industrial',40,40),
    node('node_frostpeak','Frostpeak Bastion','frostpeak','military',40,40),
    node('node_stormwatch','Stormwatch Conduit','stormwatch','arcane',40,40),
    node('node_ironwood','Ironwood Wild March','ironwood','wild',40,40),
    node('node_crystaldeep','Crystal Deep Conclave','crystaldeep','arcane',40,40),
    node('node_nightfall','Nightfall Veil','nightfall','religious',40,40),
    node('node_sunreach','Sunreach Free Port','sunreach','commercial',40,40),
    node('node_voidlands','Voidlands Warfront','voidlands','military',40,40),
    node('node_astra','Astra Sanctum','astra_sanctum','arcane',40,40),
  ]),
  factions:Object.freeze([
    {id:'crown_eldoria',name:'Crown of Eldoria',icon:'♛',color:'#e8c76a',ideology:'Order, cities and protected trade.',hqMapId:'eldoria',bonuses:{commerce:10,defense:5},enemies:['red_pact']},
    {id:'red_pact',name:'Red Pact',icon:'⚔',color:'#dc5a5a',ideology:'Strength, conquest and martial honor.',hqMapId:'voidlands',bonuses:{siege:10,attack:5},enemies:['crown_eldoria']},
    {id:'arcane_conclave',name:'Arcane Conclave',icon:'✦',color:'#9b7cff',ideology:'Knowledge, relics and dangerous discovery.',hqMapId:'crystaldeep',bonuses:{arcane:10,craftQuality:3},enemies:['order_veil']},
    {id:'order_veil',name:'Order of the Veil',icon:'☾',color:'#8a6ba8',ideology:'Death, shadows and forbidden truths.',hqMapId:'nightfall',bonuses:{death:10,shadow:10},enemies:['arcane_conclave']},
    {id:'children_wild',name:'Children of the Wild',icon:'❧',color:'#63b66c',ideology:'Beasts, wilderness and natural balance.',hqMapId:'ironwood',bonuses:{taming:12,nature:8},enemies:[]},
    {id:'free_league',name:'Free League',icon:'⚓',color:'#56b8cf',ideology:'Trade, exploration and political independence.',hqMapId:'sunreach',bonuses:{commerce:12,craftQuality:2},enemies:[]},
  ]),
  materials:Object.freeze([
    {id:'iron_ore',name:'Iron Ore',icon:'⛏',category:'ore',tier:1,baseQuality:40},
    {id:'coal',name:'Coal',icon:'◼',category:'fuel',tier:1,baseQuality:45},
    {id:'steel_ingot',name:'Steel Ingot',icon:'▰',category:'metal',tier:2,baseQuality:50},
    {id:'oak_log',name:'Oak Log',icon:'🪵',category:'wood',tier:1,baseQuality:45},
    {id:'treated_lumber',name:'Treated Lumber',icon:'▤',category:'wood',tier:2,baseQuality:55},
    {id:'wolf_hide',name:'Wolf Hide',icon:'◩',category:'hide',tier:1,baseQuality:45},
    {id:'cured_leather',name:'Cured Leather',icon:'▱',category:'leather',tier:2,baseQuality:55},
    {id:'moon_herb',name:'Moon Herb',icon:'☘',category:'herb',tier:2,baseQuality:60},
    {id:'mana_crystal',name:'Mana Crystal',icon:'◆',category:'arcane',tier:3,baseQuality:65},
    {id:'dragon_scale',name:'Dragon Scale',icon:'◇',category:'monster',tier:4,baseQuality:75},
    {id:'void_essence',name:'Void Essence',icon:'✧',category:'essence',tier:4,baseQuality:75},
    {id:'sun_salt',name:'Sun Salt',icon:'◈',category:'reagent',tier:2,baseQuality:55},
  ]),
  craftingRecipes:Object.freeze([
    {id:'process_steel',name:'Smelt Steel',profession:'smelting',stationType:'forge',difficulty:15,levelRequired:1,inputs:[{name:'Iron Ore',quantity:3},{name:'Coal',quantity:1}],output:{name:'Steel Ingot',icon:'▰',type:'material',quantity:1}},
    {id:'process_lumber',name:'Treat Lumber',profession:'carpentry',stationType:'sawmill',difficulty:12,levelRequired:1,inputs:[{name:'Oak Log',quantity:3}],output:{name:'Treated Lumber',icon:'▤',type:'material',quantity:1}},
    {id:'process_leather',name:'Cure Leather',profession:'leatherworking',stationType:'tannery',difficulty:12,levelRequired:1,inputs:[{name:'Wolf Hide',quantity:3},{name:'Sun Salt',quantity:1}],output:{name:'Cured Leather',icon:'▱',type:'material',quantity:1}},
    {id:'steel_longblade',name:'Steel Longblade',profession:'weaponsmithing',stationType:'forge',difficulty:35,levelRequired:8,inputs:[{name:'Steel Ingot',quantity:4},{name:'Treated Lumber',quantity:1}],output:{name:'Crafted Steel Longblade',icon:'⚔',type:'equipment',slot:'weapon',attack:18,rarity:'uncommon',level:8,value:450}},
    {id:'dragon_plate',name:'Dragon Scale Plate',profession:'armorsmithing',stationType:'forge',difficulty:70,levelRequired:25,inputs:[{name:'Steel Ingot',quantity:6},{name:'Dragon Scale',quantity:4},{name:'Cured Leather',quantity:2}],output:{name:'Dragon Scale Plate',icon:'🛡',type:'equipment',slot:'armor',armor:34,defense:8,rarity:'epic',level:25,value:5000,resistances:{fire:15}}},
    {id:'moon_elixir',name:'Moon Elixir',profession:'alchemy',stationType:'alchemy',difficulty:30,levelRequired:5,inputs:[{name:'Moon Herb',quantity:3},{name:'Mana Crystal',quantity:1}],output:{name:'Moon Elixir',icon:'🧪',type:'potion',quantity:2,value:180}},
    {id:'arcane_focus',name:'Arcane Focus',profession:'enchanting',stationType:'enchanter',difficulty:55,levelRequired:15,inputs:[{name:'Mana Crystal',quantity:3},{name:'Void Essence',quantity:1}],output:{name:'Arcane Focus',icon:'🔮',type:'equipment',slot:'relic',magic:12,rarity:'rare',level:15,value:1800,damageBonuses:{arcane:12}}},
    {id:'siege_ram',name:'Reinforced Battering Ram Kit',profession:'siege_engineering',stationType:'siegeworks',difficulty:60,levelRequired:20,inputs:[{name:'Treated Lumber',quantity:8},{name:'Steel Ingot',quantity:6},{name:'Cured Leather',quantity:2}],output:{name:'Battering Ram Kit',icon:'🛠',type:'siege',quantity:1,value:2500}},
  ]),
  tamingSpecies:Object.freeze([
    {id:'wild_wolf',name:'Wild Wolf',icon:'🐺',monsterId:'wolf',rarity:'common',levelRequired:3,mapId:'ironwood',temperament:35,favoriteFood:'Raw Meat',breedable:true,roles:['combat','scout'],baseTraits:{strength:48,speed:62,endurance:50,intelligence:35,loyalty:45,wildness:60}},
    {id:'brown_bear',name:'Brown Bear',icon:'🐻',monsterId:'bear',rarity:'uncommon',levelRequired:8,mapId:'ironwood',temperament:55,favoriteFood:'Honey',breedable:true,roles:['combat','pack'],baseTraits:{strength:76,speed:38,endurance:78,intelligence:40,loyalty:50,wildness:65}},
    {id:'frost_wolf',name:'Frost Wolf',icon:'❄',monsterId:'frost_wolf',rarity:'rare',levelRequired:18,mapId:'frostpeak',temperament:68,favoriteFood:'Icefish',breedable:true,roles:['mount','combat','scout'],baseTraits:{strength:62,speed:78,endurance:66,intelligence:52,loyalty:45,wildness:78}},
    {id:'storm_raptor',name:'Storm Raptor',icon:'⚡',monsterId:'storm_raptor',rarity:'epic',levelRequired:28,mapId:'stormwatch',temperament:78,favoriteFood:'Charged Meat',breedable:true,roles:['mount','combat'],baseTraits:{strength:72,speed:90,endurance:60,intelligence:62,loyalty:40,wildness:88}},
    {id:'shadow_panther',name:'Shadow Panther',icon:'🌑',monsterId:'shadow_panther',rarity:'legendary',levelRequired:38,mapId:'nightfall',temperament:88,favoriteFood:'Void Venison',breedable:false,roles:['combat','scout'],baseTraits:{strength:82,speed:94,endurance:70,intelligence:78,loyalty:35,wildness:94}},
  ]),
});
