// Mor'ia 9.11-9.16 — authoritative persistent world politics, chronicle, crafting and taming.
const clamp=(v,a,b,f=a)=>{const n=Number(v);return Number.isFinite(n)?Math.max(a,Math.min(b,n)):f};
const int=(v,a,b,f=a)=>Math.floor(clamp(v,a,b,f));
const text=(v,n=120)=>typeof v==='string'?v.trim().slice(0,n):'';
const slug=v=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'');
const clone=v=>v===undefined?undefined:structuredClone(v);
const isRecord=v=>Boolean(v&&typeof v==='object'&&!Array.isArray(v));
const playerKey=name=>String(name||'').trim().toLocaleLowerCase('en-US').slice(0,80);
const LIVING_REALM_REGIONAL_REAGENTS=Object.freeze({sunreach_coast:{name:'Tide Pearl',icon:'◉',value:48},ironwood:{name:'Ironbark Resin',icon:'◆',value:52},crystal_deep:{name:'Mana Crystal',icon:'◇',value:88},stormwatch_isle:{name:'Storm Core',icon:'⚡',value:96},nightfall_citadel:{name:'Night Essence',icon:'☾',value:125}});

export const NODE_STAGES=Object.freeze(['ruins','camp','settlement','village','city','fortress','capital']);
export const NODE_SPECIALIZATIONS=Object.freeze(['military','commercial','arcane','religious','industrial','wild','neutral']);
export const NODE_WAR_STATES=Object.freeze(['peace','tension','declared','preparation','siege','occupied','recovery']);
export const CRAFT_GRADES=Object.freeze(['crude','common','fine','masterwork','epic','relic']);
export const TAME_RARITIES=Object.freeze(['common','uncommon','rare','epic','legendary','mythical']);
export const LIVING_REALM_LIMITS=Object.freeze({chronicle:250,animals:40,craftLog:100,nodeWarPreparationMs:5*60_000,nodeSiegeMs:30*60_000,nodeRecoveryMs:15*60_000,nodeAttackCooldownMs:1200,defectionCooldownMs:24*60*60_000});

function ensureHost(host){if(!host||typeof host.ensurePlayer!=='function'||!isRecord(host.global))throw new TypeError('LivingRealmDomain requires an OfficialSystems-compatible host.');}
function markDirty(host){host._livingRealmDirty=true;}
function flushDirty(host,now=Date.now(),force=false){if(!host._livingRealmDirty)return false;const last=Math.max(0,Number(host._livingRealmLastPersist)||0);if(!force&&now-last<5000)return false;if(typeof host.save==='function'&&!host.save())return false;host._livingRealmDirty=false;host._livingRealmLastPersist=now;return true;}
function catalogs(host){return isRecord(host.livingRealmContent)?host.livingRealmContent:{nodes:[],factions:[],materials:[],craftingRecipes:[],tamingSpecies:[]};}
function normalizeNodeDefinition(raw){
  const thresholds=Array.isArray(raw?.stageThresholds)&&raw.stageThresholds.length>=7?raw.stageThresholds.slice(0,7).map((v,i)=>int(v,0,10_000_000,i?i*500:0)):[0,150,450,1100,2400,4800,9000];
  for(let i=1;i<thresholds.length;i++)thresholds[i]=Math.max(thresholds[i],thresholds[i-1]+1);
  return {id:text(raw?.id,100),name:text(raw?.name,100)||'Unnamed Node',mapId:text(raw?.mapId,100),specialization:NODE_SPECIALIZATIONS.includes(raw?.specialization)?raw.specialization:'neutral',x:int(raw?.x,1,78,40),y:int(raw?.y,1,78,40),radius:int(raw?.radius,2,30,12),enabled:raw?.enabled!==false,maxHp:int(raw?.maxHp,500,1_000_000,5000),stageThresholds:thresholds,taxRate:clamp(raw?.taxRate,0,25,5)};
}
function stageFromXp(def,xp){let stage=0;for(let i=0;i<def.stageThresholds.length;i++)if(xp>=def.stageThresholds[i])stage=i;return Math.min(NODE_STAGES.length-1,stage);}
function normalizeNodeState(raw,def){const xp=int(raw?.xp,0,100_000_000,0);const stage=stageFromXp(def,xp);const maxHp=Math.round(def.maxHp*(1+stage*.35));return {id:def.id,xp,stage,stageName:NODE_STAGES[stage],controllerFactionId:text(raw?.controllerFactionId,100)||null,hp:int(raw?.hp,0,maxHp,maxHp),maxHp,treasury:int(raw?.treasury,0,1_000_000_000,0),supply:int(raw?.supply,0,100,50),morale:int(raw?.morale,0,100,50),status:NODE_WAR_STATES.includes(raw?.status)?raw.status:'peace',attackerFactionId:text(raw?.attackerFactionId,100)||null,declaredAt:Math.max(0,Number(raw?.declaredAt)||0),siegeStartsAt:Math.max(0,Number(raw?.siegeStartsAt)||0),siegeEndsAt:Math.max(0,Number(raw?.siegeEndsAt)||0),recoveryUntil:Math.max(0,Number(raw?.recoveryUntil)||0),lastChangedAt:Math.max(0,Number(raw?.lastChangedAt)||0)};}
function ensureRealm(host){
  ensureHost(host); if(!isRecord(host.global.livingRealm))host.global.livingRealm={nodes:{},chronicle:[],sequence:0};
  const realm=host.global.livingRealm;if(!isRecord(realm.nodes))realm.nodes={};if(!Array.isArray(realm.chronicle))realm.chronicle=[];realm.sequence=int(realm.sequence,0,999_999_999,0);
  for(const raw of catalogs(host).nodes||[]){const def=normalizeNodeDefinition(raw);if(!def.id||!def.enabled)continue;realm.nodes[def.id]=normalizeNodeState(realm.nodes[def.id],def);}
  return realm;
}
function ensurePlayer(host,player){ensureHost(host);const state=host.ensurePlayer(player);if(!isRecord(state.livingRealm))state.livingRealm={};const lr=state.livingRealm;
  if(!isRecord(lr.faction))lr.faction={id:null,reputation:0,rank:0,joinedAt:0,defectionUntil:0,history:[]};
  if(!isRecord(lr.crafting))lr.crafting={skills:{},crafted:0,masterworks:0,log:[]};
  if(!isRecord(lr.taming))lr.taming={skill:1,xp:0,animals:[],activeId:null,breedingCount:0};
  lr.lastNodeAttackAt=Math.max(0,Number(lr.lastNodeAttackAt)||0); return lr;
}
function factionById(host,id){return (catalogs(host).factions||[]).find(f=>f?.id===id)||null;}
function nodeDef(host,id){const raw=(catalogs(host).nodes||[]).find(n=>n?.id===id);return raw?normalizeNodeDefinition(raw):null;}
function nodeAtMap(host,mapId){return (catalogs(host).nodes||[]).map(normalizeNodeDefinition).find(n=>n.enabled&&n.mapId===mapId)||null;}
function addInventory(player,item){const copy=clone(item)||{};copy.quantity=int(copy.quantity,1,9999,1);if(copy.type!=='equipment'&&copy.type!=='gem'){const same=player.inventory.find(i=>i.name===copy.name&&i.type===copy.type&&!i.equipment);if(same){same.quantity=int(same.quantity,0,999999,0)+copy.quantity;return same;}}copy.id=copy.id||`lr_${Date.now()}_${Math.random().toString(36).slice(2)}`;player.inventory.push(copy);return copy;}
function inventoryCount(player,name){return player.inventory.filter(i=>i?.name===name).reduce((sum,i)=>sum+int(i.quantity,0,999999,0),0);}
function consumeInventory(player,name,qty){let remaining=qty;for(const item of player.inventory){if(item?.name!==name||remaining<=0)continue;const take=Math.min(int(item.quantity,0,999999,0),remaining);item.quantity-=take;remaining-=take;}player.inventory=player.inventory.filter(i=>Number(i.quantity)>0||i.type==='equipment');return remaining===0;}
function rankFromRep(rep){return rep>=2500?5:rep>=1200?4:rep>=500?3:rep>=200?2:rep>=50?1:0;}
function qualityGrade(score){return score>=95?'relic':score>=85?'epic':score>=70?'masterwork':score>=50?'fine':score>=30?'common':'crude';}
function inheritedTrait(a,b,roll){const avg=(Number(a)||0+Number(b)||0)/2;return int(avg+(roll-.5)*12,1,100,50);}

export class LivingRealmDomain{
  syncContent(host,content={}){host.livingRealmContent={nodes:clone(content.nodes||[]),factions:clone(content.factions||[]),materials:clone(content.materials||[]),craftingRecipes:clone(content.craftingRecipes||[]),tamingSpecies:clone(content.tamingSpecies||[])};ensureRealm(host);return host.livingRealmContent;}
  chronicle(host,type,headline,body='',meta={},now=Date.now()){
    const realm=ensureRealm(host);realm.sequence++;const item={id:`news_${now}_${realm.sequence}`,type:slug(type)||'world',headline:text(headline,160)||'World update',body:text(body,700),at:Math.max(0,Number(now)||Date.now()),mapId:text(meta.mapId,100)||null,nodeId:text(meta.nodeId,100)||null,factionId:text(meta.factionId,100)||null,actor:text(meta.actor,80)||null,severity:['info','notable','major','historic'].includes(meta.severity)?meta.severity:'info'};
    realm.chronicle.push(item);realm.chronicle=realm.chronicle.slice(-LIVING_REALM_LIMITS.chronicle);markDirty(host);flushDirty(host,now,true);return clone(item);
  }
  joinFaction(host,player,factionId,now=Date.now()){
    const lr=ensurePlayer(host,player),f=factionById(host,factionId);if(!f||player.level<3||lr.faction.id||now<lr.faction.defectionUntil)return {ok:false,reason:'faction_unavailable'};
    lr.faction={...lr.faction,id:f.id,reputation:0,rank:0,joinedAt:now};this.chronicle(host,'faction',`${player.name} pledged to ${f.name}.`,'A new allegiance was sworn in the realm.',{actor:player.name,factionId:f.id,severity:'notable'},now);return {ok:true,factionId:f.id};
  }
  defectFaction(host,player,nextFactionId,now=Date.now()){
    const lr=ensurePlayer(host,player),next=factionById(host,nextFactionId);if(!next||!lr.faction.id||lr.faction.id===next.id||now<lr.faction.defectionUntil)return {ok:false,reason:'defection_unavailable'};
    const old=lr.faction.id;lr.faction.history=Array.isArray(lr.faction.history)?lr.faction.history.slice(-9):[];lr.faction.history.push({id:old,leftAt:now});lr.faction.id=next.id;lr.faction.reputation=-100;lr.faction.rank=0;lr.faction.joinedAt=now;lr.faction.defectionUntil=now+LIVING_REALM_LIMITS.defectionCooldownMs;
    this.chronicle(host,'faction',`${player.name} defected to ${next.name}.`,'The political balance shifted after a public defection.',{actor:player.name,factionId:next.id,severity:'major'},now);return {ok:true,from:old,to:next.id,defectionUntil:lr.faction.defectionUntil};
  }
  awardFactionReputation(host,player,amount){const lr=ensurePlayer(host,player);if(!lr.faction.id)return 0;lr.faction.reputation=int(lr.faction.reputation+amount,-5000,100000,0);lr.faction.rank=rankFromRep(lr.faction.reputation);return lr.faction.reputation;}
  contributeNode(host,player,nodeId,points=10,kind='activity',now=Date.now()){
    const def=nodeDef(host,nodeId);if(!def||player.mapId!==def.mapId)return {ok:false,reason:'wrong_node'};const realm=ensureRealm(host),node=realm.nodes[nodeId];const before=node.stage;node.xp=int(node.xp+points,0,100_000_000,0);Object.assign(node,normalizeNodeState(node,def));node.lastChangedAt=now;
    if(lrFaction(player,host)&&lrFaction(player,host)===node.controllerFactionId)this.awardFactionReputation(host,player,Math.max(1,Math.floor(points/5)));
    if(node.stage>before)this.chronicle(host,'node',`${def.name} advanced to ${node.stageName}.`,`Player activity transformed the ${def.specialization} node.`,{mapId:def.mapId,nodeId:def.id,severity:'major'},now);
    markDirty(host);return {ok:true,node:clone(node),kind};
  }
  donateNodeGold(host,player,nodeId,amount,now=Date.now()){
    const gold=int(amount,10,100000,0);if(gold<10||player.gold<gold)return {ok:false,reason:'gold'};const result=this.contributeNode(host,player,nodeId,Math.max(1,Math.floor(gold/10)),'donation',now);if(!result.ok)return result;player.gold-=gold;ensureRealm(host).nodes[nodeId].treasury=int(ensureRealm(host).nodes[nodeId].treasury+gold,0,1_000_000_000,0);return {...result,gold};
  }
  declareNodeWar(host,player,nodeId,now=Date.now()){
    const lr=ensurePlayer(host,player),def=nodeDef(host,nodeId),realm=ensureRealm(host),node=realm.nodes[nodeId];if(!def||!node||!lr.faction.id||player.level<10||player.mapId!==def.mapId||node.controllerFactionId===lr.faction.id||!['peace','recovery'].includes(node.status)||player.gold<5000)return {ok:false,reason:'war_requirements'};
    player.gold-=5000;node.status='declared';node.attackerFactionId=lr.faction.id;node.declaredAt=now;node.siegeStartsAt=now+LIVING_REALM_LIMITS.nodeWarPreparationMs;node.siegeEndsAt=node.siegeStartsAt+LIVING_REALM_LIMITS.nodeSiegeMs;node.lastChangedAt=now;const faction=factionById(host,lr.faction.id);
    this.chronicle(host,'war',`${faction?.name||lr.faction.id} declared war on ${def.name}.`,'Defenders have a preparation window before the siege begins.',{mapId:def.mapId,nodeId:def.id,factionId:lr.faction.id,actor:player.name,severity:'historic'},now);return {ok:true,node:clone(node)};
  }
  tick(host,now=Date.now()){
    const realm=ensureRealm(host);for(const [id,node] of Object.entries(realm.nodes)){const def=nodeDef(host,id);if(!def)continue;if(node.status==='declared'&&now>=node.siegeStartsAt)node.status='siege';if(node.status==='siege'&&now>=node.siegeEndsAt){node.status='recovery';node.recoveryUntil=now+LIVING_REALM_LIMITS.nodeRecoveryMs;node.attackerFactionId=null;node.hp=node.maxHp;}if(node.status==='occupied'&&now>=node.recoveryUntil)node.status='recovery';if(node.status==='recovery'&&now>=node.recoveryUntil){node.status='peace';node.hp=node.maxHp;}Object.assign(node,normalizeNodeState(node,def));}flushDirty(host,now,false);return this.publicRealm(host);}
  attackNode(host,player,nodeId,now=Date.now()){
    const lr=ensurePlayer(host,player),realm=ensureRealm(host),node=realm.nodes[nodeId],def=nodeDef(host,nodeId);const px=Number(player.x),py=Number(player.y);const atNode=def&&Number.isFinite(px)&&Number.isFinite(py)&&Math.hypot(px-def.x,py-def.y)<=def.radius;if(!def||!node||!atNode||node.status!=='siege'||lr.faction.id!==node.attackerFactionId||player.mapId!==def.mapId||now-lr.lastNodeAttackAt<LIVING_REALM_LIMITS.nodeAttackCooldownMs)return {ok:false,reason:'attack_unavailable'};
    lr.lastNodeAttackAt=now;const siegeKit=Array.isArray(player.inventory)&&player.inventory.some(i=>i?.name==='Battering Ram Kit'&&Number(i.quantity)>0);const faction=factionById(host,lr.faction.id);const siegePct=Number(faction?.bonuses?.siege)||0;const damage=int((30+player.level*3+(player.attack||0)*1.2)*(siegeKit?1.4:1)*(1+siegePct/100),25,7000,50);node.hp=Math.max(0,node.hp-damage);markDirty(host);if(node.hp===0){node.controllerFactionId=node.attackerFactionId;node.status='occupied';node.recoveryUntil=now+LIVING_REALM_LIMITS.nodeRecoveryMs;node.attackerFactionId=null;node.morale=30;node.supply=35;node.hp=Math.floor(node.maxHp*.35);const f=factionById(host,node.controllerFactionId);this.chronicle(host,'conquest',`${def.name} was claimed by ${f?.name||node.controllerFactionId}.`,'The node changed political control after its defenses collapsed.',{mapId:def.mapId,nodeId:def.id,factionId:node.controllerFactionId,actor:player.name,severity:'historic'},now);}
    return {ok:true,damage,node:clone(node)};
  }
  claimNeutralNode(host,player,nodeId,now=Date.now()){
    const lr=ensurePlayer(host,player),realm=ensureRealm(host),node=realm.nodes[nodeId],def=nodeDef(host,nodeId);const px=Number(player.x),py=Number(player.y);const atNode=def&&Number.isFinite(px)&&Number.isFinite(py)&&Math.hypot(px-def.x,py-def.y)<=def.radius;if(!def||!node||!atNode||!lr.faction.id||node.controllerFactionId||player.mapId!==def.mapId||node.stage<1)return {ok:false,reason:'claim_unavailable'};node.controllerFactionId=lr.faction.id;node.status='recovery';node.recoveryUntil=now+LIVING_REALM_LIMITS.nodeRecoveryMs;const f=factionById(host,lr.faction.id);this.chronicle(host,'claim',`${f?.name||lr.faction.id} claimed ${def.name}.`,'A previously neutral node entered faction control.',{mapId:def.mapId,nodeId:def.id,factionId:lr.faction.id,actor:player.name,severity:'major'},now);return {ok:true,node:clone(node)};
  }
  advancedCraft(host,player,recipeId,now=Date.now(),roll=Math.random){
    const recipe=(catalogs(host).craftingRecipes||[]).find(r=>r?.id===recipeId);if(!recipe||player.level<int(recipe.levelRequired,1,100000,1))return {ok:false,reason:'recipe'};for(const input of recipe.inputs||[])if(inventoryCount(player,input.name)<int(input.quantity,1,9999,1))return {ok:false,reason:`missing_${slug(input.name)}`};
    for(const input of recipe.inputs||[])consumeInventory(player,input.name,int(input.quantity,1,9999,1));const lr=ensurePlayer(host,player),skillId=slug(recipe.profession)||'crafting';if(!isRecord(lr.crafting.skills[skillId]))lr.crafting.skills[skillId]={level:1,xp:0};const skill=lr.crafting.skills[skillId];const def=nodeAtMap(host,player.mapId),node=def?ensureRealm(host).nodes[def.id]:null;const faction=factionById(host,lr.faction.id);const factionCraft=Number(faction?.bonuses?.craftQuality)||0;const factionBonus=(node&&node.controllerFactionId===lr.faction.id&&def.specialization==='industrial'?6:0)+factionCraft;const stationQuality=def?Math.min(20,node.stage*3):0;const difficulty=int(recipe.difficulty,1,100,25);const materialQuality=(recipe.inputs||[]).length?60:50;const score=clamp(25+skill.level*1.8+stationQuality+factionBonus+materialQuality*.25-difficulty*.55+(roll()-.5)*16,1,100,40);const grade=qualityGrade(score);const multiplier=Number((.75+score/100*.55).toFixed(3));const out=clone(recipe.output||{});out.crafted={recipeId:recipe.id,profession:skillId,quality:Math.round(score),grade,multiplier,crafter:text(player.name,80),nodeId:def?.id||null};if(out.type==='equipment'){out.equipment={...out,attack:Math.round((out.attack||0)*multiplier),defense:Math.round((out.defense||0)*multiplier),armor:Math.round((out.armor||0)*multiplier),magic:Math.round((out.magic||0)*multiplier),crafted:out.crafted};}
    const item=addInventory(player,out);skill.xp+=10+difficulty;if(skill.xp>=skill.level*60){skill.xp-=skill.level*60;skill.level=Math.min(100,skill.level+1);}lr.crafting.crafted++;if(['masterwork','epic','relic'].includes(grade))lr.crafting.masterworks++;lr.crafting.log.push({recipeId:recipe.id,grade,quality:Math.round(score),at:now});lr.crafting.log=lr.crafting.log.slice(-LIVING_REALM_LIMITS.craftLog);if(def)this.contributeNode(host,player,def.id,Math.max(3,Math.floor(difficulty/4)),'craft',now);if(['epic','relic'].includes(grade))this.chronicle(host,'craft',`${player.name} forged a ${grade} ${out.name}.`,`Quality ${Math.round(score)}/100 using ${recipe.profession}.`,{mapId:player.mapId,nodeId:def?.id,actor:player.name,severity:grade==='relic'?'historic':'notable'},now);return {ok:true,item:clone(item),grade,quality:Math.round(score),skill:clone(skill)};
  }
  tame(host,player,speciesId,nearbyMonsters=[],now=Date.now(),roll=Math.random){
    const species=(catalogs(host).tamingSpecies||[]).find(s=>s?.id===speciesId),lr=ensurePlayer(host,player);const px=Number(player.x),py=Number(player.y);const target=Array.isArray(nearbyMonsters)?nearbyMonsters.find(m=>m&&!m.dead&&((m.contentSourceId&&m.contentSourceId===species?.monsterId)||slug(m.name)===slug(species?.name))&&Number.isFinite(px)&&Number.isFinite(py)&&Math.hypot(Number(m.x)-px,Number(m.y)-py)<=2.25):null;if(!species||!target||player.level<int(species.levelRequired,1,100000,1)||player.mapId!==species.mapId||lr.taming.animals.length>=LIVING_REALM_LIMITS.animals)return {ok:false,reason:'taming_requirements'};const rarityIndex=Math.max(0,TAME_RARITIES.indexOf(species.rarity));const faction=factionById(host,lr.faction.id);const tamePct=Number(faction?.bonuses?.taming)||0;const chance=clamp(.72+lr.taming.skill*.008+tamePct*.005+(-rarityIndex*.09)-int(species.temperament,0,100,50)*.002,.08,.95,.4);const succeeded=roll()<=chance;lr.taming.xp+=succeeded?18+rarityIndex*8:5;if(lr.taming.xp>=lr.taming.skill*50){lr.taming.xp-=lr.taming.skill*50;lr.taming.skill=Math.min(100,lr.taming.skill+1);}if(!succeeded)return {ok:false,reason:'resisted',chance,skill:lr.taming.skill};
    target.dead=true;target.hp=0;target.respawnAt=now+30000;const traits={};for(const [key,val] of Object.entries(species.baseTraits||{}))traits[key]=int(Number(val)+(roll()-.5)*12,1,100,50);const animal={id:`animal_${now}_${Math.random().toString(36).slice(2,8)}`,speciesId:species.id,name:species.name,icon:species.icon,rarity:species.rarity,roles:clone(species.roles||[]),traits,loyalty:int(traits.loyalty,1,100,50),bond:0,tamedAt:now,generation:1,mutation:null};lr.taming.animals.push(animal);if(!lr.taming.activeId)lr.taming.activeId=animal.id;const def=nodeAtMap(host,player.mapId);if(def)this.contributeNode(host,player,def.id,8+rarityIndex*3,'tame',now);if(rarityIndex>=2)this.chronicle(host,'taming',`${player.name} tamed ${species.name}.`,`A ${species.rarity} beast entered the chronicles.`,{mapId:player.mapId,actor:player.name,severity:rarityIndex>=4?'historic':'notable'},now);return {ok:true,animal:clone(animal),chance,skill:lr.taming.skill};
  }
  breed(host,player,parentAId,parentBId,now=Date.now(),roll=Math.random){
    const lr=ensurePlayer(host,player),a=lr.taming.animals.find(x=>x.id===parentAId),b=lr.taming.animals.find(x=>x.id===parentBId);if(!a||!b||a.id===b.id||a.speciesId!==b.speciesId||lr.taming.animals.length>=LIVING_REALM_LIMITS.animals||player.gold<500)return {ok:false,reason:'breeding_requirements'};const species=(catalogs(host).tamingSpecies||[]).find(s=>s.id===a.speciesId);if(!species?.breedable)return {ok:false,reason:'not_breedable'};player.gold-=500;const keys=new Set([...Object.keys(a.traits||{}),...Object.keys(b.traits||{})]);const traits={};for(const key of keys)traits[key]=int(((Number(a.traits?.[key])||50)+(Number(b.traits?.[key])||50))/2+(roll()-.5)*10,1,100,50);let mutation=null;if(roll()<.08){const key=[...keys][Math.floor(roll()*keys.size)]||'speed';traits[key]=int(traits[key]+12,1,100,traits[key]);mutation=`enhanced_${key}`;}const child={id:`animal_${now}_${Math.random().toString(36).slice(2,8)}`,speciesId:species.id,name:`${species.name} Offspring`,icon:species.icon,rarity:species.rarity,roles:clone(species.roles||[]),traits,loyalty:int((traits.loyalty||50)+5,1,100,55),bond:0,tamedAt:now,generation:Math.max(a.generation||1,b.generation||1)+1,parents:[a.id,b.id],mutation};lr.taming.animals.push(child);lr.taming.breedingCount++;if(mutation)this.chronicle(host,'breeding',`${player.name} bred a mutated ${species.name}.`,`Trait mutation: ${mutation.replace('enhanced_','')}.`,{mapId:player.mapId,actor:player.name,severity:'notable'},now);return {ok:true,animal:clone(child)};
  }
  activateAnimal(host,player,animalId){const lr=ensurePlayer(host,player);if(!animalId){lr.taming.activeId=null;return {ok:true,activeId:null};}if(!lr.taming.animals.some(a=>a.id===animalId))return {ok:false};lr.taming.activeId=animalId;return {ok:true,activeId:animalId};}
  onMonsterKill(host,player,monster,now=Date.now()){const def=nodeAtMap(host,player.mapId);if(!def)return null;const points=monster?.type==='boss'?30:monster?.type==='elite'?8:3;const result=this.contributeNode(host,player,def.id,points,'kill',now);const reagent=LIVING_REALM_REGIONAL_REAGENTS[player.mapId];if(reagent&&(monster?.type==='boss'||monster?.type==='elite'||Math.random()<.18)){const quantity=monster?.type==='boss'?3:monster?.type==='elite'?2:1;addInventory(player,{id:`lr_mat_${now}_${Math.random().toString(36).slice(2,8)}`,...reagent,type:'material',quantity});result.material={name:reagent.name,quantity};}if(monster?.type==='boss')this.chronicle(host,'boss',`${player.name} defeated ${monster.name}.`,`A regional boss fell in ${def.name}.`,{mapId:player.mapId,nodeId:def.id,actor:player.name,severity:'major'},now);return result;}
  publicRealm(host,player=null){const realm=ensureRealm(host);const defs=(catalogs(host).nodes||[]).map(normalizeNodeDefinition);const nodes=defs.filter(n=>n.enabled).map(def=>({...clone(realm.nodes[def.id]),name:def.name,mapId:def.mapId,specialization:def.specialization,x:def.x,y:def.y,radius:def.radius,taxRate:def.taxRate}));const result={nodes,chronicle:clone(realm.chronicle.slice(-50).reverse()),factions:clone(catalogs(host).factions||[]),materials:clone(catalogs(host).materials||[]),craftingRecipes:clone(catalogs(host).craftingRecipes||[]),tamingSpecies:clone(catalogs(host).tamingSpecies||[])};if(player)result.player=clone(ensurePlayer(host,player));return result;}
}
function lrFaction(player,host){return ensurePlayer(host,player).faction.id;}
export const livingRealmDomain=new LivingRealmDomain();
