// Mor'ia 9.17-9.26 — Road to 10 authoritative integration domain.
import { livingRealmDomain } from './LivingRealmDomain.mjs';

const clamp=(v,a,b,f=a)=>{const n=Number(v);return Number.isFinite(n)?Math.max(a,Math.min(b,n)):f};
const int=(v,a,b,f=a)=>Math.floor(clamp(v,a,b,f));
const text=(v,n=120)=>typeof v==='string'?v.trim().slice(0,n):'';
const slug=v=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'');
const clone=v=>v===undefined?undefined:structuredClone(v);
const isRecord=v=>Boolean(v&&typeof v==='object'&&!Array.isArray(v));
const playerKey=name=>String(name||'').trim().toLocaleLowerCase('en-US').slice(0,80);

export const ROAD_TO_TEN_VERSION='9.26.1';
export const ROAD_TO_TEN_LIMITS=Object.freeze({ledger:200,events:80,bounties:100,orders:30,discoveries:100,housingUpgrades:12,siegeAssets:12,choices:100,animalCare:40});

function content(host){return isRecord(host?.roadToTenContent)?host.roadToTenContent:{professionSpecializations:[],economyPolicies:[],factionPrograms:[],siegeAssets:[],dynamicWorldRules:[],dungeonBlueprints:[],questConsequences:[],housingUpgrades:[]};}
function nodeDefinitions(host){return Array.isArray(host?.livingRealmContent?.nodes)?host.livingRealmContent.nodes:[];}
function factionDefinitions(host){return Array.isArray(host?.livingRealmContent?.factions)?host.livingRealmContent.factions:[];}
function nodeDefinitionAt(host,mapId){return nodeDefinitions(host).find(n=>n?.mapId===mapId&&n?.enabled!==false)||null;}
function nodeStateAt(host,mapId){const def=nodeDefinitionAt(host,mapId);return def&&isRecord(host?.global?.livingRealm?.nodes?.[def.id])?host.global.livingRealm.nodes[def.id]:null;}
function factionDefinition(host,id){return factionDefinitions(host).find(f=>f?.id===id)||null;}
function playerFaction(host,player){return text(host?.ensurePlayer?.(player)?.livingRealm?.faction?.id,100)||null;}
function countInventory(player,name){return (Array.isArray(player?.inventory)?player.inventory:[]).filter(i=>i?.name===name).reduce((s,i)=>s+int(i.quantity,0,999999,0),0);}
function consumeInventory(player,name,qty){let left=qty;for(const item of Array.isArray(player?.inventory)?player.inventory:[]){if(item?.name!==name||left<=0)continue;const take=Math.min(left,int(item.quantity,0,999999,0));item.quantity-=take;left-=take;}if(Array.isArray(player?.inventory))player.inventory=player.inventory.filter(i=>Number(i.quantity)>0||i.type==='equipment');return left===0;}

function freshRegion(){return {supply:55,demand:50,prosperity:50,ecology:50,threat:35,corruption:10,crime:10,priceIndex:1,tradeVolume:0,goldSink:0,lastTick:0,activeEvents:[]};}
function freshFaction(){return {treasury:0,influence:0,leader:null,votes:{},weeklyProgress:0,objectiveCycle:0,lastObjectiveAt:0};}
function freshFortification(){return {wallHp:3000,wallMax:3000,gateHp:2200,gateMax:2200,towerHp:1800,towerMax:1800,supply:100,assets:[],lastActionAt:0};}
function freshGlobal(){return {version:ROAD_TO_TEN_VERSION,economy:{regions:{},ledger:[],inflationIndex:1},politics:{factions:{},diplomacy:{},bounties:[]},warfare:{nodes:{}},dynamicWorld:{regions:{},events:[],sequence:0},dungeons:{worldBosses:{},records:[]},questConsequences:{},housing:{shops:{}},sequence:0};}
function freshPlayer(){return {version:ROAD_TO_TEN_VERSION,professions:{specializations:{},discoveries:[],workOrders:[]},beastCare:{animals:{}},politics:{influence:0,votes:0,bountiesPlaced:0},warfare:{assetsBuilt:0,repairs:0,damage:0},dungeon:{blueprintId:null,path:null,puzzle:null,puzzleProgress:0,puzzleSolved:false},quests:{choices:{}},housing:{upgrades:[],shopOpen:false,shopName:'',homeScore:0}};}

function ensureGlobal(host){if(!host||!isRecord(host.global))throw new TypeError('RoadToTenDomain requires an OfficialSystems-compatible host.');if(!isRecord(host.global.roadToTen))host.global.roadToTen=freshGlobal();const g=host.global.roadToTen;
  if(!isRecord(g.economy))g.economy=freshGlobal().economy;if(!isRecord(g.economy.regions))g.economy.regions={};if(!Array.isArray(g.economy.ledger))g.economy.ledger=[];g.economy.inflationIndex=clamp(g.economy.inflationIndex,.75,1.5,1);
  if(!isRecord(g.politics))g.politics=freshGlobal().politics;if(!isRecord(g.politics.factions))g.politics.factions={};if(!isRecord(g.politics.diplomacy))g.politics.diplomacy={};if(!Array.isArray(g.politics.bounties))g.politics.bounties=[];
  if(!isRecord(g.warfare))g.warfare={nodes:{}};if(!isRecord(g.warfare.nodes))g.warfare.nodes={};
  if(!isRecord(g.dynamicWorld))g.dynamicWorld=freshGlobal().dynamicWorld;if(!isRecord(g.dynamicWorld.regions))g.dynamicWorld.regions={};if(!Array.isArray(g.dynamicWorld.events))g.dynamicWorld.events=[];
  if(!isRecord(g.dungeons))g.dungeons={worldBosses:{},records:[]};if(!isRecord(g.dungeons.worldBosses))g.dungeons.worldBosses={};if(!Array.isArray(g.dungeons.records))g.dungeons.records=[];
  if(!isRecord(g.questConsequences))g.questConsequences={};if(!isRecord(g.housing))g.housing={shops:{}};if(!isRecord(g.housing.shops))g.housing.shops={};
  for(const f of factionDefinitions(host)){if(f?.id&&!isRecord(g.politics.factions[f.id]))g.politics.factions[f.id]=freshFaction();}
  for(const n of nodeDefinitions(host)){if(n?.id&&!isRecord(g.warfare.nodes[n.id]))g.warfare.nodes[n.id]=freshFortification();if(n?.mapId&&!isRecord(g.economy.regions[n.mapId]))g.economy.regions[n.mapId]=freshRegion();if(n?.mapId&&!isRecord(g.dynamicWorld.regions[n.mapId]))g.dynamicWorld.regions[n.mapId]=freshRegion();}
  return g;
}
function ensurePlayer(host,player){const state=host.ensurePlayer(player);if(!isRecord(state.roadToTen))state.roadToTen=freshPlayer();const r=state.roadToTen;if(!isRecord(r.professions))r.professions=freshPlayer().professions;if(!isRecord(r.professions.specializations))r.professions.specializations={};if(!Array.isArray(r.professions.discoveries))r.professions.discoveries=[];if(!Array.isArray(r.professions.workOrders))r.professions.workOrders=[];if(!isRecord(r.beastCare))r.beastCare={animals:{}};if(!isRecord(r.beastCare.animals))r.beastCare.animals={};if(!isRecord(r.politics))r.politics=freshPlayer().politics;if(!isRecord(r.warfare))r.warfare=freshPlayer().warfare;if(!isRecord(r.dungeon))r.dungeon=freshPlayer().dungeon;if(!isRecord(r.quests))r.quests={choices:{}};if(!isRecord(r.quests.choices))r.quests.choices={};if(!isRecord(r.housing))r.housing=freshPlayer().housing;return r;}
function region(host,mapId){const g=ensureGlobal(host);if(!isRecord(g.economy.regions[mapId]))g.economy.regions[mapId]=freshRegion();return g.economy.regions[mapId];}
function dynamicRegion(host,mapId){const g=ensureGlobal(host);if(!isRecord(g.dynamicWorld.regions[mapId]))g.dynamicWorld.regions[mapId]=freshRegion();return g.dynamicWorld.regions[mapId];}
function fortification(host,nodeId){const g=ensureGlobal(host);if(!isRecord(g.warfare.nodes[nodeId]))g.warfare.nodes[nodeId]=freshFortification();return g.warfare.nodes[nodeId];}
function politics(host,factionId){const g=ensureGlobal(host);if(!isRecord(g.politics.factions[factionId]))g.politics.factions[factionId]=freshFaction();return g.politics.factions[factionId];}
function activeWorldEffects(host,mapId,now=Date.now()){const g=ensureGlobal(host);return g.dynamicWorld.events.filter(e=>e?.mapId===mapId&&Number(e.expiresAt)>now).map(e=>e.effects||{});}
function policy(host,mapId){const def=nodeDefinitionAt(host,mapId);return (content(host).economyPolicies||[]).find(p=>p?.specialization===(def?.specialization||'neutral'))||{buyMultiplier:1,sellMultiplier:1,craftDemand:1,taxEfficiency:1};}
function playerCraftSkill(host,player,profession){return int(host.ensurePlayer(player)?.livingRealm?.crafting?.skills?.[slug(profession)]?.level,1,100,1);}
function animalFor(host,player,animalId){return host.ensurePlayer(player)?.livingRealm?.taming?.animals?.find?.(a=>a?.id===animalId)||null;}
function housingBenefits(host,player){const rp=ensurePlayer(host,player),out={};for(const id of rp.housing.upgrades||[]){const up=(content(host).housingUpgrades||[]).find(x=>x?.id===id);for(const [k,v] of Object.entries(up?.benefits||{}))out[k]=(Number(out[k])||0)+(Number(v)||0);}return out;}
function puzzleSequence(blueprintId,runId){const seed=String(`${blueprintId}:${runId}`).split('').reduce((s,c)=>s+c.charCodeAt(0),0);return [0,1,2].map((_,i)=>(seed+i*3+i*i)%4);}

export class RoadToTenDomain{
  syncContent(host,c={}){host.roadToTenContent={professionSpecializations:clone(c.professionSpecializations||[]),economyPolicies:clone(c.economyPolicies||[]),factionPrograms:clone(c.factionPrograms||[]),siegeAssets:clone(c.siegeAssets||[]),dynamicWorldRules:clone(c.dynamicWorldRules||[]),dungeonBlueprints:clone(c.dungeonBlueprints||[]),questConsequences:clone(c.questConsequences||[]),housingUpgrades:clone(c.housingUpgrades||[])};ensureGlobal(host);return host.roadToTenContent;}

  integrationModifiers(host,player,now=Date.now()){
    const mapId=text(player?.mapId,100)||'eldoria',def=nodeDefinitionAt(host,mapId),node=nodeStateAt(host,mapId),r=region(host,mapId),p=policy(host,mapId),factionId=playerFaction(host,player),faction=factionDefinition(host,factionId),rep=int(host.ensurePlayer(player)?.livingRealm?.faction?.reputation,-5000,100000,0);let worldPrice=1,craftQuality=0,spawnThreat=1,tamingChance=0;
    for(const fx of activeWorldEffects(host,mapId,now)){worldPrice*=clamp(fx.shopPrice,.6,1.8,1);craftQuality+=clamp(fx.craftQuality,-20,20,0);spawnThreat*=clamp(fx.spawnThreat,.5,2,1);tamingChance+=clamp(fx.taming,-.5,.5,0);}
    const benefits=housingBenefits(host,player),taxReduction=clamp(Number(benefits.taxReduction)||0,0,20,0);const tax=Math.max(0,clamp(Number(def?.taxRate)||0,0,25,0)-taxReduction)/100;const sameControl=Boolean(node&&factionId&&node.controllerFactionId===factionId);const stage=int(node?.stage,0,6,0);const priceMultiplier=clamp(r.priceIndex*p.buyMultiplier*worldPrice*(1+tax),.65,1.75,1);
    craftQuality+=stage+(def?.specialization==='industrial'?4:0)+(sameControl?2:0)+Math.min(5,Math.max(0,Math.floor(rep/500)))+Number(faction?.bonuses?.craftQuality||0);
    return {mapId,nodeId:def?.id||null,nodeStage:stage,nodeSpecialization:def?.specialization||'neutral',factionId,priceMultiplier:Number(priceMultiplier.toFixed(3)),craftQualityBonus:Number(craftQuality.toFixed(2)),spawnThreatMultiplier:Number((spawnThreat*(1+r.threat/250)).toFixed(3)),tamingChanceBonus:Number(tamingChance.toFixed(3)),prosperity:int(r.prosperity,0,100,50),supply:int(r.supply,0,100,50),ecology:int(dynamicRegion(host,mapId).ecology,0,100,50),corruption:int(dynamicRegion(host,mapId).corruption,0,100,10)};
  }
  marketMultiplier(host,player){return this.integrationModifiers(host,player).priceMultiplier;}
  recordTrade(host,player,value,direction='buy',category='general',now=Date.now()){
    const amount=int(value,1,100_000_000,1),mapId=text(player?.mapId,100)||'eldoria',r=region(host,mapId),g=ensureGlobal(host),def=nodeDefinitionAt(host,mapId),node=nodeStateAt(host,mapId),p=policy(host,mapId);r.tradeVolume=int(r.tradeVolume+amount,0,1_000_000_000,0);r.demand=clamp(r.demand+(direction==='buy'?Math.min(8,amount/5000):-Math.min(5,amount/8000)),0,100,50);r.supply=clamp(r.supply+(direction==='sell'?Math.min(8,amount/5000):-Math.min(4,amount/10000)),0,100,50);r.prosperity=clamp(r.prosperity+Math.min(2,amount/25000),0,100,50);const scarcity=(r.demand-r.supply)/180;r.priceIndex=clamp(1+scarcity,.78,1.35,1);const tax=def?Math.floor(amount*(clamp(Number(def.taxRate)||0,0,25,0)/100)*clamp(p.taxEfficiency,.5,1.5,1)):0;if(node&&tax>0)node.treasury=int(node.treasury+tax,0,1_000_000_000,0);g.economy.ledger.push({at:now,mapId,player:playerKey(player?.name),direction,category:text(category,50),value:amount,tax});g.economy.ledger=g.economy.ledger.slice(-ROAD_TO_TEN_LIMITS.ledger);this.progressFactionProgram(host,player,'trade',amount,now);return {ok:true,mapId,value:amount,tax,priceIndex:Number(r.priceIndex.toFixed(3))};
  }
  onCraft(host,player,result,recipeId,now=Date.now(),roll=Math.random){if(!result?.ok)return null;const rp=ensurePlayer(host,player),recipe=(host.livingRealmContent?.craftingRecipes||[]).find(r=>r?.id===recipeId),profession=slug(recipe?.profession)||'crafting',skill=playerCraftSkill(host,player,profession),selected=rp.professions.specializations[profession],spec=(content(host).professionSpecializations||[]).find(s=>s?.id===selected);const discovered=Array.isArray(rp.professions.discoveries)?rp.professions.discoveries:[];const discoveryBonus=clamp(Number(housingBenefits(host,player).recipeDiscovery)||0,0,50,0)/100;if(skill>=20&&roll()<.12+Number(spec?.qualityBonus||0)/200+discoveryBonus){const pool=(host.livingRealmContent?.craftingRecipes||[]).filter(r=>slug(r.profession)===profession&&!discovered.includes(r.id));if(pool.length){const pick=pool[Math.floor(roll()*pool.length)%pool.length];discovered.push(pick.id);rp.professions.discoveries=discovered.slice(-ROAD_TO_TEN_LIMITS.discoveries);livingRealmDomain.chronicle(host,'discovery',`${player.name} discovered ${pick.name}.`,'A profession breakthrough entered the crafting record.',{mapId:player.mapId,actor:player.name,severity:'notable'},now);}}
    const def=nodeDefinitionAt(host,player.mapId),r=region(host,player.mapId);r.demand=clamp(r.demand+clamp(policy(host,player.mapId).craftDemand,.5,2,1),0,100,50);if(def?.specialization==='industrial')r.prosperity=clamp(r.prosperity+.5,0,100,50);this.progressFactionProgram(host,player,'craft',1,now);return {specialization:selected||null,discovered:clone(rp.professions.discoveries)};
  }
  chooseProfessionSpecialization(host,player,specId){const spec=(content(host).professionSpecializations||[]).find(s=>s?.id===specId);if(!spec)return {ok:false,reason:'specialization'};const profession=slug(spec.profession),skill=playerCraftSkill(host,player,profession),rp=ensurePlayer(host,player);if(skill<int(spec.requiredLevel,1,100,15))return {ok:false,reason:'skill'};if(rp.professions.specializations[profession]&&rp.professions.specializations[profession]!==spec.id)return {ok:false,reason:'already_specialized'};rp.professions.specializations[profession]=spec.id;return {ok:true,profession,specialization:spec.id,qualityBonus:Number(spec.qualityBonus)||0};}

  careAnimal(host,player,animalId,kind='feed',now=Date.now()){
    const animal=animalFor(host,player,animalId),rp=ensurePlayer(host,player);if(!animal)return {ok:false,reason:'animal'};if(!isRecord(rp.beastCare.animals[animal.id]))rp.beastCare.animals[animal.id]={happiness:60,health:100,training:0,role:null,lastCareAt:0};const care=rp.beastCare.animals[animal.id];const cost=kind==='train'?80:25;if(player.gold<cost)return {ok:false,reason:'gold'};if(now-care.lastCareAt<3000)return {ok:false,reason:'cooldown'};player.gold-=cost;care.lastCareAt=now;if(kind==='train'){care.training=int(care.training+1,0,100,0);const keys=Object.keys(animal.traits||{});if(keys.length){const key=keys[care.training%keys.length];animal.traits[key]=int(Number(animal.traits[key])+1,1,100,50);}animal.bond=int((animal.bond||0)+2,0,100,0);}else{care.happiness=int(care.happiness+12,0,100,60);care.health=int(care.health+5,0,100,100);animal.bond=int((animal.bond||0)+1,0,100,0);}return {ok:true,animal:clone(animal),care:clone(care)};
  }
  assignAnimalRole(host,player,animalId,role){const animal=animalFor(host,player,animalId),rp=ensurePlayer(host,player);const allowed=Array.isArray(animal?.roles)?animal.roles:[];if(!animal||!allowed.includes(role))return {ok:false,reason:'role'};if(!isRecord(rp.beastCare.animals[animal.id]))rp.beastCare.animals[animal.id]={happiness:60,health:100,training:0,role:null,lastCareAt:0};rp.beastCare.animals[animal.id].role=role;return {ok:true,animalId,role};}

  donateFaction(host,player,amount,now=Date.now()){
    const factionId=playerFaction(host,player),gold=int(amount,100,1000000,0);if(!factionId||gold<100||player.gold<gold)return {ok:false,reason:'faction_gold'};player.gold-=gold;const fp=politics(host,factionId),rp=ensurePlayer(host,player);fp.treasury=int(fp.treasury+gold,0,1_000_000_000,0);const influence=Math.max(1,Math.floor(gold/250));fp.influence=int(fp.influence+influence,0,100000000,0);rp.politics.influence=int(rp.politics.influence+influence,0,1000000,0);livingRealmDomain.chronicle(host,'politics',`${player.name} funded ${factionDefinition(host,factionId)?.name||factionId}.`,`Faction treasury received ${gold.toLocaleString()} gold.`,{factionId,actor:player.name,severity:'info'},now);return {ok:true,treasury:fp.treasury,influence};
  }
  voteLeader(host,player,candidateName,now=Date.now()){
    const factionId=playerFaction(host,player),candidate=text(candidateName,80),fp=factionId?politics(host,factionId):null,rp=ensurePlayer(host,player);if(!fp||!candidate||rp.politics.influence<5)return {ok:false,reason:'vote'};const voter=playerKey(player.name);if(fp.votes[voter])return {ok:false,reason:'already_voted'};rp.politics.influence-=5;rp.politics.votes=int(rp.politics.votes+1,0,100000,0);fp.votes[voter]=candidate;const tally={};for(const vote of Object.values(fp.votes))tally[vote]=(tally[vote]||0)+1;fp.leader=Object.entries(tally).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0]||candidate;livingRealmDomain.chronicle(host,'election',`${fp.leader} leads ${factionDefinition(host,factionId)?.name||factionId}.`,'Faction members changed their political leadership through player votes.',{factionId,actor:player.name,severity:'notable'},now);return {ok:true,leader:fp.leader,tally};
  }
  progressFactionProgram(host,player,kind,amount=1,now=Date.now()){
    const factionId=playerFaction(host,player),program=(content(host).factionPrograms||[]).find(x=>x?.factionId===factionId);if(!program||program.objective!==kind)return null;const fp=politics(host,factionId),week=7*86400000;if(!fp.lastObjectiveAt||now-fp.lastObjectiveAt>=week){fp.weeklyProgress=0;fp.lastObjectiveAt=now;}
    fp.weeklyProgress=clamp(Number(fp.weeklyProgress||0)+Math.max(0,Number(amount)||0),0,1_000_000_000,0);const target=Math.max(1,Number(program.target)||1);let completed=false,reward=0;if(fp.weeklyProgress>=target){completed=true;reward=int(program.rewardInfluence,0,1000000,0);fp.influence=int(fp.influence+reward,0,100000000,0);fp.weeklyProgress=Math.max(0,fp.weeklyProgress-target);fp.objectiveCycle=int(fp.objectiveCycle+1,0,1000000,0);fp.lastObjectiveAt=now;livingRealmDomain.chronicle(host,'faction_program',`${factionDefinition(host,factionId)?.name||factionId} completed ${program.name}.`,`Players completed the faction objective and earned ${reward} influence.`,{factionId,actor:player.name,severity:'major'},now);}return {programId:program.id,progress:fp.weeklyProgress,target,completed,reward};
  }
  claimBounties(host,killer,target,now=Date.now()){
    const g=ensureGlobal(host),targetKey=playerKey(target?.name),claims=g.politics.bounties.filter(b=>!b.claimed&&playerKey(b.target)===targetKey);if(!claims.length)return null;let reward=0;for(const b of claims){b.claimed=true;b.claimedAt=now;b.claimedBy=killer.name;reward+=int(b.reward,0,1000000,0);}killer.gold=int(Number(killer.gold)+reward,0,1_000_000_000,0);if(killer.stats)killer.stats.goldEarned=int(Number(killer.stats.goldEarned||0)+reward,0,1_000_000_000,0);this.progressFactionProgram(host,killer,'bounty',claims.length,now);livingRealmDomain.chronicle(host,'bounty',`${killer.name} claimed ${reward.toLocaleString()}g in bounties on ${target.name}.`,'A player bounty was resolved by authoritative PvP combat.',{mapId:killer.mapId,factionId:playerFaction(host,killer),actor:killer.name,severity:'notable'},now);return {ok:true,reward,count:claims.length};
  }

  setDiplomacy(host,player,targetFactionId,status,now=Date.now()){
    const factionId=playerFaction(host,player),fp=factionId?politics(host,factionId):null,target=factionDefinition(host,targetFactionId),allowed=['allied','neutral','rival','war'];if(!fp||fp.leader!==player.name||!target||targetFactionId===factionId||!allowed.includes(status))return {ok:false,reason:'diplomacy'};const g=ensureGlobal(host),key=[factionId,targetFactionId].sort().join('::');g.politics.diplomacy[key]={a:factionId,b:targetFactionId,status,changedAt:now,changedBy:player.name};livingRealmDomain.chronicle(host,'diplomacy',`${factionDefinition(host,factionId)?.name} and ${target.name}: ${status}.`,'Player-led diplomacy changed the political map.',{factionId,actor:player.name,severity:status==='war'?'historic':'major'},now);return {ok:true,status};
  }
  placeBounty(host,player,targetName,reward,now=Date.now()){
    const amount=int(reward,500,1_000_000,0),target=text(targetName,80),rp=ensurePlayer(host,player),g=ensureGlobal(host);if(!target||amount<500||target.toLowerCase()===String(player.name||'').toLowerCase()||player.gold<amount)return {ok:false,reason:'bounty'};player.gold-=amount;const bounty={id:`bounty_${now}_${g.sequence++}`,issuer:player.name,target,reward:amount,factionId:playerFaction(host,player),at:now,claimed:false};g.politics.bounties.push(bounty);g.politics.bounties=g.politics.bounties.slice(-ROAD_TO_TEN_LIMITS.bounties);rp.politics.bountiesPlaced=int(rp.politics.bountiesPlaced+1,0,100000,0);return {ok:true,bounty:clone(bounty)};
  }

  buildSiegeAsset(host,player,nodeId,assetId,now=Date.now()){
    const def=nodeDefinitions(host).find(n=>n?.id===nodeId),asset=(content(host).siegeAssets||[]).find(a=>a?.id===assetId),factionId=playerFaction(host,player),node=host.global?.livingRealm?.nodes?.[nodeId],fort=fortification(host,nodeId),rp=ensurePlayer(host,player);if(!def||!asset||!factionId||player.mapId!==def.mapId||!node||!['declared','siege','occupied','recovery'].includes(node.status))return {ok:false,reason:'siege_context'};const cost=int(asset.goldCost,0,1000000,0),mat=text(asset.material,100),qty=int(asset.materialQty,0,99,0);if(player.gold<cost||(mat&&countInventory(player,mat)<qty))return {ok:false,reason:'siege_resources'};player.gold-=cost;if(mat&&qty)consumeInventory(player,mat,qty);const siegeQuality=clamp(Number(housingBenefits(host,player).siegeQuality)||0,0,50,0);const built={id:`asset_${now}_${Math.random().toString(36).slice(2,7)}`,assetId:asset.id,ownerFactionId:factionId,durability:int(Number(asset.durability)*(1+siegeQuality/100),1,15000,500),builtBy:player.name,builtAt:now};fort.assets.push(built);fort.assets=fort.assets.slice(-ROAD_TO_TEN_LIMITS.siegeAssets);rp.warfare.assetsBuilt=int(rp.warfare.assetsBuilt+1,0,1000000,0);return {ok:true,asset:clone(built)};
  }
  useSiegeAsset(host,player,nodeId,builtAssetId,now=Date.now()){
    const def=nodeDefinitions(host).find(n=>n?.id===nodeId),node=host.global?.livingRealm?.nodes?.[nodeId],factionId=playerFaction(host,player),fort=fortification(host,nodeId),built=fort.assets.find(a=>a.id===builtAssetId),asset=(content(host).siegeAssets||[]).find(a=>a.id===built?.assetId),rp=ensurePlayer(host,player);if(!def||!node||!built||!asset||built.durability<=0||player.mapId!==def.mapId||now-fort.lastActionAt<800)return {ok:false,reason:'siege_asset'};fort.lastActionAt=now;const attacker=node.attackerFactionId===factionId,defender=node.controllerFactionId===factionId;if(asset.role==='repair'){if(!defender)return {ok:false,reason:'defender'};const repairBonus=clamp(Number(housingBenefits(host,player).repairBonus)||0,0,100,0);const heal=int(Number(asset.power)*(1+repairBonus/100),1,2000,50);fort.wallHp=Math.min(fort.wallMax,fort.wallHp+heal);fort.gateHp=Math.min(fort.gateMax,fort.gateHp+heal);fort.towerHp=Math.min(fort.towerMax,fort.towerHp+Math.floor(heal*.7));fort.supply=clamp(fort.supply-2,0,100,100);built.durability-=10;rp.warfare.repairs=int(rp.warfare.repairs+heal,0,100000000,0);return {ok:true,role:'repair',heal,fortification:clone(fort)};}
    if(!attacker||node.status!=='siege')return {ok:false,reason:'attacker'};const siegeQuality=clamp(Number(housingBenefits(host,player).siegeQuality)||0,0,50,0);const power=int(Number(asset.power)*(1+siegeQuality/100),1,3000,50);let target=asset.role==='gate'?'gateHp':asset.role==='tower'?'towerHp':'wallHp';if(asset.role==='supply'){fort.supply=clamp(fort.supply+12,0,100,100);built.durability-=8;return {ok:true,role:'supply',fortification:clone(fort)};}fort[target]=Math.max(0,fort[target]-power);built.durability-=12;rp.warfare.damage=int(rp.warfare.damage+power,0,100000000,0);this.progressFactionProgram(host,player,'siege',power,now);return {ok:true,role:asset.role,damage:power,fortification:clone(fort)};
  }

  evaluateWorld(host,mapId,now=Date.now()){
    const g=ensureGlobal(host),econ=region(host,mapId),dyn=dynamicRegion(host,mapId),node=nodeStateAt(host,mapId);if(node){dyn.supply=clamp(node.supply,0,100,50);dyn.morale=clamp(node.morale,0,100,50);}dyn.prosperity=clamp((dyn.prosperity*2+econ.prosperity)/3,0,100,50);const rules=content(host).dynamicWorldRules||[];for(const rule of rules){const val=Number(dyn[rule.metric]??econ[rule.metric]??50);const hit=rule.mode==='above'?val>=Number(rule.threshold):val<=Number(rule.threshold);const active=g.dynamicWorld.events.some(e=>e.ruleId===rule.id&&e.mapId===mapId&&e.expiresAt>now);if(hit&&!active){const def=nodeDefinitionAt(host,mapId),event={id:`world_${now}_${g.dynamicWorld.sequence++}`,ruleId:rule.id,name:rule.name,mapId,startedAt:now,expiresAt:now+int(rule.durationMs,60000,86400000,1200000),severity:rule.severity||'notable',effects:clone(rule.effects||{})};g.dynamicWorld.events.push(event);g.dynamicWorld.events=g.dynamicWorld.events.slice(-ROAD_TO_TEN_LIMITS.events);livingRealmDomain.chronicle(host,'world',`${rule.name} grips ${def?.name||mapId}.`,'The server simulation crossed a dynamic-world threshold.',{mapId,nodeId:def?.id,severity:event.severity},now);}}
    g.dynamicWorld.events=g.dynamicWorld.events.filter(e=>Number(e.expiresAt)>now).slice(-ROAD_TO_TEN_LIMITS.events);dyn.activeEvents=g.dynamicWorld.events.filter(e=>e.mapId===mapId).map(e=>e.id);return clone(dyn);
  }
  tick(host,now=Date.now()){
    const g=ensureGlobal(host);for(const def of nodeDefinitions(host)){if(!def?.mapId)continue;const r=region(host,def.mapId);const elapsed=Math.max(1,Math.min(60,(now-(r.lastTick||now-60000))/60000));r.lastTick=now;r.supply=clamp(r.supply+(50-r.supply)*.025*elapsed,0,100,50);r.demand=clamp(r.demand+(50-r.demand)*.02*elapsed,0,100,50);r.prosperity=clamp(r.prosperity+(50-r.prosperity)*.012*elapsed,0,100,50);r.priceIndex=clamp(1+(r.demand-r.supply)/180,.78,1.35,1);const d=dynamicRegion(host,def.mapId);d.threat=clamp(d.threat+(35-d.threat)*.015*elapsed,0,100,35);d.ecology=clamp(d.ecology+(50-d.ecology)*.01*elapsed,0,100,50);d.corruption=clamp(d.corruption*.995,0,100,10);this.evaluateWorld(host,def.mapId,now);}return this.publicSnapshot(host,null,now);
  }
  onMonsterKill(host,player,monster,now=Date.now()){
    const mapId=text(player?.mapId,100)||'eldoria',d=dynamicRegion(host,mapId),r=region(host,mapId),boss=monster?.type==='boss';d.threat=clamp(d.threat-(boss?8:monster?.type==='elite'?2:.35),0,100,35);d.ecology=clamp(d.ecology-(boss?1:.15),0,100,50);if(['death','shadow'].includes(String(monster?.damageType||'')))d.corruption=clamp(d.corruption-(boss?6:1),0,100,10);r.prosperity=clamp(r.prosperity+(boss?2:.08),0,100,50);if(boss){const g=ensureGlobal(host),id=text(monster?.contentSourceId||monster?.name,100)||'boss';const rec=g.dungeons.worldBosses[id]||{kills:0,firstDefeatAt:0,firstDefeatedBy:null};rec.kills=int(rec.kills+1,0,100000000,0);if(!rec.firstDefeatAt){rec.firstDefeatAt=now;rec.firstDefeatedBy=player.name;}rec.lastDefeatAt=now;g.dungeons.worldBosses[id]=rec;}return this.evaluateWorld(host,mapId,now);
  }

  startDungeonBlueprint(host,player,blueprintId,now=Date.now()){
    const bp=(content(host).dungeonBlueprints||[]).find(d=>d?.id===blueprintId),node=nodeStateAt(host,player.mapId),rp=ensurePlayer(host,player);if(!bp||bp.mapId!==player.mapId||player.level<int(bp.minLevel,1,100000,1)||int(node?.stage,0,6,0)<int(bp.requiredNodeStage,0,6,0))return {ok:false,reason:'dungeon_requirements'};const result=host.startDungeon(player,int(bp.waves,1,10,5));if(!result?.ok)return result;rp.dungeon={blueprintId:bp.id,path:null,puzzle:bp.puzzle||null,puzzleProgress:0,puzzleSolved:!bp.puzzle,startedAt:now};return {ok:true,blueprint:clone(bp),dungeon:result};
  }
  chooseDungeonPath(host,player,path){const rp=ensurePlayer(host,player),bp=(content(host).dungeonBlueprints||[]).find(d=>d?.id===rp.dungeon.blueprintId);if(!bp||!Array.isArray(bp.paths)||!bp.paths.includes(path)||rp.dungeon.path)return {ok:false,reason:'dungeon_path'};rp.dungeon.path=path;return {ok:true,path};}

  dungeonPresentation(host,player){const rp=ensurePlayer(host,player),bp=(content(host).dungeonBlueprints||[]).find(d=>d?.id===rp.dungeon.blueprintId);return bp?{id:bp.id,name:bp.name,icon:bp.icon,boss:bp.boss,puzzle:bp.puzzle,puzzleProgress:int(rp.dungeon.puzzleProgress,0,3,0),puzzleSolved:Boolean(rp.dungeon.puzzleSolved)}:null;}
  isDungeonPuzzlePending(host,player){const rp=ensurePlayer(host,player);return Boolean(rp.dungeon.blueprintId&&rp.dungeon.puzzle&&!rp.dungeon.puzzleSolved);}
  solveDungeonPuzzleStep(host,player,runeIndex){const rp=ensurePlayer(host,player),official=host.ensurePlayer(player)?.dungeon,bp=(content(host).dungeonBlueprints||[]).find(d=>d?.id===rp.dungeon.blueprintId);if(!bp||!official?.active||!rp.dungeon.puzzle||rp.dungeon.puzzleSolved)return {ok:false,reason:'puzzle'};const seq=puzzleSequence(bp.id,official.runId),progress=int(rp.dungeon.puzzleProgress,0,3,0),rune=int(runeIndex,0,3,-1);if(rune!==seq[progress]){rp.dungeon.puzzleProgress=0;return {ok:true,correct:false,progress:0,solved:false};}rp.dungeon.puzzleProgress=progress+1;rp.dungeon.puzzleSolved=rp.dungeon.puzzleProgress>=seq.length;return {ok:true,correct:true,progress:rp.dungeon.puzzleProgress,solved:rp.dungeon.puzzleSolved};}

  applyQuestConsequence(host,player,consequenceId,now=Date.now()){
    const c=(content(host).questConsequences||[]).find(x=>x?.id===consequenceId),rp=ensurePlayer(host,player),completed=Array.isArray(player?.quests)?player.quests:[];if(!c||!completed.includes(c.questId)||rp.quests.choices[c.questId])return {ok:false,reason:'quest_consequence'};rp.quests.choices[c.questId]=c.choice;const def=nodeDefinitionAt(host,player.mapId),node=nodeStateAt(host,player.mapId),econ=region(host,player.mapId),dyn=dynamicRegion(host,player.mapId);for(const [k,v] of Object.entries(c.nodeEffects||{})){if(k==='supply'&&node)node.supply=clamp(node.supply+Number(v),0,100,node.supply);else if(k==='morale'&&node)node.morale=clamp(node.morale+Number(v),0,100,node.morale);else if(['ecology','corruption','threat','crime'].includes(k))dyn[k]=clamp(Number(dyn[k])+Number(v),0,100,50);else if(k in econ)econ[k]=clamp(Number(econ[k])+Number(v),0,100,50);else if(k in dyn)dyn[k]=clamp(Number(dyn[k])+Number(v),0,100,50);}const factionId=playerFaction(host,player);if(factionId){const fp=politics(host,factionId),gain=int(c.factionEffects?.influence,0,10000,0);fp.influence=int(fp.influence+gain,0,100000000,0);rp.politics.influence=int(rp.politics.influence+gain,0,1000000,0);}livingRealmDomain.chronicle(host,'quest',text(c.chronicle,160)||`${player.name} changed the realm.`,`Quest choice: ${c.label||c.choice}.`,{mapId:player.mapId,nodeId:def?.id,factionId,actor:player.name,severity:'major'},now);return {ok:true,choice:c.choice,modifiers:this.integrationModifiers(host,player,now)};
  }

  buyHousingUpgrade(host,player,upgradeId,ownedHouseId=null,now=Date.now()){
    const up=(content(host).housingUpgrades||[]).find(u=>u?.id===upgradeId),rp=ensurePlayer(host,player);if(!up||rp.housing.upgrades.includes(up.id)||rp.housing.upgrades.length>=ROAD_TO_TEN_LIMITS.housingUpgrades||player.gold<int(up.goldCost,0,100000000,0))return {ok:false,reason:'housing_upgrade'};if(!text(ownedHouseId,100))return {ok:false,reason:'house_required'};player.gold-=int(up.goldCost,0,100000000,0);rp.housing.upgrades.push(up.id);rp.housing.homeScore=int(rp.housing.homeScore+int(up.level,1,10,1)*10,0,10000,0);if(up.category==='commerce')rp.housing.shopOpen=true;livingRealmDomain.chronicle(host,'housing',`${player.name} upgraded a home with ${up.name}.`,'Player housing gained a functional world-service upgrade.',{mapId:player.mapId,actor:player.name,severity:'notable'},now);return {ok:true,upgrade:clone(up),housing:clone(rp.housing)};
  }

  craftQualityBonus(host,player,now=Date.now()){
    const rp=ensurePlayer(host,player),base=this.integrationModifiers(host,player,now).craftQualityBonus;let spec=0;
    for(const id of Object.values(rp.professions.specializations||{})){const def=(content(host).professionSpecializations||[]).find(x=>x?.id===id);spec+=Number(def?.qualityBonus)||0;}
    let housing=0;for(const id of rp.housing.upgrades||[]){const up=(content(host).housingUpgrades||[]).find(x=>x?.id===id);housing+=Number(up?.benefits?.craftQuality)||0;}
    return clamp(base+spec+housing,-30,60,0);
  }
  tamingChanceBonus(host,player,now=Date.now()){
    const rp=ensurePlayer(host,player);let bonus=this.integrationModifiers(host,player,now).tamingChanceBonus;
    for(const id of rp.housing.upgrades||[]){const up=(content(host).housingUpgrades||[]).find(x=>x?.id===id);bonus+=Number(up?.benefits?.breedingBonus||0)/100;}
    const activeId=host.ensurePlayer(player)?.livingRealm?.taming?.activeId,care=rp.beastCare.animals?.[activeId];if(care)bonus+=(Number(care.happiness||60)-60)/1000;
    return clamp(bonus,-.4,.35,0);
  }
  breedingMutationBonus(host,player){const rp=ensurePlayer(host,player);let bonus=0;for(const id of rp.housing.upgrades||[]){const up=(content(host).housingUpgrades||[]).find(x=>x?.id===id);bonus+=Number(up?.benefits?.breedingBonus||0)/100;}return clamp(bonus,0,.25,0);}
  nodeSiegeMultiplier(host,nodeId){const f=fortification(host,nodeId),wall=f.wallMax?f.wallHp/f.wallMax:0,gate=f.gateMax?f.gateHp/f.gateMax:0;if(wall<=0&&gate<=0)return 1.25;if(gate<=0)return .9;if(wall<=.25)return .75;return .35;}
  spawnThreatMultiplier(host,mapId){const g=ensureGlobal(host),eventEffects=g.dynamicWorld.events.filter(e=>e?.mapId===mapId&&Number(e.expiresAt)>Date.now()).map(e=>e.effects||{});let mult=1+clamp(dynamicRegion(host,mapId).threat,0,100,35)/250;for(const fx of eventEffects)mult*=clamp(fx.spawnThreat,.5,2,1);return clamp(mult,.65,2.2,1);}
  completeDungeonBlueprint(host,player,completion,now=Date.now()){
    const rp=ensurePlayer(host,player),bp=(content(host).dungeonBlueprints||[]).find(d=>d?.id===rp.dungeon.blueprintId);if(!bp)return null;const econ=region(host,player.mapId),dyn=dynamicRegion(host,player.mapId);for(const [k,v] of Object.entries(bp.worldImpact||{})){if(['ecology','corruption','threat','crime'].includes(k))dyn[k]=clamp(Number(dyn[k])+Number(v),0,100,50);else if(k in econ)econ[k]=clamp(Number(econ[k])+Number(v),0,100,50);else if(k in dyn)dyn[k]=clamp(Number(dyn[k])+Number(v),0,100,50);}const g=ensureGlobal(host);g.dungeons.records.push({blueprintId:bp.id,player:player.name,path:rp.dungeon.path,at:now,completion:clone(completion)});g.dungeons.records=g.dungeons.records.slice(-200);livingRealmDomain.chronicle(host,'dungeon',`${player.name} cleared ${bp.name}.`,`Path: ${rp.dungeon.path||'direct'} · Boss: ${bp.boss}.`,{mapId:player.mapId,actor:player.name,severity:'major'},now);rp.dungeon={blueprintId:null,path:null,puzzle:null,puzzleProgress:0,puzzleSolved:false};return {ok:true,blueprintId:bp.id,worldImpact:clone(bp.worldImpact||{})};
  }

  publicSnapshot(host,player=null,now=Date.now()){
    const g=ensureGlobal(host),regions={};for(const def of nodeDefinitions(host)){if(def?.mapId)regions[def.mapId]={economy:clone(region(host,def.mapId)),dynamic:clone(dynamicRegion(host,def.mapId)),modifiers:player&&player.mapId===def.mapId?this.integrationModifiers(host,player,now):null};}
    const out={version:ROAD_TO_TEN_VERSION,regions,politics:clone(g.politics),warfare:clone(g.warfare),dynamicEvents:clone(g.dynamicWorld.events),worldBosses:clone(g.dungeons.worldBosses),content:clone(content(host))};if(player)out.player=clone(ensurePlayer(host,player));return out;
  }
}

export const roadToTenDomain=new RoadToTenDomain();
