import { Graphics } from 'pixi.js';
import type { IsoSceneNode } from './sceneModel';
import { findEntityArchetype } from './entityArchetypes';

function sideOf(n:Readonly<IsoSceneNode>){return n.facing==='nw'||n.facing==='sw'?-1:1;}
function phaseOf(n:Readonly<IsoSceneNode>){return (n.animationPhase??0)*Math.PI*2;}
function humanoid(g:Graphics,n:Readonly<IsoSceneNode>,role:'villager'|'guard'|'merchant'){const a=findEntityArchetype(n.visualId);if(!a)return;const s=sideOf(n),p=phaseOf(n),walk=n.motion==='walk',bob=walk?Math.abs(Math.sin(p))*2:Math.sin(p)*.5,stride=walk?Math.sin(p)*5:0;g.ellipse(0,17,24,8).fill({color:0,alpha:.28});g.poly([-13,-6-bob,13,-6-bob,11,25-bob,-11,25-bob]).fill(a.palette.secondary).stroke({width:2,color:0x20242a});g.circle(0,-22-bob,11).fill(0xd3a16f).stroke({width:2,color:0x654633});g.poly([-11,-28-bob,-3,-37-bob,9,-34-bob,12,-26-bob]).fill(role==='guard'?0x596b78:role==='merchant'?0x5d3e50:0x4b392d);g.poly([(-10+stride)*s,10-bob,(-8+stride)*s,26-bob,-3*s,26-bob,-3*s,9-bob]).fill(0x30343a);g.poly([(5-stride)*s,9-bob,(8-stride)*s,26-bob,13*s,26-bob,11*s,8-bob]).fill(0x30343a);if(role==='guard'){g.moveTo(16*s,-8-bob).lineTo(16*s,-43-bob).stroke({width:4,color:0xb9bec4});g.moveTo(9*s,-34-bob).lineTo(23*s,-34-bob).stroke({width:3,color:a.palette.accent});}if(role==='merchant'){g.roundRect(-19*s,-2-bob,13*s,19,4).fill(a.palette.primary);g.circle(-13*s,2-bob,3).fill(a.palette.accent);}if(role==='villager')g.poly([-12,-7-bob,12,-7-bob,8,5-bob,-8,5-bob]).fill(a.palette.primary);}
function wisp(g:Graphics,n:Readonly<IsoSceneNode>){const a=findEntityArchetype(n.visualId);if(!a)return;const p=phaseOf(n),float=Math.sin(p)*4;g.ellipse(0,17,15,5).fill({color:0,alpha:.14});g.circle(0,-12+float,16).fill({color:a.palette.primary,alpha:.13});g.circle(0,-12+float,8).fill({color:a.palette.primary,alpha:.72});g.circle(-2,-15+float,3).fill(a.palette.accent);for(let i=0;i<3;i++){const ang=p+i*Math.PI*2/3;g.circle(Math.cos(ang)*14,-12+float+Math.sin(ang)*8,2).fill({color:a.palette.accent,alpha:.7});}}
function boar(g:Graphics,n:Readonly<IsoSceneNode>){const a=findEntityArchetype(n.visualId);if(!a)return;const s=sideOf(n),p=phaseOf(n),stride=n.motion==='walk'?Math.sin(p)*5:0;g.ellipse(0,15,34,10).fill({color:0,alpha:.32});g.ellipse(-2*s,-4,30,17).fill(a.palette.primary).stroke({width:2,color:0x283328});g.ellipse(23*s,-5,16,13).fill(a.palette.secondary);g.poly([27*s,-1,39*s,4,29*s,5]).fill(0xdacba7);g.poly([18*s,-14,23*s,-25,27*s,-12]).fill(a.palette.primary);g.circle(28*s,-8,2.5).fill(a.palette.accent);g.poly([(-14+stride)*s,7,(-12+stride)*s,23,-6*s,23,-6*s,6]).fill(0x354235);g.poly([(7-stride)*s,7,(9-stride)*s,23,15*s,23,14*s,5]).fill(0x354235);}
export function drawAmbientEntityProcedural(g:Graphics,n:Readonly<IsoSceneNode>):boolean{switch(n.visualId){case'npc-villager':humanoid(g,n,'villager');return true;case'npc-guard':humanoid(g,n,'guard');return true;case'npc-merchant':humanoid(g,n,'merchant');return true;case'forest-wisp':wisp(g,n);return true;case'moss-boar':boar(g,n);return true;default:return false;}}
