import { ISO_ENTITY_ARCHETYPES, ambientBehaviorAt, type IsoAmbientBehavior, type IsoEntityArchetypeId } from './entityArchetypes';
import type { IsoFacing, IsoSceneNode } from './sceneModel';
import { isEldoriaNight, lifeSchedule, pointOfInterest } from './eldoriaLifeSchedule';

export type AmbientSpawnZone={id:string;center:{x:number;y:number};radius:number;archetypes:readonly IsoEntityArchetypeId[];budget:number};
export type AmbientPopulationEntity={id:string;archetypeId:IsoEntityArchetypeId;behavior:IsoAmbientBehavior;origin:{x:number;y:number};phase:number;speed:number};
export type AmbientPopulationFrame={entities:IsoSceneNode[];active:number;culled:number;night:boolean};
const DEFAULT_ZONES:readonly AmbientSpawnZone[]=[{id:'eldoria-square',center:{x:0,y:360},radius:260,archetypes:['eldoria-villager','eldoria-guard','eldoria-merchant'],budget:9},{id:'eldoria-grove',center:{x:-330,y:390},radius:250,archetypes:['forest-wisp','moss-boar'],budget:7},{id:'eldoria-edge',center:{x:350,y:330},radius:280,archetypes:['moss-boar','shadow-wolf'],budget:6}];
function hash(text:string):number{let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}function unit(seed:number):number{return((seed%10000)+.5)/10000;}function facing(dx:number,dy:number):IsoFacing{return Math.abs(dx)>Math.abs(dy)?(dx<0?'sw':'ne'):(dy<0?'nw':'se');}function lerp(a:number,b:number,t:number){return a+(b-a)*t;}
export class AmbientPopulationRuntime{
 private population:AmbientPopulationEntity[]=[];constructor(private readonly zones:readonly AmbientSpawnZone[]=DEFAULT_ZONES){this.population=this.buildPopulation();}
 sample(elapsedMs:number,camera:{x:number;y:number},renderDistance=760):AmbientPopulationFrame{const t=elapsedMs/1000,night=isEldoriaNight(elapsedMs),out:IsoSceneNode[]=[];let culled=0;for(const e of this.population){const a=ISO_ENTITY_ARCHETYPES.find(v=>v.id===e.archetypeId);if(!a)continue;const schedule=lifeSchedule(e.archetypeId),poi=schedule?pointOfInterest(night?schedule.night:schedule.day):undefined,behavior=schedule?(night?schedule.nightBehavior:schedule.dayBehavior):e.behavior,target=poi??{x:e.origin.x,y:e.origin.y,radius:80},transition=this.transitionFactor(elapsedMs),baseX=schedule?lerp(e.origin.x,target.x,transition):e.origin.x,baseY=schedule?lerp(e.origin.y,target.y,transition):e.origin.y,motion=this.motion(behavior,e,t,target.radius),x=baseX+motion.x,y=baseY+motion.y,dx=x-camera.x,dy=y-camera.y;if(dx*dx+dy*dy>renderDistance*renderDistance){culled++;continue;}out.push({id:e.id,layer:'entities',visualId:a.visualId,x,y,depth:y,facing:facing(motion.dx,motion.dy),motion:motion.walk?'walk':'idle',animationPhase:(t*e.speed+e.phase)%1,combatCue:'none'});}return{entities:out,active:out.length,culled,night};}
 private transitionFactor(elapsedMs:number){const cycle=((elapsedMs/1000)/180)%1,dayStart=.18,nightStart=.78,w=.055;if(cycle<dayStart)return 0;if(cycle<dayStart+w)return(cycle-dayStart)/w;if(cycle<nightStart)return 1;if(cycle<nightStart+w)return 1-(cycle-nightStart)/w;return 0;}
 private buildPopulation():AmbientPopulationEntity[]{const out:AmbientPopulationEntity[]=[];for(const zone of this.zones)for(let i=0;i<zone.budget;i++){const seed=hash(`${zone.id}:${i}`),angle=unit(seed)*Math.PI*2,radius=Math.sqrt(unit(seed>>>3))*zone.radius*.78,archetypeId=zone.archetypes[seed%zone.archetypes.length],a=ISO_ENTITY_ARCHETYPES.find(v=>v.id===archetypeId)!;out.push({id:`ambient:${zone.id}:${i}`,archetypeId,behavior:ambientBehaviorAt(a,seed>>>5),origin:{x:zone.center.x+Math.cos(angle)*radius,y:zone.center.y+Math.sin(angle)*radius*.55},phase:unit(seed>>>7),speed:.16+unit(seed>>>11)*.22});}return out;}
 private motion(behavior:IsoAmbientBehavior,e:AmbientPopulationEntity,t:number,radius:number){const p=t*e.speed+e.phase*Math.PI*2,range=Math.max(14,Math.min(radius*.55,90));if(behavior==='patrol')return{x:Math.sin(p)*range,y:Math.cos(p*.5)*range*.28,dx:Math.cos(p),dy:-Math.sin(p*.5)*.25,walk:true};if(behavior==='wander')return{x:Math.sin(p*.73)*range*.62,y:Math.cos(p*.51)*range*.38,dx:Math.cos(p*.73),dy:-Math.sin(p*.51),walk:true};if(behavior==='graze')return{x:Math.sin(p*.3)*range*.25,y:Math.cos(p*.25)*range*.14,dx:Math.cos(p*.3),dy:-Math.sin(p*.25),walk:Math.sin(p*.7)>.45};if(behavior==='hover')return{x:Math.sin(p)*range*.3,y:Math.cos(p*1.3)*range*.2-10,dx:Math.cos(p),dy:-Math.sin(p*1.3),walk:true};if(behavior==='watch')return{x:0,y:0,dx:Math.sin(p),dy:Math.cos(p),walk:false};return{x:0,y:0,dx:1,dy:1,walk:false};}
}
