export type IsoAssetKind = 'hero' | 'creature' | 'structure' | 'prop' | 'fx';
export type IsoAssetDirection = 'nw' | 'ne' | 'sw' | 'se' | 'omni';
export type IsoAssetAnimation = 'idle' | 'walk' | 'windup' | 'attack' | 'hit' | 'cast' | 'death' | 'ambient';
export type IsoAssetFrameSet = { atlas:string; prefix:string; frames:number; fps:number; loop:boolean };
export type IsoAssetDefinition = { id:string; kind:IsoAssetKind; direction:IsoAssetDirection; animation:IsoAssetAnimation; anchor:{x:number;y:number}; scale:number; shadow?:{width:number;height:number;alpha:number}; frames:IsoAssetFrameSet };
const DIRECTIONS:readonly Exclude<IsoAssetDirection,'omni'>[]=['nw','ne','sw','se'];
const EUPHORIA_ATLAS='/assets/iso-next/euphoria/euphoria.webp',WOLF_ATLAS='/assets/iso-next/creatures/shadow-wolf.webp';
const EUPHORIA_ANIMATIONS:readonly {animation:IsoAssetAnimation;frames:number;fps:number;loop:boolean}[]=[{animation:'idle',frames:8,fps:8,loop:true},{animation:'walk',frames:10,fps:12,loop:true},{animation:'windup',frames:6,fps:12,loop:false},{animation:'attack',frames:8,fps:15,loop:false},{animation:'hit',frames:5,fps:14,loop:false},{animation:'cast',frames:10,fps:15,loop:false},{animation:'death',frames:12,fps:12,loop:false}];
const WOLF_ANIMATIONS:readonly {animation:IsoAssetAnimation;frames:number;fps:number;loop:boolean}[]=[{animation:'idle',frames:8,fps:7,loop:true},{animation:'walk',frames:10,fps:13,loop:true},{animation:'windup',frames:6,fps:13,loop:false},{animation:'attack',frames:8,fps:17,loop:false},{animation:'hit',frames:5,fps:15,loop:false},{animation:'cast',frames:10,fps:15,loop:false},{animation:'death',frames:10,fps:12,loop:false}];
function directionalAssets(prefix:string,kind:IsoAssetKind,atlas:string,animations:typeof EUPHORIA_ANIMATIONS,anchorY:number):IsoAssetDefinition[]{const out:IsoAssetDefinition[]=[];for(const direction of DIRECTIONS)for(const spec of animations)out.push({id:`${prefix}-${spec.animation}-${direction}`,kind,direction,animation:spec.animation,anchor:{x:.5,y:anchorY},scale:1,shadow:{width:spec.animation==='attack'?66:prefix==='shadow-wolf'?62:58,height:spec.animation==='death'?13:prefix==='shadow-wolf'?16:18,alpha:prefix==='shadow-wolf'?.36:.34},frames:{atlas,prefix:`${spec.animation}_${direction}_`,frames:spec.frames,fps:spec.fps,loop:spec.loop}});return out;}
/** Production-facing manifest. Procedural rendering remains a safe fallback until atlases ship. */
export const ISO_ASSET_MANIFEST:readonly IsoAssetDefinition[]=[...directionalAssets('euphoria','hero',EUPHORIA_ATLAS,EUPHORIA_ANIMATIONS,.86),...directionalAssets('shadow-wolf','creature',WOLF_ATLAS,WOLF_ANIMATIONS,.78),{id:'eldoria-lantern',kind:'prop',direction:'omni',animation:'ambient',anchor:{x:.5,y:.95},scale:1,frames:{atlas:'/assets/iso-next/eldoria/props.webp',prefix:'lantern_',frames:6,fps:6,loop:true}},{id:'arcane-pulse',kind:'fx',direction:'omni',animation:'cast',anchor:{x:.5,y:.5},scale:1,frames:{atlas:'/assets/iso-next/fx/arcane.webp',prefix:'pulse_',frames:12,fps:18,loop:false}}];
export function findIsoAsset(kind:IsoAssetKind,animation:IsoAssetAnimation,direction:IsoAssetDirection):IsoAssetDefinition|undefined{return ISO_ASSET_MANIFEST.find(asset=>asset.kind===kind&&asset.animation===animation&&(asset.direction===direction||asset.direction==='omni'));}
export function frameName(asset:IsoAssetDefinition,frame:number):string{const safe=Math.max(0,Math.min(asset.frames.frames-1,Math.floor(frame)));return `${asset.frames.prefix}${String(safe).padStart(2,'0')}`;}
