import { useState } from 'react';
import { DraggableIsoWindow } from './DraggableIsoWindow';
import { serverSync } from '../ServerSync';

const btn:React.CSSProperties={border:'1px solid rgba(238,203,126,.28)',background:'rgba(17,21,29,.92)',color:'#f4e8c8',borderRadius:8,padding:'7px 9px',cursor:'pointer'};
export function IsoAuthoritativeEconomy({snapshot}:{snapshot:any}){
 const interaction=snapshot?.interaction??snapshot?.activeInteraction??null;const npc=interaction?.npc??snapshot?.dialogue?.npc??snapshot?.activeNpc??null;const official=snapshot?.official??{};const player=snapshot?.player??{};const role=String(npc?.role??'');const [amount,setAmount]=useState('100');
 const send=(action:string,payload:Record<string,unknown>={})=>serverSync.sendOfficial(action,payload);
 if(!npc||!['merchant','banker'].includes(role))return null;
 if(role==='merchant'){
  const stock=Array.isArray(npc.shop)?npc.shop:Array.isArray(official?.shop)?official.shop:[];
  return <DraggableIsoWindow id="authoritative-merchant" title={`Mercador · ${npc.name??'Loja'}`} initial={{x:70,y:150}} width={430}><div style={{padding:12,color:'#f4e8c8'}}><div style={{fontSize:12,opacity:.7,marginBottom:8}}>Ouro: {Number(player.gold??0).toLocaleString('pt-BR')}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}>{stock.map((item:any,i:number)=><div key={String(item.id??i)} style={{padding:9,border:'1px solid rgba(255,255,255,.08)',borderRadius:9,background:'rgba(255,255,255,.025)'}}><b>{item.icon??'◈'} {item.name??item.id}</b><div style={{fontSize:11,opacity:.65,margin:'4px 0 8px'}}>{Number(item.price??item.cost??0).toLocaleString('pt-BR')} ouro</div><button style={btn} onClick={()=>send('shop_buy',{itemId:item.id,quantity:1})}>Comprar</button></div>)}</div>{stock.length===0&&<div style={{opacity:.65}}>Nenhum item disponível neste mercador.</div>}</div></DraggableIsoWindow>;
 }
 const bank=official?.bank??snapshot?.bank??{};const depot=Array.isArray(official?.depot)?official.depot:Array.isArray(snapshot?.depot)?snapshot.depot:[];const inventory=Array.isArray(player.inventory)?player.inventory:Array.isArray(snapshot?.inventory)?snapshot.inventory:[];
 return <><DraggableIsoWindow id="authoritative-bank" title={`Banco · ${npc.name??'Banqueiro'}`} initial={{x:70,y:150}} width={390}><div style={{padding:12,color:'#f4e8c8',display:'grid',gap:9}}><div>Carteira: <b>{Number(player.gold??0).toLocaleString('pt-BR')}</b> · Banco: <b>{Number(bank.gold??bank.balance??official?.bankGold??0).toLocaleString('pt-BR')}</b></div><input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9]/g,''))} inputMode="numeric" style={{padding:8,borderRadius:7,background:'rgba(0,0,0,.25)',color:'#fff',border:'1px solid rgba(255,255,255,.12)'}}/><div style={{display:'flex',gap:7}}><button style={btn} onClick={()=>send('bank_deposit',{amount:Number(amount)||0})}>Depositar</button><button style={btn} onClick={()=>send('bank_withdraw',{amount:Number(amount)||0})}>Sacar</button></div></div></DraggableIsoWindow><DraggableIsoWindow id="authoritative-depot" title={`Depot · ${depot.length}/40`} initial={{x:480,y:150}} width={430}><div style={{padding:12,color:'#f4e8c8',display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><section><b>Inventário</b>{inventory.slice(0,20).map((item:any,i:number)=><button key={String(item.id??i)} style={{...btn,width:'100%',marginTop:5,textAlign:'left'}} onClick={()=>send('depot_put',{itemId:item.id})}>{item.icon??'◇'} {item.name??item.id} →</button>)}</section><section><b>Depot</b>{depot.slice(0,40).map((item:any,i:number)=><button key={String(item.depotId??item.id??i)} style={{...btn,width:'100%',marginTop:5,textAlign:'left'}} onClick={()=>send('depot_take',{depotId:item.depotId??item.id})}>← {item.icon??'◇'} {item.name??item.id}</button>)}</section></div></DraggableIsoWindow></>;
}
