import { dispatchIsoAction, type IsoGameplaySnapshot } from './isoGameplayActions';
import { IsoItemTooltip } from './IsoTooltip';

type ItemLike = { id?: string; itemId?: string; name?: string; icon?: string; quantity?: number; qty?: number; slot?: string; rarity?: string; description?: string; value?: number; price?: number; level?: number; equipment?: Record<string, unknown>; stats?: Record<string, unknown> };
type GroundLike = ItemLike & { groundId?: string };

const itemId = (item: ItemLike) => String(item.itemId || item.id || '');
const label = (item: ItemLike) => item.name || itemId(item) || 'Item';

export function IsoGameplayPanel({ state, onClose }: { state: IsoGameplaySnapshot; onClose: () => void }) {
  const equipment = Object.entries(state.equipment || {}).filter(([, value]) => Boolean(value));
  return <aside data-testid="iso-gameplay-panel" style={{position:'absolute',right:20,top:82,width:390,maxHeight:'calc(100% - 120px)',overflow:'auto',padding:16,borderRadius:18,background:'linear-gradient(180deg,rgba(14,20,29,.97),rgba(6,9,14,.95))',border:'1px solid rgba(238,203,126,.35)',boxShadow:'0 22px 60px rgba(0,0,0,.55)',color:'#f4e8c8',fontFamily:'system-ui',backdropFilter:'blur(14px)'}}>
    <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14}}><div><strong style={{fontSize:18}}>Mochila & Equipamento</strong><div style={{fontSize:11,opacity:.6}}>Estado autoritativo</div></div><button onClick={onClose}>×</button></header>
    <section><small style={{opacity:.65,textTransform:'uppercase',letterSpacing:'.12em'}}>Equipado</small><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7,marginTop:8}}>{equipment.length?equipment.map(([slot,raw])=>{const item=raw as ItemLike;return <IsoItemTooltip key={slot} item={{...item,slot:item.slot||slot}}><button data-testid={`iso-equipped-${slot}`} onClick={()=>dispatchIsoAction({kind:'unequip',slot})} title="Clique para desequipar" style={{width:'100%',padding:9,textAlign:'left',borderRadius:10,border:'1px solid rgba(238,203,126,.22)',background:'rgba(255,255,255,.05)',color:'inherit',cursor:'help'}}><b>{slot}</b><br/><span>{item.icon||'◆'} {label(item)}</span></button></IsoItemTooltip>}):<div style={{opacity:.5,padding:8}}>Nenhum equipamento no snapshot.</div>}</div></section>
    <section style={{marginTop:16}}><small style={{opacity:.65,textTransform:'uppercase',letterSpacing:'.12em'}}>Inventário · {state.inventory.length}</small><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:7,marginTop:8}}>{state.inventory.map((raw,index)=>{const item=raw as ItemLike;const id=itemId(item);return <IsoItemTooltip key={`${id}-${index}`} item={item}><button data-testid={`iso-inventory-item-${index}`} disabled={!id} onClick={()=>dispatchIsoAction({kind:'use-item',itemId:id})} onContextMenu={e=>{e.preventDefault();if(id)dispatchIsoAction({kind:'equip',itemId:id});}} title="Clique: usar · botão direito: equipar" style={{width:'100%',minHeight:68,padding:6,borderRadius:10,border:'1px solid rgba(238,203,126,.2)',background:'rgba(255,255,255,.045)',color:'inherit',fontSize:11,cursor:'help'}}><div style={{fontSize:22}}>{item.icon||'◇'}</div><div>{label(item)}</div>{(item.quantity||item.qty)&&<b>×{item.quantity||item.qty}</b>}</button></IsoItemTooltip>})}</div></section>
    <section style={{marginTop:16}}><small style={{opacity:.65,textTransform:'uppercase',letterSpacing:'.12em'}}>Loot próximo · {state.groundItems.length}</small><div style={{display:'grid',gap:6,marginTop:8}}>{state.groundItems.slice(0,8).map((raw,index)=>{const item=raw as GroundLike;const id=String(item.groundId||item.id||'');return <IsoItemTooltip key={`${id}-${index}`} item={item}><button data-testid={`iso-ground-item-${index}`} disabled={!id} onClick={()=>dispatchIsoAction({kind:'pickup',groundId:id})} style={{width:'100%',display:'flex',justifyContent:'space-between',padding:'8px 10px',borderRadius:9,border:'1px solid rgba(105,206,147,.25)',background:'rgba(50,130,85,.09)',color:'inherit',cursor:'help'}}><span>{item.icon||'✦'} {label(item)}</span><b>PEGAR</b></button></IsoItemTooltip>})}{!state.groundItems.length&&<div style={{opacity:.5,padding:8}}>Nenhum loot próximo.</div>}</div></section>
  </aside>;
}
