import { DraggableIsoWindow } from './DraggableIsoWindow';

type LegacyWindowId='character'|'quests'|'spellbook'|'talents'|'map'|'crafting'|'bestiary'|'dps'|'depot'|'mail'|'auction'|'social'|'pets'|'dungeons'|'mounts'|'housing'|'events';
type Snapshot=Record<string,any>;
const DEFINITIONS:Array<[LegacyWindowId,string,string]>= [
 ['character','Personagem','C'],['quests','Quest Log','Q'],['spellbook','Spellbook','K'],['talents','Talentos & Profissões','T'],['map','Mapa & Viagem','G'],['crafting','Crafting','R'],['bestiary','Bestiário','B'],['dps','DPS Meter','P'],['depot','Depot','O'],['mail','Correio','L'],['auction','Auction House','U'],['social','Social','H'],['pets','Pets','N'],['dungeons','Dungeons','D'],['mounts','Montarias','M'],['housing','Housing','Y'],['events','World Events','V']
];
const list=(value:any)=>Array.isArray(value)?value:[];
function body(id:LegacyWindowId,s:Snapshot){const p=s.player||{};const data:Record<LegacyWindowId,any[]>={character:[{name:p.name||'Aventureiro',level:p.level||1,vocation:p.vocation||'—'},{name:`HP ${p.hp??0}/${p.maxHp??0}`},{name:`Mana ${p.mana??0}/${p.maxMana??0}`}],quests:list(p.activeQuests||s.quests),spellbook:list(p.spells||s.spells),talents:[...list(p.talents),...list(p.professions)],map:[{name:s.map?.name||s.mapId||p.mapId||'Mundo atual'}],crafting:list(p.recipes||s.recipes||s.crafting),bestiary:list(p.bestiary||s.bestiary),dps:list(s.combatStats||s.dps),depot:list(p.depot||s.depot),mail:list(p.mail||s.mail),auction:list(s.auctions||s.auction),social:list(p.friends||s.social),pets:list(p.pets||s.pets),dungeons:list(s.dungeons||p.dungeons),mounts:list(p.mounts),housing:list(p.housing||s.housing),events:list(s.worldEvents||s.events)};return data[id]||[];}
export function IsoLegacyWindowRegistry({snapshot,open,onToggle}:{snapshot:Snapshot;open:Set<LegacyWindowId>;onToggle:(id:LegacyWindowId)=>void}){return <>{DEFINITIONS.map(([id,title,key],index)=>{if(!open.has(id))return null;const rows=body(id,snapshot);return <DraggableIsoWindow key={id} id={`legacy-${id}`} title={`${title} [${key}]`} initial={{x:24+(index%4)*36,y:86+(index%5)*34}} width={340} onClose={()=>onToggle(id)}><div style={{padding:12,color:'#f4e8c8',fontFamily:'system-ui'}}>{rows.length?rows.slice(0,30).map((row:any,i)=><div key={row.id||row.questId||row.name||i} style={{padding:'8px 9px',marginBottom:6,borderRadius:9,border:'1px solid rgba(238,203,126,.15)',background:'rgba(255,255,255,.035)'}}><b>{row.name||row.title||row.id||row.questId||title}</b>{row.description&&<div style={{fontSize:11,opacity:.65,marginTop:3}}>{row.description}</div>}{row.level!=null&&<small> · Nv {row.level}</small>}</div>):<div style={{padding:12,opacity:.55}}>Sem dados autoritativos disponíveis neste snapshot.</div>}</div></DraggableIsoWindow>})}</>}
export { DEFINITIONS as ISO_LEGACY_WINDOWS };export type { LegacyWindowId };
