import { dispatchIsoAction, type IsoGameplaySnapshot } from './isoGameplayActions';

type Tab='quests'|'progress'|'world'|'social';
export function IsoLegacySystemsDock({state,tab,onTab}:{state:IsoGameplaySnapshot;tab:Tab;onTab:(tab:Tab)=>void}){
 const tabs:[Tab,string][]=[['quests','Quests & Tasks'],['progress','Talentos & Profissões'],['world','Mundo & Montarias'],['social','Social & Housing']];
 const box:React.CSSProperties={padding:10,borderRadius:10,border:'1px solid rgba(238,203,126,.18)',background:'rgba(255,255,255,.04)'};
 return <aside data-testid="iso-legacy-dock" style={{position:'absolute',left:20,top:82,width:330,maxHeight:420,overflow:'auto',padding:12,borderRadius:16,background:'rgba(7,11,17,.94)',border:'1px solid rgba(238,203,126,.28)',boxShadow:'0 18px 50px rgba(0,0,0,.48)',color:'#f4e8c8',fontFamily:'system-ui',backdropFilter:'blur(12px)'}}>
  <nav style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:5,marginBottom:10}}>{tabs.map(([id,name])=><button key={id} onClick={()=>onTab(id)} style={{padding:7,borderRadius:8,border:'1px solid rgba(238,203,126,.18)',background:tab===id?'rgba(238,203,126,.16)':'rgba(255,255,255,.03)',color:'inherit'}}>{name}</button>)}</nav>
  {tab==='quests'&&<div style={{display:'grid',gap:7}}><div style={box}><b>Quests ativas · {state.activeQuests.length}</b>{state.activeQuests.slice(0,5).map((q:any,i)=><div key={q.questId||q.id||i} style={{marginTop:5,fontSize:12}}>{q.name||q.title||q.questId||q.id||'Quest'}</div>)}</div><div style={box}><b>Tasks · {state.tasks.length}</b>{state.tasks.slice(0,5).map((t:any,i)=><div key={t.id||i} style={{marginTop:5,fontSize:12}}>{t.name||t.title||t.id||'Task'}</div>)}</div></div>}
  {tab==='progress'&&<div style={{display:'grid',gap:7}}><div style={box}><b>Talentos · {state.talents.length}</b>{state.talents.slice(0,8).map((t:any,i)=><button key={t.id||i} onClick={()=>t.id&&dispatchIsoAction({kind:'talent',talentId:t.id})} style={{display:'block',width:'100%',marginTop:5}}>{t.name||t.id||'Talento'}</button>)}</div><div style={box}><b>Profissões · {state.professions.length}</b>{state.professions.slice(0,6).map((p:any,i)=><div key={p.id||i} style={{marginTop:5,fontSize:12}}>{p.name||p.id||'Profissão'} {p.level?`· Nv ${p.level}`:''}</div>)}</div></div>}
  {tab==='world'&&<div style={{display:'grid',gap:7}}><div style={box}><b>Montarias · {state.mounts.length}</b>{state.mounts.slice(0,6).map((m:any,i)=><button key={m.id||i} onClick={()=>dispatchIsoAction({kind:'mount',action:'toggle',payload:m.id?{mountId:m.id}:{}})} style={{display:'block',width:'100%',marginTop:5}}>{m.name||m.id||'Montaria'}</button>)}</div><div style={box}><b>Viagem</b><div style={{display:'flex',gap:5,marginTop:6}}>{['eldoria','valoria','moria'].map(map=><button key={map} onClick={()=>dispatchIsoAction({kind:'travel',targetMap:map})}>{map}</button>)}</div></div></div>}
  {tab==='social'&&<div style={{display:'grid',gap:7}}><div style={box}><b>Social</b><div style={{display:'flex',gap:5,marginTop:6}}><button onClick={()=>dispatchIsoAction({kind:'social',action:'refresh'})}>Atualizar</button><button onClick={()=>dispatchIsoAction({kind:'social',action:'party_status'})}>Grupo</button></div></div><div style={box}><b>Housing & Aparência</b><div style={{display:'flex',gap:5,flexWrap:'wrap',marginTop:6}}><button onClick={()=>dispatchIsoAction({kind:'housing',action:'status'})}>Casa</button><button onClick={()=>dispatchIsoAction({kind:'appearance',action:'status'})}>Visual</button></div></div></div>}
 </aside>;
}
