import { DraggableIsoWindow } from './DraggableIsoWindow';
import { IsoAuthoritativeCharacter } from './IsoAuthoritativeCharacter';
import { IsoAuthoritativeQuestLog, IsoAuthoritativeSpellbook } from './IsoAuthoritativeJournal';
import { IsoAuthoritativeCrafting } from './IsoAuthoritativeCrafting';
import { IsoAuthoritativeDepot, IsoAuthoritativeMail, IsoAuthoritativeAuction } from './IsoAuthoritativeServices';
import { IsoAuthoritativeBestiary, IsoAuthoritativeDps, IsoAuthoritativePets, IsoAuthoritativeDungeons } from './IsoAuthoritativeCombatWorld';
import { IsoAuthoritativeProgression, IsoAuthoritativeTravel, IsoAuthoritativeSocial, IsoAuthoritativeMounts, IsoAuthoritativeHousing, IsoAuthoritativeEvents } from './IsoAuthoritativeRealm';

type LegacyWindowId='character'|'quests'|'spellbook'|'talents'|'map'|'crafting'|'bestiary'|'dps'|'depot'|'mail'|'auction'|'social'|'pets'|'dungeons'|'mounts'|'housing'|'events';
type Snapshot=Record<string,any>;
const DEFINITIONS:Array<[LegacyWindowId,string,string]>= [['character','Personagem','C'],['quests','Quest Log','Q'],['spellbook','Spellbook','K'],['talents','Talentos & Profissões','T'],['map','Mapa & Viagem','G'],['crafting','Crafting','R'],['bestiary','Bestiário','B'],['dps','DPS Meter','P'],['depot','Depot','O'],['mail','Correio','L'],['auction','Auction House','U'],['social','Social','H'],['pets','Pets','N'],['dungeons','Dungeons','D'],['mounts','Montarias','M'],['housing','Housing','Y'],['events','World Events','V']];
function specialized(id:LegacyWindowId,snapshot:Snapshot){switch(id){case'character':return <IsoAuthoritativeCharacter player={snapshot.player||{}}/>;case'quests':return <IsoAuthoritativeQuestLog snapshot={snapshot}/>;case'spellbook':return <IsoAuthoritativeSpellbook snapshot={snapshot} targetId={snapshot?.interaction?.targetId}/>;case'talents':return <IsoAuthoritativeProgression snapshot={snapshot}/>;case'map':return <IsoAuthoritativeTravel snapshot={snapshot}/>;case'crafting':return <IsoAuthoritativeCrafting snapshot={snapshot}/>;case'bestiary':return <IsoAuthoritativeBestiary snapshot={snapshot}/>;case'dps':return <IsoAuthoritativeDps snapshot={snapshot}/>;case'depot':return <IsoAuthoritativeDepot snapshot={snapshot}/>;case'mail':return <IsoAuthoritativeMail snapshot={snapshot}/>;case'auction':return <IsoAuthoritativeAuction snapshot={snapshot}/>;case'social':return <IsoAuthoritativeSocial snapshot={snapshot}/>;case'pets':return <IsoAuthoritativePets snapshot={snapshot}/>;case'dungeons':return <IsoAuthoritativeDungeons snapshot={snapshot}/>;case'mounts':return <IsoAuthoritativeMounts snapshot={snapshot}/>;case'housing':return <IsoAuthoritativeHousing snapshot={snapshot}/>;case'events':return <IsoAuthoritativeEvents snapshot={snapshot}/>;}}
export function IsoLegacyWindowRegistry({snapshot,open,onToggle}:{snapshot:Snapshot;open:Set<LegacyWindowId>;onToggle:(id:LegacyWindowId)=>void}){return <>{DEFINITIONS.map(([id,title,key],index)=>{if(!open.has(id))return null;return <DraggableIsoWindow key={id} id={`legacy-${id}`} title={`${title} [${key}]`} initial={{x:24+(index%4)*36,y:86+(index%5)*34}} width={id==='character'?430:400} onClose={()=>onToggle(id)}>{specialized(id,snapshot)}</DraggableIsoWindow>})}</>}
export { DEFINITIONS as ISO_LEGACY_WINDOWS };export type { LegacyWindowId };
