import { useEffect, useRef, useState } from 'react';
import DialogBox from '../../components/DialogBox';
import type { NPC, Player, Quest } from '../types';
import { serverNpcToClient, serverQuestToClient } from '../serverContentAdapters';
import { ELDORIA_ISO_FIXTURE } from './eldoriaFixture';
import { EuphoriaPresentationRuntime } from './euphoriaRuntime';
import { PixiIsoRenderer } from './PixiIsoRenderer';
import { bridgeServerSnapshot } from './serverPresentationBridge';
import { serverSync } from '../ServerSync';
import type { InteractionState } from './interactionLayer';

const ROLE:Record<string,string>={'npc-villager':'Habitante de Eldoria','npc-guard':'Guarda de Eldoria','npc-merchant':'Mercador','forest-wisp':'Wisp da Floresta','moss-boar':'Javali Musgoso','shadow-wolf':'Lobo das Sombras'};
const MOVE_KEYS:Record<string,{dx:number;dy:number}>={ArrowUp:{dx:0,dy:-1},KeyW:{dx:0,dy:-1},ArrowDown:{dx:0,dy:1},KeyS:{dx:0,dy:1},ArrowLeft:{dx:-1,dy:0},KeyA:{dx:-1,dy:0},ArrowRight:{dx:1,dy:0},KeyD:{dx:1,dy:0}};

type IsoSnapshot={player?:Player;npcs?:unknown[];quests?:unknown[];interaction?:{state?:string;targetId?:string;kind?:string}};

export function IsoNextPrototype(){
 const hostRef=useRef<HTMLDivElement>(null);const runtimeRef=useRef<EuphoriaPresentationRuntime|null>(null);const interactionRef=useRef<InteractionState>({candidate:null,inRange:false});const snapshotRef=useRef<IsoSnapshot|null>(null);const[interaction,setInteraction]=useState<InteractionState>({candidate:null,inRange:false});const[live,setLive]=useState(false);const[dialogNpc,setDialogNpc]=useState<NPC|null>(null);const[dialogPlayer,setDialogPlayer]=useState<Player|null>(null);const[questCatalog,setQuestCatalog]=useState<Quest[]>([]);
 const syncInteraction=(next:InteractionState)=>{interactionRef.current=next;setInteraction(next);};
 const openNpcDialogue=(targetId:string)=>{const snap=snapshotRef.current;if(!snap?.player)return false;const quests=(snap.quests||[]).map(serverQuestToClient).filter((q):q is Quest=>Boolean(q));const converted=(snap.npcs||[]).map(raw=>serverNpcToClient(raw,quests)).find(entry=>entry?.npc.id===targetId);if(!converted)return false;setQuestCatalog(quests);setDialogPlayer(snap.player);setDialogNpc(converted.npc);return true;};
 const interact=()=>{const request=runtimeRef.current?.interactionRequest();if(!request)return false;const sent=serverSync.sendInteraction(request.targetEntityId,request.kind);if(sent&&(request.kind==='talk'||request.kind==='trade'))openNpcDialogue(request.targetEntityId);return sent;};
 const onDialogAction=(action:string,questId?:string)=>{if(action==='bye'){setDialogNpc(null);return;}if(action==='quest'&&questId){const active=dialogPlayer?.activeQuests?.some(q=>q.questId===questId);if(active)serverSync.sendQuestComplete(questId);else serverSync.sendQuestAccept(questId);return;}if(dialogNpc)serverSync.sendInteraction(dialogNpc.id,action);};
 useEffect(()=>{const host=hostRef.current;if(!host)return;const runtime=new EuphoriaPresentationRuntime();runtimeRef.current=runtime;const renderer=new PixiIsoRenderer();let alive=true;const pressed=new Set<string>();let lastMoveAt=0;
 const applySnapshot=(snapshot:unknown)=>{const frame=bridgeServerSnapshot(snapshot);if(!frame)return false;snapshotRef.current=snapshot as IsoSnapshot;runtime.updateAuthoritativeEntities(frame.entities);if(frame.playerId)runtime.followEntity(frame.playerId);setLive(true);syncInteraction(runtime.interactionState());if(dialogNpc){const snap=snapshot as IsoSnapshot;if(snap.player)setDialogPlayer(snap.player);}return true;};
 const onSnapshot=(event:Event)=>{applySnapshot((event as CustomEvent).detail);};
 const onKeyDown=(event:KeyboardEvent)=>{if(event.code==='Escape'&&dialogNpc){setDialogNpc(null);event.preventDefault();return;}if(dialogNpc)return;if(event.repeat&&event.code==='KeyE')return;if(event.code==='KeyE'){if(interactionRef.current.inRange&&interact())event.preventDefault();return;}if(MOVE_KEYS[event.code]){pressed.add(event.code);event.preventDefault();}};
 const onKeyUp=(event:KeyboardEvent)=>{if(MOVE_KEYS[event.code])pressed.delete(event.code);};
 window.addEventListener('moria:authoritative-snapshot',onSnapshot as EventListener);window.addEventListener('keydown',onKeyDown);window.addEventListener('keyup',onKeyUp);
 void runtime.mount(renderer,host,{width:host.clientWidth||1280,height:host.clientHeight||720,devicePixelRatio:window.devicePixelRatio}).then(()=>{if(!alive)return;const initial=(window as Window & {__MORIA_AUTHORITATIVE_SNAPSHOT__?:unknown}).__MORIA_AUTHORITATIVE_SNAPSHOT__;if(!applySnapshot(initial)){runtime.updateAuthoritativeEntities(ELDORIA_ISO_FIXTURE);runtime.followEntity('preview-player');}runtime.zoom(1.1);syncInteraction(runtime.interactionState());});
 const uiTimer=window.setInterval(()=>{if(!alive)return;syncInteraction(runtime.interactionState());if(dialogNpc)return;if(!live&&!(window as Window & {__MORIA_AUTHORITATIVE_SNAPSHOT__?:unknown}).__MORIA_AUTHORITATIVE_SNAPSHOT__)return;const now=performance.now();if(now-lastMoveAt<90)return;let dx=0,dy=0;for(const code of pressed){const move=MOVE_KEYS[code];dx+=move.dx;dy+=move.dy;}if(dx||dy){serverSync.sendMove(Math.sign(dx),Math.sign(dy));lastMoveAt=now;}},50);
 const onResize=()=>runtime.resize({width:host.clientWidth||window.innerWidth,height:host.clientHeight||window.innerHeight,devicePixelRatio:window.devicePixelRatio});window.addEventListener('resize',onResize);return()=>{alive=false;window.clearInterval(uiTimer);window.removeEventListener('resize',onResize);window.removeEventListener('moria:authoritative-snapshot',onSnapshot as EventListener);window.removeEventListener('keydown',onKeyDown);window.removeEventListener('keyup',onKeyUp);runtime.destroy();runtimeRef.current=null;};},[live,dialogNpc]);
 const candidate=interaction.candidate;
 return <section style={{position:'relative',width:'100%',minHeight:'720px',overflow:'hidden',background:'#10151d'}}><div ref={hostRef} data-testid="iso-next-canvas" style={{position:'absolute',inset:0}}/><div style={{position:'absolute',left:20,top:20,padding:'10px 14px',borderRadius:12,background:'rgba(8,12,18,.72)',color:'#f4e8c8',fontFamily:'system-ui',pointerEvents:'none'}}><strong>Mor'ia ISO Next</strong><br/><small>{live?'Servidor autoritativo • LIVE · WASD para mover':'Eldoria • preview fixture'}</small></div>{candidate&&!dialogNpc&&<div data-testid="iso-interaction-prompt" style={{position:'absolute',left:'50%',bottom:34,transform:'translateX(-50%)',minWidth:260,padding:'12px 16px',border:'1px solid rgba(238,203,126,.42)',borderRadius:14,background:'rgba(8,12,18,.9)',boxShadow:'0 12px 36px rgba(0,0,0,.35)',color:'#f4e8c8',fontFamily:'system-ui',textAlign:'center'}}><div style={{fontSize:12,opacity:.72,letterSpacing:'.08em',textTransform:'uppercase'}}>{ROLE[candidate.visualId]??'Entidade'}</div><strong style={{display:'block',margin:'3px 0 8px',fontSize:15}}>{candidate.label}</strong><button type="button" disabled={!interaction.inRange} onClick={()=>interact()} style={{border:'1px solid rgba(238,203,126,.55)',borderRadius:9,padding:'7px 13px',background:'rgba(196,143,61,.18)',color:'#ffe4a5',cursor:interaction.inRange?'pointer':'not-allowed',opacity:interaction.inRange?1:.5}}>E · Interagir</button></div>}{dialogNpc&&dialogPlayer&&<DialogBox npc={dialogNpc} player={dialogPlayer} questCatalog={questCatalog} onAction={onDialogAction} onClose={()=>setDialogNpc(null)}/>}</section>;
}
