import { useEffect, useState } from 'react';
import { IsoGameplayPanel } from './IsoGameplayPanel';
import { IsoLegacySystemsDock } from './IsoLegacySystemsDock';
import { DraggableIsoWindow } from './DraggableIsoWindow';
import { IsoLegacyWindowRegistry, ISO_LEGACY_WINDOWS, type LegacyWindowId } from './IsoLegacyWindowRegistry';
import { dispatchIsoAction, selectIsoGameplaySnapshot, type IsoGameplaySnapshot } from './isoGameplayActions';

type Tab='quests'|'progress'|'world'|'social';
const EMPTY:IsoGameplaySnapshot={inventory:[],equipment:{},groundItems:[],activeQuests:[],tasks:[],talents:[],professions:[],reputation:{},mounts:[]};
const KEY_TO_WINDOW:Map<string,LegacyWindowId>=new Map(ISO_LEGACY_WINDOWS.map(([id,,key])=>[`Key${key}`,id]));
export function IsoSystemsOverlay(){
 const[state,setState]=useState<IsoGameplaySnapshot>(EMPTY);const[rawSnapshot,setRawSnapshot]=useState<any>({});const[showInventory,setShowInventory]=useState(false);const[showDock,setShowDock]=useState(false);const[open,setOpen]=useState<Set<LegacyWindowId>>(new Set());const[tab,setTab]=useState<Tab>('quests');const[targetId,setTargetId]=useState('');
 const toggle=(id:LegacyWindowId)=>setOpen(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next;});
 useEffect(()=>{const apply=(raw:any)=>{setRawSnapshot(raw||{});setState(selectIsoGameplaySnapshot(raw));const interaction=raw?.interaction;const hostile=interaction?.kind==='hostile'?interaction?.targetId:'';if(hostile)setTargetId(String(hostile));};const initial=(window as any).__MORIA_AUTHORITATIVE_SNAPSHOT__;if(initial)apply(initial);const onSnapshot=(e:Event)=>apply((e as CustomEvent).detail);const onKey=(e:KeyboardEvent)=>{if(e.code==='KeyI'){setShowInventory(v=>!v);e.preventDefault();return;}if(e.code==='KeyJ'){setShowDock(v=>!v);e.preventDefault();return;}const windowId=KEY_TO_WINDOW.get(e.code);if(windowId){toggle(windowId);e.preventDefault();return;}if(e.code==='Digit1'&&targetId){dispatchIsoAction({kind:'attack',targetId});e.preventDefault();}if(/^Digit[2-6]$/.test(e.code)){dispatchIsoAction({kind:'cast',spellIndex:Number(e.code.slice(-1))-2,targetId:targetId||undefined});e.preventDefault();}};window.addEventListener('moria:authoritative-snapshot',onSnapshot as EventListener);window.addEventListener('keydown',onKey);return()=>{window.removeEventListener('moria:authoritative-snapshot',onSnapshot as EventListener);window.removeEventListener('keydown',onKey);};},[targetId]);
 const button:React.CSSProperties={border:'1px solid rgba(238,203,126,.28)',background:'rgba(7,11,17,.9)',color:'#f4e8c8',borderRadius:9,padding:'8px 10px',boxShadow:'0 8px 24px rgba(0,0,0,.3)'};
 return <><div data-testid="iso-system-shortcuts" style={{position:'absolute',right:20,bottom:84,display:'flex',gap:6,zIndex:20,flexWrap:'wrap',maxWidth:'70vw',justifyContent:'flex-end'}}><button style={button} onClick={()=>setShowInventory(v=>!v)}>🎒 Inventário [I]</button><button style={button} onClick={()=>setShowDock(v=>!v)}>📜 Resumo [J]</button>{ISO_LEGACY_WINDOWS.slice(0,6).map(([id,title,key])=><button key={id} style={button} onClick={()=>toggle(id)}>{title} [{key}]</button>)}{targetId&&<button style={button} onClick={()=>dispatchIsoAction({kind:'attack',targetId})}>⚔️ Atacar [1]</button>}</div>{showInventory&&<DraggableIsoWindow id="inventory-equipment-loot" title="Inventário · Equipamento · Loot" initial={{x:Math.max(20,window.innerWidth-430),y:86}} width={390} onClose={()=>setShowInventory(false)}><IsoGameplayPanel state={state} onClose={()=>setShowInventory(false)}/></DraggableIsoWindow>}{showDock&&<DraggableIsoWindow id="legacy-systems" title="Sistemas do Personagem" initial={{x:20,y:86}} width={330} onClose={()=>setShowDock(false)}><IsoLegacySystemsDock state={state} tab={tab} onTab={setTab}/></DraggableIsoWindow>}<IsoLegacyWindowRegistry snapshot={rawSnapshot} open={open} onToggle={toggle}/></>;
}
