import { useEffect, useState } from 'react';
import { IsoGameplayPanel } from './IsoGameplayPanel';
import { IsoLegacySystemsDock } from './IsoLegacySystemsDock';
import { DraggableIsoWindow } from './DraggableIsoWindow';
import { dispatchIsoAction, selectIsoGameplaySnapshot, type IsoGameplaySnapshot } from './isoGameplayActions';

type Tab='quests'|'progress'|'world'|'social';
const EMPTY:IsoGameplaySnapshot={inventory:[],equipment:{},groundItems:[],activeQuests:[],tasks:[],talents:[],professions:[],reputation:{},mounts:[]};

export function IsoSystemsOverlay(){
 const[state,setState]=useState<IsoGameplaySnapshot>(EMPTY);const[showInventory,setShowInventory]=useState(false);const[showDock,setShowDock]=useState(false);const[tab,setTab]=useState<Tab>('quests');const[targetId,setTargetId]=useState('');
 useEffect(()=>{const apply=(raw:any)=>{setState(selectIsoGameplaySnapshot(raw));const interaction=raw?.interaction;const hostile=interaction?.kind==='hostile'?interaction?.targetId:'';if(hostile)setTargetId(String(hostile));};const initial=(window as any).__MORIA_AUTHORITATIVE_SNAPSHOT__;if(initial)apply(initial);const onSnapshot=(e:Event)=>apply((e as CustomEvent).detail);const onKey=(e:KeyboardEvent)=>{if(e.code==='KeyI'){setShowInventory(v=>!v);e.preventDefault();}if(e.code==='KeyJ'){setShowDock(v=>!v);e.preventDefault();}if(e.code==='Digit1'&&targetId){dispatchIsoAction({kind:'attack',targetId});e.preventDefault();}if(/^Digit[2-6]$/.test(e.code)){dispatchIsoAction({kind:'cast',spellIndex:Number(e.code.slice(-1))-2,targetId:targetId||undefined});e.preventDefault();}if(e.code==='KeyM'){dispatchIsoAction({kind:'mount'});e.preventDefault();}};window.addEventListener('moria:authoritative-snapshot',onSnapshot as EventListener);window.addEventListener('keydown',onKey);return()=>{window.removeEventListener('moria:authoritative-snapshot',onSnapshot as EventListener);window.removeEventListener('keydown',onKey);};},[targetId]);
 const button:React.CSSProperties={border:'1px solid rgba(238,203,126,.28)',background:'rgba(7,11,17,.9)',color:'#f4e8c8',borderRadius:9,padding:'8px 10px',boxShadow:'0 8px 24px rgba(0,0,0,.3)'};
 return <><div data-testid="iso-system-shortcuts" style={{position:'absolute',right:20,bottom:84,display:'flex',gap:6,zIndex:20}}><button style={button} onClick={()=>setShowInventory(v=>!v)}>🎒 Inventário [I]</button><button style={button} onClick={()=>setShowDock(v=>!v)}>📜 Sistemas [J]</button><button style={button} onClick={()=>dispatchIsoAction({kind:'mount'})}>🐎 Montaria [M]</button>{targetId&&<button style={button} onClick={()=>dispatchIsoAction({kind:'attack',targetId})}>⚔️ Atacar [1]</button>}</div>{showInventory&&<DraggableIsoWindow id="inventory-equipment-loot" title="Inventário · Equipamento · Loot" initial={{x:Math.max(20,window.innerWidth-430),y:86}} width={390} onClose={()=>setShowInventory(false)}><IsoGameplayPanel state={state} onClose={()=>setShowInventory(false)}/></DraggableIsoWindow>}{showDock&&<DraggableIsoWindow id="legacy-systems" title="Sistemas do Personagem" initial={{x:20,y:86}} width={330} onClose={()=>setShowDock(false)}><IsoLegacySystemsDock state={state} tab={tab} onTab={setTab}/></DraggableIsoWindow>}</>;
}
