import { useEffect, useState } from 'react';
import { IsoGameplayPanel } from './IsoGameplayPanel';
import { IsoLegacySystemsDock } from './IsoLegacySystemsDock';
import { DraggableIsoWindow } from './DraggableIsoWindow';
import { IsoLegacyWindowRegistry, ISO_LEGACY_WINDOWS, type LegacyWindowId } from './IsoLegacyWindowRegistry';
import { IsoAuthoritativeActionBar } from './IsoAuthoritativeActionBar';
import { IsoCombatPresentation } from './IsoCombatPresentation';
import { IsoAuthoritativeMiniMap } from './IsoAuthoritativeMiniMap';
import { dispatchIsoAction, selectIsoGameplaySnapshot, type IsoGameplaySnapshot } from './isoGameplayActions';

type Tab='quests'|'progress'|'world'|'social';type Preset='combat'|'exploration'|'social';type SavedLayout={positions:Record<string,{x:number;y:number}>;open:LegacyWindowId[];inventory:boolean;dock:boolean;minimap?:boolean};
const EMPTY:IsoGameplaySnapshot={inventory:[],equipment:{},groundItems:[],activeQuests:[],tasks:[],talents:[],professions:[],reputation:{},mounts:[]};
const KEY_TO_WINDOW:Map<string,LegacyWindowId>=new Map(ISO_LEGACY_WINDOWS.map(([id,,key])=>[`Key${key}`,id]));
const PRESETS:Record<Preset,LegacyWindowId[]>={combat:['character','spellbook','dps','bestiary'],exploration:['quests','map','crafting','mounts','events'],social:['social','mail','auction','housing','pets']};
export function IsoSystemsOverlay(){
 const[state,setState]=useState<IsoGameplaySnapshot>(EMPTY);const[rawSnapshot,setRawSnapshot]=useState<any>({});const[showInventory,setShowInventory]=useState(false);const[showDock,setShowDock]=useState(false);const[showMiniMap,setShowMiniMap]=useState(true);const[showLayouts,setShowLayouts]=useState(false);const[open,setOpen]=useState<Set<LegacyWindowId>>(new Set());const[tab,setTab]=useState<Tab>('quests');const[targetId,setTargetId]=useState('');const[savedSlots,setSavedSlots]=useState<boolean[]>(()=>[1,2,3].map(slot=>{try{return !!localStorage.getItem(`moria:iso-custom-layout:${slot}`)}catch{return false}}));const[notice,setNotice]=useState('');
 const toggle=(id:LegacyWindowId)=>setOpen(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next;});const flash=(text:string)=>{setNotice(text);window.setTimeout(()=>setNotice(''),1800);};
 const applyPreset=(preset:Preset)=>{setOpen(new Set(PRESETS[preset]));setShowInventory(preset==='exploration');setShowDock(preset==='social');setShowMiniMap(preset!=='social');setShowLayouts(false);window.dispatchEvent(new CustomEvent('moria:iso-layout-reset',{detail:{id:'*'}}));try{localStorage.setItem('moria:iso-layout-preset',preset)}catch{}};
 const resetLayout=()=>{window.dispatchEvent(new CustomEvent('moria:iso-layout-reset',{detail:{id:'*'}}));try{Object.keys(localStorage).filter(k=>k.startsWith('moria:iso-window:')).forEach(k=>localStorage.removeItem(k))}catch{}flash('Posições restauradas');};
 const saveLayout=(slot:number)=>{const positions:Record<string,{x:number;y:number}>={};const handler=(e:Event)=>{const d=(e as CustomEvent).detail;if(d?.id&&d?.pos)positions[d.id]=d.pos;};window.addEventListener('moria:iso-layout-position',handler as EventListener);window.dispatchEvent(new Event('moria:iso-layout-request'));window.removeEventListener('moria:iso-layout-position',handler as EventListener);const layout:SavedLayout={positions,open:[...open],inventory:showInventory,dock:showDock,minimap:showMiniMap};try{localStorage.setItem(`moria:iso-custom-layout:${slot}`,JSON.stringify(layout));setSavedSlots(v=>v.map((x,i)=>i===slot-1?true:x));flash(`Layout ${slot} salvo`)}catch{}};
 const loadLayout=(slot:number)=>{try{const raw=localStorage.getItem(`moria:iso-custom-layout:${slot}`);if(!raw){flash(`Slot ${slot} vazio`);return}const layout=JSON.parse(raw) as SavedLayout;setOpen(new Set(layout.open||[]));setShowInventory(!!layout.inventory);setShowDock(!!layout.dock);setShowMiniMap(layout.minimap!==false);setShowLayouts(false);requestAnimationFrame(()=>window.dispatchEvent(new CustomEvent('moria:iso-layout-apply',{detail:{positions:layout.positions||{}}})));flash(`Layout ${slot} carregado`)}catch{}};
 const autoOrganize=()=>{const ids=['authoritative-action-bar','combat-target-frame',...(showMiniMap?['authoritative-minimap']:[]),...Array.from(open).map(id=>`legacy-${id}`),...(showInventory?['inventory-equipment-loot']:[]),...(showDock?['legacy-systems']:[])];const positions:Record<string,{x:number;y:number}>={};const margin=16,gap=12,cardW=400,cardH=250;let x=margin,y=82;for(const id of ids){if(id==='authoritative-action-bar'){positions[id]={x:Math.max(margin,(window.innerWidth-760)/2),y:Math.max(82,window.innerHeight-160)};continue}if(id==='combat-target-frame'){positions[id]={x:Math.max(margin,(window.innerWidth-380)/2),y:82};continue}if(id==='authoritative-minimap'){positions[id]={x:Math.max(margin,window.innerWidth-276),y:82};continue}if(y+cardH>window.innerHeight-170){y=82;x+=cardW+gap}positions[id]={x:Math.min(x,Math.max(margin,window.innerWidth-cardW-margin)),y};y+=cardH+gap}window.dispatchEvent(new CustomEvent('moria:iso-layout-apply',{detail:{positions}}));flash('HUD organizada automaticamente');};
 useEffect(()=>{const apply=(raw:any)=>{setRawSnapshot(raw||{});setState(selectIsoGameplaySnapshot(raw));const interaction=raw?.interaction;const hostile=interaction?.kind==='hostile'?interaction?.targetId:'';setTargetId(hostile?String(hostile):'');};const initial=(window as any).__MORIA_AUTHORITATIVE_SNAPSHOT__;if(initial)apply(initial);const onSnapshot=(e:Event)=>apply((e as CustomEvent).detail);const onKey=(e:KeyboardEvent)=>{if(e.code==='KeyI'){setShowInventory(v=>!v);e.preventDefault();return;}if(e.code==='KeyJ'){setShowDock(v=>!v);e.preventDefault();return;}if(e.code==='KeyZ'){setShowMiniMap(v=>!v);e.preventDefault();return;}if(e.code==='Escape'){setShowLayouts(false);return;}const windowId=KEY_TO_WINDOW.get(e.code);if(windowId){toggle(windowId);e.preventDefault();return;}};window.addEventListener('moria:authoritative-snapshot',onSnapshot as EventListener);window.addEventListener('keydown',onKey);return()=>{window.removeEventListener('moria:authoritative-snapshot',onSnapshot as EventListener);window.removeEventListener('keydown',onKey);};},[]);
 const button:React.CSSProperties={border:'1px solid rgba(238,203,126,.28)',background:'rgba(7,11,17,.9)',color:'#f4e8c8',borderRadius:9,padding:'8px 10px',boxShadow:'0 8px 24px rgba(0,0,0,.3)'};
 return <><IsoAuthoritativeActionBar snapshot={rawSnapshot}/><IsoCombatPresentation snapshot={rawSnapshot}/>{showMiniMap&&<IsoAuthoritativeMiniMap snapshot={rawSnapshot}/>} {notice&&<div style={{position:'absolute',left:'50%',top:24,transform:'translateX(-50%)',zIndex:80,padding:'8px 14px',borderRadius:10,background:'rgba(7,11,17,.94)',border:'1px solid rgba(238,203,126,.35)',color:'#f4e8c8'}}>{notice}</div>}<div data-testid="iso-system-shortcuts" style={{position:'absolute',right:20,bottom:168,display:'flex',gap:6,zIndex:40,flexWrap:'wrap',maxWidth:'76vw',justifyContent:'flex-end'}}><button style={button} onClick={()=>setShowLayouts(v=>!v)}>▦ HUD</button><button style={button} onClick={()=>setShowMiniMap(v=>!v)}>🗺 Minimapa [Z]</button><button style={button} onClick={()=>setShowInventory(v=>!v)}>🎒 Inventário [I]</button><button style={button} onClick={()=>setShowDock(v=>!v)}>📜 Resumo [J]</button>{ISO_LEGACY_WINDOWS.slice(0,6).map(([id,title,key])=><button key={id} style={button} onClick={()=>toggle(id)}>{title} [{key}]</button>)}{targetId&&<button style={button} onClick={()=>dispatchIsoAction({kind:'attack',targetId})}>⚔️ Atacar alvo</button>}</div>{showLayouts&&<div style={{position:'absolute',right:20,bottom:216,zIndex:50,width:290,padding:10,borderRadius:12,border:'1px solid rgba(238,203,126,.3)',background:'rgba(7,11,17,.96)',color:'#f4e8c8',boxShadow:'0 18px 50px rgba(0,0,0,.55)'}}><b>Organização da HUD</b><div style={{fontSize:11,opacity:.65,margin:'3px 0 8px'}}>Encaixe, organize e salve sua própria interface.</div><div style={{display:'grid',gap:6}}><button onClick={()=>applyPreset('combat')}>⚔ Combate</button><button onClick={()=>applyPreset('exploration')}>🧭 Exploração</button><button onClick={()=>applyPreset('social')}>👥 Social & Economia</button><button onClick={autoOrganize}>▦ Organizar automaticamente</button>{[1,2,3].map(slot=><div key={slot} style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:5}}><button onClick={()=>saveLayout(slot)}>💾 Salvar {slot}</button><button disabled={!savedSlots[slot-1]} onClick={()=>loadLayout(slot)}>{savedSlots[slot-1]?'●':'○'} Carregar {slot}</button></div>)}<button onClick={resetLayout}>↺ Restaurar posições</button></div></div>}{showInventory&&<DraggableIsoWindow id="inventory-equipment-loot" title="Inventário · Equipamento · Loot" initial={{x:Math.max(20,window.innerWidth-430),y:86}} width={390} onClose={()=>setShowInventory(false)}><IsoGameplayPanel state={state} onClose={()=>setShowInventory(false)}/></DraggableIsoWindow>}{showDock&&<DraggableIsoWindow id="legacy-systems" title="Sistemas do Personagem" initial={{x:20,y:86}} width={330} onClose={()=>setShowDock(false)}><IsoLegacySystemsDock state={state} tab={tab} onTab={setTab}/></DraggableIsoWindow>}<IsoLegacyWindowRegistry snapshot={rawSnapshot} open={open} onToggle={toggle}/></>;
}
