import { Application, Container, Graphics } from 'pixi.js';
import type { IsoCameraState } from './camera';
import { ISO_LAYER_ORDER, type IsoSceneFrame, type IsoSceneNode } from './sceneModel';
import type { IsoRenderer, IsoViewport } from './rendererContract';
import { drawArcanePulse, drawEldoriaLivingWorld } from './livingWorldPass';
import { depthScale, resolveOcclusionAlpha } from './depthOcclusion';
import { deterministicMote, sampleEnvironmentMotion, type EnvironmentMotionSample } from './environmentMotion';
import { ISO_ASSET_MANIFEST } from './assetPipeline';
import { PixiIsoAssetRuntime } from './pixiAssetRuntime';
import { drawEuphoriaProcedural } from './euphoriaProceduralPass';
import { aggregateCombatJuice, sampleCombatJuice } from './combatJuice';

const TILE_W=96,TILE_H=48;
export class PixiIsoRenderer implements IsoRenderer{
 private app:Application|null=null;private world=new Container();private layers=new Map<string,Container>();private camera:IsoCameraState={x:0,y:0,zoom:1};private frame:Readonly<IsoSceneFrame>|null=null;private motion:EnvironmentMotionSample=sampleEnvironmentMotion(0);private elapsedMs=0;private assets=new PixiIsoAssetRuntime();private combatOffset={x:0,y:0,zoom:0};
 async mount(host:HTMLElement){const app=new Application();await app.init({resizeTo:host,antialias:true,background:'#091017',preference:'webgl'});host.replaceChildren(app.canvas);this.app=app;app.stage.addChild(this.world);for(const n of ISO_LAYER_ORDER){const l=new Container();l.label=`iso-${n}`;this.layers.set(n,l);this.world.addChild(l);}this.assets.warmManifest(ISO_ASSET_MANIFEST);app.ticker.add(t=>{this.elapsedMs+=t.deltaMS;this.motion=sampleEnvironmentMotion(this.elapsedMs);if(this.frame)this.paint(this.frame);});this.applyCamera();}
 resize(v:IsoViewport){this.app?.renderer.resize(v.width,v.height);this.applyCamera();} setCamera(c:Readonly<IsoCameraState>){this.camera={...c};this.applyCamera();}
 render(frame:Readonly<IsoSceneFrame>){this.frame=frame;this.paint(frame);} private paint(frame:Readonly<IsoSceneFrame>){const juice=aggregateCombatJuice(frame.entities);this.combatOffset={x:juice.shakeX,y:juice.shakeY,zoom:juice.zoomKick};this.applyCamera();for(const n of ISO_LAYER_ORDER){const l=this.layers.get(n);if(!l)continue;l.removeChildren().forEach(c=>c.destroy());if(n==='terrain')this.drawGround(l);if(n==='structures')this.drawStructures(l);if(n==='foreground'){this.drawForeground(l,frame.entities);drawEldoriaLivingWorld(l);}if(n==='lighting')this.drawLighting(l);if(n==='fx'){this.drawAtmosphere(l);drawArcanePulse(l);for(const e of frame.entities)this.drawCombatFx(l,e);}for(const node of frame[n])l.addChild(this.drawNode(node));}}
 destroy(){this.frame=null;this.assets.destroy();this.app?.destroy(true,{children:true});this.app=null;this.layers.clear();} private applyCamera(){if(!this.app)return;const z=Math.max(.5,this.camera.zoom+this.combatOffset.zoom);this.world.scale.set(z);this.world.position.set(this.app.renderer.width/2-this.camera.x*z+this.combatOffset.x,this.app.renderer.height/2-this.camera.y*z+this.combatOffset.y);} private iso(x:number,y:number){return{x:(x-y)*TILE_W/2,y:(x+y)*TILE_H/2};}
 private drawGround(l:Container){for(let x=0;x<18;x++)for(let y=0;y<18;y++){const p=this.iso(x,y),pl=x>=6&&x<=11&&y>=6&&y<=11,r=Math.abs(x-y)<=1||Math.abs(x+y-17)<=1,w=x>=14&&y<=5,e=x===0||y===0||x===17||y===17,f=w?0x1f536b:pl?0x70685a:r?0x78654e:(x+y)%2?0x315b3b:0x3d6b44,g=new Graphics().poly([0,-24,48,0,0,24,-48,0]).fill(f).stroke({width:e?2:1,color:w?0x4b8ca3:0x22382a,alpha:e?.7:.38});if(w){const wave=this.motion.water*5;g.poly([-30+wave,2,-10+wave,-6,15+wave,-1,32+wave,-8]).stroke({width:2,color:0x82c7d3,alpha:.4});g.poly([-25-wave,10,-3-wave,4,22-wave,9]).stroke({width:1,color:0xb2e0df,alpha:.22});}else if(!pl&&!r&&(x*3+y*5)%7===0){g.circle(-10,-2,2).fill({color:0x82a95d,alpha:.7});g.circle(7,5,1.5).fill({color:0xc9b55b,alpha:.6});}g.position.set(p.x,p.y);l.addChild(g);}}
 private drawStructures(l:Container){const bs=[{x:4,y:8,w:104,h:78,roof:0x8d3442,trim:0xd7a35b},{x:8,y:4,w:120,h:92,roof:0x4b5278,trim:0xb7c4d2},{x:12,y:8,w:112,h:84,roof:0x815039,trim:0xe0b56c},{x:8,y:13,w:136,h:96,roof:0x5f365d,trim:0xd5a5c8}];for(const b of bs){const p=this.iso(b.x,b.y),g=new Graphics();g.ellipse(0,22,b.w*.52,20).fill({color:0,alpha:.28});g.poly([-b.w/2,-8,0,18,0,b.h-22,-b.w/2,b.h-48]).fill(0x655849);g.poly([b.w/2,-8,0,18,0,b.h-22,b.w/2,b.h-48]).fill(0x443d3b);g.poly([-b.w/2-16,-10,0,-54,b.w/2+16,-10,0,28]).fill(b.roof).stroke({width:4,color:0x241d25});g.poly([-b.w/2-8,-9,0,-44,b.w/2+8,-9]).stroke({width:3,color:b.trim,alpha:.55});g.roundRect(-10,b.h-56,20,32,5).fill(0x211918);g.position.set(p.x,p.y-b.h+38);l.addChild(g);}const p=this.iso(8,8),f=new Graphics().ellipse(0,9,52,24).fill(0x4c575d).ellipse(0,3,41,17).fill(0x2c7890).ellipse(0,1,32,11).fill({color:0x75c1cc,alpha:.5}).rect(-6,-39,12,44).fill(0x727e83).circle(0,-43,10).fill(0x9aa5a7);f.position.set(p.x,p.y);l.addChild(f);}
 private drawForeground(l:Container,entities:readonly IsoSceneNode[]){for(const[x,y,s]of[[3,5,1],[5,13,1.15],[12,4,1.1],[14,12,1.25],[2,11,.82],[15,8,.9]]as const){const p=this.iso(x,y),g=new Graphics(),sway=this.motion.foliage*4*s;g.ellipse(0,13,31*s,11*s).fill({color:0,alpha:.24});g.poly([-6*s,12*s,-4*s+sway*.2,-37*s,7*s+sway*.2,-34*s,6*s,12*s]).fill(0x513624);g.circle(-17*s+sway,-43*s,25*s).fill(0x244b31);g.circle(15*s+sway*.75,-49*s,29*s).fill(0x32653c);g.circle(sway*.55,-70*s,27*s).fill(0x43804a);const nearby=entities.some(e=>Math.abs(e.x-p.x)<58*s&&e.y>p.y-75*s&&e.y<p.y+30*s);g.alpha=nearby?.43:1;g.position.set(p.x,p.y);l.addChild(g);}}
 private drawLighting(l:Container){for(const[x,y]of[[6,7],[9,6],[10,10],[7,11],[4,8],[12,8]]as const){const p=this.iso(x,y),a=this.motion.lantern,g=new Graphics().circle(0,0,52).fill({color:0xf4a94f,alpha:.04*a}).circle(0,0,26).fill({color:0xffbd5d,alpha:.065*a}).circle(0,0,11).fill({color:0xffd47b,alpha:.16*a}).circle(0,0,3).fill({color:0xffe4a3,alpha:Math.min(1,a)});g.position.set(p.x,p.y-25);l.addChild(g);}}
 private drawAtmosphere(l:Container){const origins=[[5,6,-52],[7,8,-75],[9,5,-61],[11,9,-88],[6,12,-66],[13,7,-48],[3,10,-57]]as const;origins.forEach(([x,y,z],i)=>{const p=this.iso(x,y),m=deterministicMote(i,this.motion.motes),g=new Graphics().circle(0,0,5).fill({color:0xffd77d,alpha:.035*m.alpha}).circle(0,0,1.5).fill({color:0xffe5a8,alpha:m.alpha});g.position.set(p.x+m.x,p.y+z+m.y);l.addChild(g);});}
 private drawCombatFx(l:Container,n:IsoSceneNode){const cue=n.combatCue??'none',p=Math.max(0,Math.min(1,n.combatPhase??0));if(cue==='none')return;const juice=sampleCombatJuice(n),g=new Graphics(),left=n.facing==='nw'||n.facing==='sw',d=left?-1:1;if(cue==='windup'){g.ellipse(0,15,30+18*p,12+7*p).stroke({width:3,color:0xf3c568,alpha:.7});g.circle(0,-18,8+10*p).fill({color:0xffd97b,alpha:.08+.12*p});}if(cue==='attack'){const reach=30+34*p;g.moveTo(7*d,-18).quadraticCurveTo(reach*.55*d,-42,reach*d,-5).stroke({width:8+juice.trail*5,color:0xffe7a3,alpha:.18+.18*juice.trail});g.moveTo(8*d,-18).quadraticCurveTo(reach*.55*d,-40,reach*d,-5).stroke({width:3,color:0xffffff,alpha:.82});}if(cue==='hit'){g.circle(0,-8,12+24*p).fill({color:0xffe6a3,alpha:.22*(1-p)+juice.flash*.18});for(let i=0;i<7;i++){const a=i*Math.PI*2/7,r=12+32*p;g.moveTo(Math.cos(a)*8,-8+Math.sin(a)*8).lineTo(Math.cos(a)*r,-8+Math.sin(a)*r).stroke({width:2+juice.flash,color:i%2?0xff9a57:0xffe1a0,alpha:.85*(1-p)});}}if(cue==='cast'){g.circle(0,-20,16+18*p).stroke({width:4+juice.trail*2,color:0x77d9ff,alpha:.7});g.circle(0,-20,7+9*p).fill({color:0xaeeaff,alpha:.3+juice.flash*.2});for(let i=0;i<4;i++){const a=p*Math.PI*2+i*Math.PI/2;g.circle(Math.cos(a)*(18+8*p),-20+Math.sin(a)*(10+5*p),3).fill(0xb8f0ff);}}g.position.set(n.x,n.y);l.addChild(g);}
 private drawNode(n:IsoSceneNode){if(n.layer==='entities'){const sprite=this.assets.createEntitySprite(n);if(sprite){sprite.position.set(n.x,n.y);sprite.alpha=resolveOcclusionAlpha(n);const s=depthScale(n.depth);sprite.scale.set(s);return sprite;}}const g=new Graphics();if(n.layer==='entities'){if(n.visualId==='shadow-wolf')this.drawWolf(g,n);else if(n.visualId==='hero-v1')drawEuphoriaProcedural(g,n);else{g.ellipse(0,17,21,9).fill({color:0,alpha:.3});g.circle(0,-22,12).fill(0xa7a7a2);g.poly([-12,-7,12,-7,10,24,-10,24]).fill(0x596774);}}else g.circle(0,0,8).fill(0xc79b4a);g.position.set(n.x,n.y);g.alpha=resolveOcclusionAlpha(n);const s=depthScale(n.depth);g.scale.set(s);return g;}
 private drawWolf(g:Graphics,n:IsoSceneNode){const walk=n.motion==='walk',ph=(n.animationPhase??0)*Math.PI*2,s=walk?Math.sin(ph):0,left=n.facing==='nw'||n.facing==='sw',d=left?-1:1,hit=n.combatCue==='hit',recoil=hit?8*(1-(n.combatPhase??0))*-d:0;g.ellipse(recoil,12,31,9).fill({color:0,alpha:.36});g.poly([(-23*d)+recoil,0,(-12*d)+recoil,-13,(8*d)+recoil,-15,(23*d)+recoil,-7,(27*d)+recoil,4,(8*d)+recoil,8,(-11*d)+recoil,10]).fill(hit?0x6b4650:0x303541).stroke({width:2,color:0x171b25});g.poly([(14*d)+recoil,-12,(29*d)+recoil,-22,(27*d)+recoil,-5]).fill(0x353b49);g.circle((21*d)+recoil,-14,2.7).fill(0xe94d62);g.poly([(-13+s*4)*d+recoil,7,(-10+s*5)*d+recoil,20,-5*d+recoil,20,-5*d+recoil,7]).fill(0x202631);g.poly([(8-s*4)*d+recoil,7,(11-s*5)*d+recoil,20,16*d+recoil,20,14*d+recoil,5]).fill(0x202631);}
}
