import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { ContentDB } from '../engine/ContentDB.mjs';
import { CONTENT_STUDIO_SCHEMAS, validateStudioRecord } from '../engine/ContentStudio.mjs';
import { TibiaTaskEngine } from '../engine/TibiaTaskEngine.mjs';
import { AppearanceSystem } from '../engine/AppearanceSystem.mjs';
import { MountSystem } from '../engine/MountSystem.mjs';
import { HousingSystem } from '../engine/HousingSystem.mjs';

function temp(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'moria-92-'));return{dir,file:path.join(dir,'content.json'),housing:path.join(dir,'housing.json')}};
function player(name='Alpha Tester'){return{name,level:40,gold:100000,bankGold:50000,mapId:'eldoria',x:42,y:43,mounted:false};}

test('9.2 content migration seeds admin-editable alpha life catalogs',()=>{const t=temp();try{const db=new ContentDB(t.file);assert.equal(db.data.version,3);for(const type of ['taskQuests','houses','housingDecor','outfits','mounts']){assert.ok(db.get(type).length>=10,type);assert.ok(CONTENT_STUDIO_SCHEMAS[type],type);for(const record of db.get(type))assert.equal(validateStudioRecord(type,record),null,`${type}:${record.id}`);}assert.ok(db.get('npcs').some(n=>n.role==='stablemaster'));assert.ok(db.get('npcs').some(n=>n.role==='outfitter'));assert.ok(db.get('npcs').some(n=>n.role==='taskmaster'));}finally{fs.rmSync(t.dir,{recursive:true,force:true});}});

test('Tibia task engine tracks three persistent tasks, points, rank and repeat limits',()=>{const t=temp();try{const db=new ContentDB(t.file),engine=new TibiaTaskEngine(),p=player();engine.initializePlayer(p,db);const near=id=>id==='task_master_eldoria';assert.equal(engine.accept(p,'task_rat_catcher',db,near).ok,true);assert.equal(engine.accept(p,'task_snake_charmer',db,near).ok,true);p.mapId='frostpeak';p.x=64;p.y=42;assert.equal(engine.accept(p,'task_wolf_hunter',db,id=>id==='task_master_frostpeak').ok,true);assert.equal(engine.accept(p,'task_bear_tracker',db,()=>true).ok,false);p.mapId='eldoria';for(let i=0;i<25;i++)engine.onMonsterKill(p,{name:'Rat',contentSourceId:'rat'},db);const snap=engine.snapshot(p,db);assert.equal(snap.active.find(x=>x.id==='task_rat_catcher').ready,true);const claimed=engine.claim(p,'task_rat_catcher',db,near);assert.equal(claimed.ok,true);assert.equal(claimed.reward.points,2);assert.equal(engine.exportState(p,db).points,2);}finally{fs.rmSync(t.dir,{recursive:true,force:true});}});

test('appearance ownership, colors and addons are authoritative and bounded',()=>{const t=temp();try{const db=new ContentDB(t.file),sys=new AppearanceSystem(),p=player();sys.initializePlayer(p,db);assert.ok(sys.snapshot(p,db).ownedOutfits.includes('citizen'));assert.equal(sys.handle(p,{action:'select',outfitId:'void_walker'},db).ok,false);const bought=sys.handle(p,{action:'buy',outfitId:'knight_regalia'},db);assert.equal(bought.ok,true);assert.equal(sys.handle(p,{action:'colors',colors:{primary:'#112233',head:'#d7a06b'}},db).ok,true);assert.equal(sys.handle(p,{action:'buy_addon',outfitId:'knight_regalia',addon:1},db).ok,true);const pub=sys.publicAppearance(p,db);assert.equal(pub.outfit.id,'knight_regalia');assert.equal(pub.colors.primary,'#112233');assert.equal(pub.addonMask&1,1);}finally{fs.rmSync(t.dir,{recursive:true,force:true});}});

test('mount system requires ownership and applies selected authoritative speed bonus',()=>{const t=temp();try{const db=new ContentDB(t.file),sys=new MountSystem(),p=player();sys.initializePlayer(p,db);assert.equal(sys.handle(p,{action:'toggle'},db).ok,false);assert.equal(sys.handle(p,{action:'buy',mountId:'horse'},db).ok,true);assert.equal(sys.handle(p,{action:'toggle'},db).ok,true);assert.equal(p.mounted,true);assert.equal(p.mountId,'horse');assert.equal(sys.speedBonus(p,db),20);assert.equal(sys.handle(p,{action:'select',mountId:'nightmare'},db).ok,false);assert.equal(sys.handle(p,{action:'toggle'},db).mounted,false);}finally{fs.rmSync(t.dir,{recursive:true,force:true});}});

test('housing ownership is global, access-controlled, rentable, decorated and persistent',()=>{const t=temp();try{const db=new ContentDB(t.file),sys=new HousingSystem(db,t.housing),owner=player('Owner'),guest=player('Guest');const def=db.get('houses').find(h=>h.id==='house_oakhearth');owner.x=def.entranceX;owner.y=def.entranceY;assert.equal(sys.buy(owner,def.id,db).ok,true);assert.equal(sys.canStep(guest,def.mapId,def.x,def.y,db),false);assert.equal(sys.guest(owner,def.id,'Guest',true).ok,true);assert.equal(sys.canStep(guest,def.mapId,def.x,def.y,db),true);owner.x=def.x;owner.y=def.y;assert.equal(sys.decorate(owner,{action:'decor_add',houseId:def.id,decorId:'decor_table',x:def.x+1,y:def.y+1},db).ok,true);assert.equal(sys.payRent(owner,def.id,db).ok,true);const reload=new HousingSystem(db,t.housing);assert.equal(reload.record(def.id).ownerName,'Owner');assert.equal(reload.record(def.id).decor.length,1);}finally{fs.rmSync(t.dir,{recursive:true,force:true});}});
