import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import { GRAND_STORMWATCH_MAP, GRAND_CAPITAL_SCHEMA_VERSION, migrateGrandStormwatchData } from '../engine/GrandStormwatch.mjs';
import { MAP_CONFIG, URBAN_PLANS, WorldManager } from '../engine/World.mjs';
import { ContentDB } from '../engine/ContentDB.mjs';
import { getContentStudioSchema, validateStudioRecord } from '../engine/ContentStudio.mjs';
const clone=value=>JSON.parse(JSON.stringify(value));
function legacyData(){return{maps:[
{id:'stormwatch_isle',width:80,height:80,spawnX:40,spawnY:22,townX:40,townY:22,townRange:8,levelRequired:44,cityStyle:'storm',portals:[{x:40,y:8,targetMap:'emberhold',targetX:40,targetY:68},{x:8,y:40,targetMap:'crystal_deep',targetX:70,targetY:40},{x:70,y:70,targetMap:'nightfall_citadel',targetX:10,targetY:10}]},
{id:'emberhold',portals:[{x:80,y:141,targetMap:'stormwatch_isle',targetX:40,targetY:10}]},{id:'crystal_deep',portals:[{x:141,y:84,targetMap:'stormwatch_isle',targetX:10,targetY:40}]},{id:'nightfall_citadel',portals:[{x:8,y:8,targetMap:'stormwatch_isle',targetX:68,targetY:68}]},],npcs:[{id:'quest_stormwatch_isle',mapId:'stormwatch_isle',posX:38,posY:22},{id:'merchant_stormwatch_isle',mapId:'stormwatch_isle',posX:42,posY:22},{id:'warden_stormwatch_isle',mapId:'stormwatch_isle',posX:40,posY:24}],monsters:[{id:'stormwatch_isle_gale_harpy',mapId:'stormwatch_isle',posX:18,posY:27},{id:'stormwatch_isle_storm_hound',mapId:'stormwatch_isle',posX:26,posY:34},{id:'stormwatch_isle_sea_raider',mapId:'stormwatch_isle',posX:34,posY:41},{id:'stormwatch_isle_thunder_elemental',mapId:'stormwatch_isle',posX:42,posY:48},{id:'stormwatch_isle_tempest_champion',mapId:'stormwatch_isle',posX:50,posY:55},{id:'stormwatch_isle_maelstrom_drake',mapId:'stormwatch_isle',posX:58,posY:20}],nodes:[{id:'node_stormwatch',mapId:'stormwatch_isle',x:40,y:22}]};}

test('9.43A Grand Stormwatch Isle is a 160x160 tempest-archipelago capital',()=>{assert.equal(GRAND_CAPITAL_SCHEMA_VERSION,9);assert.equal(GRAND_STORMWATCH_MAP.width,160);assert.equal(GRAND_STORMWATCH_MAP.height,160);assert.equal(GRAND_STORMWATCH_MAP.settlementClass,'capital');assert.equal(GRAND_STORMWATCH_MAP.urbanPlan,'tempest-archipelago');assert.equal(GRAND_STORMWATCH_MAP.levelRequired,44);assert.equal(GRAND_STORMWATCH_MAP.districts.length,12);assert.equal(GRAND_STORMWATCH_MAP.landmarks.length,42);assert.ok(GRAND_STORMWATCH_MAP.props.length>=60);assert.equal(MAP_CONFIG.stormwatch_isle.width,160);assert.ok(URBAN_PLANS.has('tempest-archipelago'));});

test('9.43A archipelago topology creates dominant sea rocky islands and real storm causeways',()=>{const map=new WorldManager().getMap('stormwatch_isle');let water=0,bridges=0,rocks=0,snow=0,paths=0;for(let y=14;y<=145;y++)for(let x=14;x<=145;x++){const t=map.tiles[y][x].type;if(t==='water')water++;else if(t==='bridge')bridges++;else if(t==='rock')rocks++;else if(t==='snow')snow++;else if(t==='path')paths++;}assert.ok(water>8000,`water=${water}`);assert.ok(bridges>180,`bridges=${bridges}`);assert.ok(rocks>1600,`rocks=${rocks}`);assert.ok(snow>2200,`snow=${snow}`);assert.ok(paths>700,`paths=${paths}`);for(const [x,y]of [[80,14],[14,82],[145,82],[145,140]]){assert.equal(map.tiles[y][x].walkable,true);}assert.equal(map.tiles[82][54].type,'bridge');assert.equal(map.tiles[16][16].type,'water');});

test('9.43A exact legacy migration moves Stormwatch defaults and all three inbound routes',()=>{const data=legacyData();assert.equal(migrateGrandStormwatchData(data),true);const map=data.maps[0];assert.deepEqual([map.width,map.height,map.spawnX,map.spawnY,map.townX,map.townY],[160,160,80,122,80,80]);assert.equal(map.urbanPlan,'tempest-archipelago');assert.deepEqual([data.maps[1].portals[0].targetX,data.maps[1].portals[0].targetY],[80,18]);assert.deepEqual([data.maps[2].portals[0].targetX,data.maps[2].portals[0].targetY],[18,82]);assert.deepEqual([data.maps[3].portals[0].targetX,data.maps[3].portals[0].targetY],[140,136]);assert.deepEqual([data.npcs[0].posX,data.npcs[0].posY],[80,96]);assert.deepEqual([data.monsters[5].posX,data.monsters[5].posY],[112,150]);assert.deepEqual([data.nodes[0].x,data.nodes[0].y],[80,70]);const snap=JSON.stringify(data);assert.equal(migrateGrandStormwatchData(data),false);assert.equal(JSON.stringify(data),snap);});

test('9.43A administrator Stormwatch geometry blocks collateral migration',()=>{const data=legacyData();data.maps[0].width=120;data.maps[0].height=120;data.maps[0].spawnX=55;data.maps[0].spawnY=56;data.maps[0].landmarks=[{id:'admin'}];const before=JSON.stringify(data);assert.equal(migrateGrandStormwatchData(data),false);assert.equal(JSON.stringify(data),before);});

test('9.43A fresh ContentDB converges schema 9 and Stormwatch coordinates',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'moria-943-')),file=path.join(dir,'content.json');try{const db=new ContentDB(file),data=db.getAllContent();assert.equal(data.grandCapitalVersion,9);const map=data.maps.find(e=>e.id==='stormwatch_isle');assert.deepEqual([map.width,map.height,map.urbanPlan,map.levelRequired],[160,160,'tempest-archipelago',44]);const npc=data.npcs.find(e=>e.id==='quest_stormwatch_isle');const node=data.nodes.find(e=>e.id==='node_stormwatch');assert.deepEqual([npc.posX,npc.posY],[80,96]);assert.deepEqual([node.x,node.y],[80,70]);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('9.43A client server and Studio share tempest-archipelago vocabulary',()=>{const server=fs.readFileSync(new URL('../engine/World.mjs',import.meta.url),'utf8'),client=fs.readFileSync(new URL('../../src/game/maps.ts',import.meta.url),'utf8');for(const marker of ['nearStormCauseway','tempestArchipelagoTile','stormIslands']){assert.ok(server.includes(marker));assert.ok(client.includes(marker));}const fake={get(type){return type==='maps'?[clone(GRAND_STORMWATCH_MAP)]:[];}};const schema=getContentStudioSchema('maps',fake);assert.ok(schema.options.urbanPlans.includes('tempest-archipelago'));assert.equal(validateStudioRecord('maps',clone(GRAND_STORMWATCH_MAP),fake),null);});

test('9.43A eight capital algorithms remain explicitly distinct',()=>{const world=new WorldManager();for(const [id,plan]of [['eldoria','royal-grid'],['sunreach_coast','harbor-crescent'],['ironwood','forest-rings'],['frostpeak','terraced-bastion'],['shadowfen','marsh-wards'],['emberhold','caldera-radials'],['crystal_deep','geode-chambers'],['stormwatch_isle','tempest-archipelago']])assert.equal(world.getMap(id).urbanPlan,plan);});
