import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { GRAND_CRYSTAL_DEEP_MAP, GRAND_CAPITAL_SCHEMA_VERSION, migrateGrandCrystalDeepData } from '../engine/GrandCrystalDeep.mjs';
import { MAP_CONFIG, URBAN_PLANS, WorldManager } from '../engine/World.mjs';
import { ContentDB } from '../engine/ContentDB.mjs';
import { getContentStudioSchema, validateStudioRecord } from '../engine/ContentStudio.mjs';
const clone=value=>JSON.parse(JSON.stringify(value));
function legacyData(){return{maps:[
{id:'crystal_deep',width:80,height:80,spawnX:40,spawnY:60,townX:40,townY:60,townRange:8,levelRequired:36,cityStyle:'crystal',portals:[{x:40,y:75,targetMap:'frostpeak',targetX:40,targetY:12},{x:8,y:40,targetMap:'shadowfen',targetX:68,targetY:40},{x:72,y:40,targetMap:'stormwatch_isle',targetX:10,targetY:40}]},
{id:'frostpeak',portals:[{x:80,y:18,targetMap:'crystal_deep',targetX:40,targetY:70}]},{id:'shadowfen',portals:[{x:141,y:82,targetMap:'crystal_deep',targetX:10,targetY:40}]},{id:'stormwatch_isle',portals:[{x:8,y:40,targetMap:'crystal_deep',targetX:70,targetY:40}]},],npcs:[{id:'quest_crystal_deep',mapId:'crystal_deep',posX:38,posY:60},{id:'merchant_crystal_deep',mapId:'crystal_deep',posX:42,posY:60},{id:'warden_crystal_deep',mapId:'crystal_deep',posX:40,posY:62}],monsters:[{id:'crystal_deep_shardling',mapId:'crystal_deep',posX:18,posY:20},{id:'crystal_deep_cave_lurker',mapId:'crystal_deep',posX:26,posY:27},{id:'crystal_deep_resonant_bat',mapId:'crystal_deep',posX:34,posY:34},{id:'crystal_deep_crystal_sentinel',mapId:'crystal_deep',posX:42,posY:41},{id:'crystal_deep_prismatic_horror',mapId:'crystal_deep',posX:50,posY:48},{id:'crystal_deep_the_faceted_one',mapId:'crystal_deep',posX:58,posY:55}],nodes:[{id:'node_crystaldeep',mapId:'crystal_deep',x:40,y:60}]};}

test('9.42A Grand Crystal Deep is a 160x160 geode-chambers capital',()=>{assert.equal(GRAND_CAPITAL_SCHEMA_VERSION,8);assert.equal(GRAND_CRYSTAL_DEEP_MAP.width,160);assert.equal(GRAND_CRYSTAL_DEEP_MAP.height,160);assert.equal(GRAND_CRYSTAL_DEEP_MAP.settlementClass,'capital');assert.equal(GRAND_CRYSTAL_DEEP_MAP.urbanPlan,'geode-chambers');assert.equal(GRAND_CRYSTAL_DEEP_MAP.levelRequired,36);assert.equal(GRAND_CRYSTAL_DEEP_MAP.districts.length,12);assert.equal(GRAND_CRYSTAL_DEEP_MAP.landmarks.length,42);assert.ok(GRAND_CRYSTAL_DEEP_MAP.props.length>=70);assert.equal(MAP_CONFIG.crystal_deep.width,160);assert.ok(URBAN_PLANS.has('geode-chambers'));});

test('9.42A cave topology is mostly bedrock with real chambers galleries and four shaft accesses',()=>{const map=new WorldManager().getMap('crystal_deep');let walls=0,floors=0,paths=0;for(let y=18;y<=141;y++)for(let x=18;x<=141;x++){const t=map.tiles[y][x].type;if(t==='wall')walls++;else if(t==='floor')floors++;else if(t==='path')paths++;}assert.ok(walls>11000,`walls=${walls}`);assert.ok(floors>2200,`floors=${floors}`);assert.ok(paths>1000,`paths=${paths}`);for(const [x,y]of [[80,18],[80,141],[18,84],[141,84]]){assert.equal(map.tiles[y][x].type,'path');assert.equal(map.tiles[y][x].walkable,true);}assert.equal(map.tiles[60][48].type,'floor');assert.equal(map.tiles[104][62].type,'path');assert.equal(map.tiles[20][20].type,'wall');});

test('9.42A exact legacy migration moves Crystal Deep defaults and all three inbound routes',()=>{const data=legacyData();assert.equal(migrateGrandCrystalDeepData(data),true);const map=data.maps[0];assert.deepEqual([map.width,map.height,map.spawnX,map.spawnY,map.townX,map.townY],[160,160,80,124,80,80]);assert.equal(map.urbanPlan,'geode-chambers');assert.deepEqual([data.maps[1].portals[0].targetX,data.maps[1].portals[0].targetY],[80,138]);assert.deepEqual([data.maps[2].portals[0].targetX,data.maps[2].portals[0].targetY],[22,84]);assert.deepEqual([data.maps[3].portals[0].targetX,data.maps[3].portals[0].targetY],[138,84]);assert.deepEqual([data.npcs[0].posX,data.npcs[0].posY],[80,96]);assert.deepEqual([data.monsters[5].posX,data.monsters[5].posY],[112,150]);assert.deepEqual([data.nodes[0].x,data.nodes[0].y],[62,104]);const snap=JSON.stringify(data);assert.equal(migrateGrandCrystalDeepData(data),false);assert.equal(JSON.stringify(data),snap);});

test('9.42A administrator Crystal Deep geometry blocks collateral migration',()=>{const data=legacyData();data.maps[0].width=120;data.maps[0].height=120;data.maps[0].spawnX=55;data.maps[0].spawnY=56;data.maps[0].landmarks=[{id:'admin'}];const before=JSON.stringify(data);assert.equal(migrateGrandCrystalDeepData(data),false);assert.equal(JSON.stringify(data),before);});

test('9.42A fresh ContentDB converges schema 8 and Crystal Deep coordinates',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'moria-942-')),file=path.join(dir,'content.json');try{const db=new ContentDB(file),data=db.getAllContent();assert.equal(data.grandCapitalVersion,8);const map=data.maps.find(e=>e.id==='crystal_deep');assert.deepEqual([map.width,map.height,map.urbanPlan,map.levelRequired],[160,160,'geode-chambers',36]);const npc=data.npcs.find(e=>e.id==='quest_crystal_deep');const node=data.nodes.find(e=>e.id==='node_crystaldeep');assert.deepEqual([npc.posX,npc.posY],[80,96]);assert.deepEqual([node.x,node.y],[62,104]);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('9.42A client server renderer minimap and Studio share crystal vocabulary',()=>{const server=fs.readFileSync(new URL('../engine/World.mjs',import.meta.url),'utf8'),client=fs.readFileSync(new URL('../../src/game/maps.ts',import.meta.url),'utf8'),render=fs.readFileSync(new URL('../../src/game/render.ts',import.meta.url),'utf8'),mini=fs.readFileSync(new URL('../../src/components/WorldMiniMap.tsx',import.meta.url),'utf8');for(const marker of ['nearGeodeGallery','geodeChambersTile','chambers','galleries']){assert.ok(server.includes(marker));assert.ok(client.includes(marker));}assert.match(render,/wall_crystal_/);assert.match(render,/floor_crystal_/);assert.match(render,/path_crystal_/);assert.match(mini,/CRYSTAL_TILE_COLORS/);const fake={get(type){return type==='maps'?[clone(GRAND_CRYSTAL_DEEP_MAP)]:[];}};const schema=getContentStudioSchema('maps',fake);assert.ok(schema.options.urbanPlans.includes('geode-chambers'));assert.equal(validateStudioRecord('maps',clone(GRAND_CRYSTAL_DEEP_MAP),fake),null);});

test('9.42A seven capital algorithms remain explicitly distinct',()=>{const world=new WorldManager();for(const [id,plan]of [['eldoria','royal-grid'],['sunreach_coast','harbor-crescent'],['ironwood','forest-rings'],['frostpeak','terraced-bastion'],['shadowfen','marsh-wards'],['emberhold','caldera-radials'],['crystal_deep','geode-chambers']])assert.equal(world.getMap(id).urbanPlan,plan);});
