import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'fs';
import { LivingRealmDomain, NODE_STAGES, CRAFT_GRADES } from '../engine/LivingRealmDomain.mjs';
import { LIVING_REALM_CONTENT } from '../engine/LivingRealmContent.mjs';
import { freshGlobalState, freshPlayerState, normalizeGlobalState, normalizePlayerState } from '../engine/OfficialStateSchema.mjs';
import { OFFICIAL_ACTION_NAMES } from '../engine/OfficialActionRegistry.mjs';
import { CONTENT_STUDIO_SCHEMAS, validateStudioRecord } from '../engine/ContentStudio.mjs';

function host(){const h={global:freshGlobalState(),livingRealmContent:structuredClone(LIVING_REALM_CONTENT),ensurePlayer(p){p.official??=freshPlayerState();return p.official;}};return h}
function player(mapId='eldoria',level=30){return {name:'Tester',level,mapId,x:40,y:40,gold:100000,attack:60,inventory:[],official:freshPlayerState()}}
const add=(p,name,q=1,type='material')=>p.inventory.push({id:`i_${p.inventory.length}`,name,type,quantity:q});

test('9.11 living nodes advance through server-owned XP stages',()=>{const d=new LivingRealmDomain(),h=host(),p=player();const n=LIVING_REALM_CONTENT.nodes[0];let r=d.contributeNode(h,p,n.id,500,'quest',1000);assert.equal(r.ok,true);assert.ok(r.node.stage>=2);assert.equal(NODE_STAGES[r.node.stage],r.node.stageName)});
test('9.12 factions are chosen during gameplay and defection is consequential',()=>{const d=new LivingRealmDomain(),h=host(),p=player();let r=d.joinFaction(h,p,'crown_eldoria',100);assert.equal(r.ok,true);assert.equal(p.official.livingRealm.faction.id,'crown_eldoria');r=d.defectFaction(h,p,'free_league',200);assert.equal(r.ok,true);assert.equal(p.official.livingRealm.faction.reputation,-100);assert.ok(p.official.livingRealm.faction.defectionUntil>200);assert.equal(d.defectFaction(h,p,'red_pact',201).ok,false)});
test('9.13 node war declares, opens siege and can be claimed by attackers',()=>{const d=new LivingRealmDomain(),h=host(),p=player('eldoria',50);d.joinFaction(h,p,'red_pact',1);const nodeId='node_eldoria';d.contributeNode(h,p,nodeId,1000,'activity',2);h.global.livingRealm.nodes[nodeId].controllerFactionId='crown_eldoria';const war=d.declareNodeWar(h,p,nodeId,1000);assert.equal(war.ok,true);d.tick(h,war.node.siegeStartsAt);assert.equal(h.global.livingRealm.nodes[nodeId].status,'siege');h.global.livingRealm.nodes[nodeId].hp=1;p.official.livingRealm.lastNodeAttackAt=0;const hit=d.attackNode(h,p,nodeId,war.node.siegeStartsAt+2000);assert.equal(hit.ok,true);assert.equal(hit.node.controllerFactionId,'red_pact');assert.equal(hit.node.status,'occupied')});
test('9.14 Chronicle records bounded real server events',()=>{const d=new LivingRealmDomain(),h=host();for(let i=0;i<300;i++)d.chronicle(h,'world',`Headline ${i}`,'body',{},i+1);assert.equal(h.global.livingRealm.chronicle.length,250);assert.equal(d.publicRealm(h).chronicle.length,50);assert.match(d.publicRealm(h).chronicle[0].headline,/Headline 299/)});
test('9.15 grand crafting consumes a production chain and generates quality',()=>{const d=new LivingRealmDomain(),h=host(),p=player('emberhold',30);add(p,'Steel Ingot',10);add(p,'Treated Lumber',3);const r=d.advancedCraft(h,p,'steel_longblade',100,()=>0.9);assert.equal(r.ok,true);assert.ok(CRAFT_GRADES.includes(r.grade));assert.ok(r.quality>=1&&r.quality<=100);assert.ok(p.inventory.some(i=>i.name==='Crafted Steel Longblade'));assert.ok(p.official.livingRealm.crafting.skills.weaponsmithing)});
test('9.16 taming creates bounded trait animals and breeding inherits traits',()=>{const d=new LivingRealmDomain(),h=host(),p=player('ironwood',40);const nearA={contentSourceId:'ironwood_timber_wolf',name:'Timber Wolf',x:41,y:40,dead:false,hp:100};const nearB={contentSourceId:'ironwood_timber_wolf',name:'Timber Wolf',x:40,y:41,dead:false,hp:100};const a=d.tame(h,p,'timber_wolf',[nearA],100,()=>0.01);const b=d.tame(h,p,'timber_wolf',[nearB],200,()=>0.01);assert.equal(a.ok,true);assert.equal(b.ok,true);assert.equal(nearA.dead,true);const child=d.breed(h,p,a.animal.id,b.animal.id,300,()=>0.5);assert.equal(child.ok,true);assert.equal(child.animal.generation,2);assert.ok(Object.values(child.animal.traits).every(v=>v>=1&&v<=100))});
test('9.11-9.16 persistent schema round-trips living realm state',()=>{const d=new LivingRealmDomain(),h=host(),p=player();d.joinFaction(h,p,'crown_eldoria',10);d.chronicle(h,'world','Persistent headline','body',{},11);const ps=normalizePlayerState(p.official);const gs=normalizeGlobalState(h.global);assert.equal(ps.livingRealm.faction.id,'crown_eldoria');assert.equal(gs.livingRealm.chronicle.at(-1).headline,'Persistent headline')});
test('9.11-9.16 action gateway and Studio expose every living realm surface',()=>{for(const name of ['faction_join','faction_defect','node_donate','node_declare_war','node_attack','node_claim','craft_advanced','tame_animal','breed_animals','tame_activate'])assert.ok(OFFICIAL_ACTION_NAMES.includes(name));for(const type of ['nodes','factions','materials','craftingRecipes','tamingSpecies'])assert.ok(CONTENT_STUDIO_SCHEMAS[type]?.length);assert.equal(validateStudioRecord('nodes',{id:'n1',name:'Node',mapId:'eldoria',specialization:'military',x:40,y:40,radius:12,enabled:true,maxHp:5000,stageThresholds:[0,1,2,3,4,5,6],taxRate:5}),null)});
test('9.16 authoring UI stays modular and GameScreen budget is untouched',()=>{const ui=fs.readFileSync(new URL('../../src/components/LivingRealmDirector916.tsx',import.meta.url),'utf8');const editor=fs.readFileSync(new URL('../../src/components/GameEditor.tsx',import.meta.url),'utf8');const game=fs.readFileSync(new URL('../../src/components/GameScreen.tsx',import.meta.url));assert.match(ui,/THE LIVING REALM/);assert.match(ui,/THE MOR'IA CHRONICLE/);assert.match(ui,/BREEDING/);assert.match(editor,/Living Realm 9\.16/);assert.ok(game.length<=155000)});

test('9.16 content persistence keeps legacy schema v3 with a separate Living Realm marker', async()=>{
  const fsMod=await import('node:fs');const os=await import('node:os');const path=await import('node:path');const {ContentDB}=await import('../engine/ContentDB.mjs');
  const dir=fsMod.mkdtempSync(path.join(os.tmpdir(),'moria-lr-content-'));try{const db=new ContentDB(path.join(dir,'content.json'));assert.equal(db.data.version,3);assert.equal(db.data.livingRealmVersion,1);assert.ok(db.get('nodes').length>=10);assert.ok(db.get('factions').length>=6);assert.ok(db.get('craftingRecipes').length>=8);assert.ok(db.get('tamingSpecies').length>=5)}finally{fsMod.rmSync(dir,{recursive:true,force:true})}
});

test('9.16 regional Living Realm reagents do not pollute the legacy itemization contract',()=>{const d=new LivingRealmDomain(),h=host(),p=player('stormwatch_isle',50);p.x=40;p.y=22;const result=d.onMonsterKill(h,p,{name:'Stormwatch Elite',type:'elite'},500);assert.equal(result.material.name,'Storm Core');assert.ok(p.inventory.some(i=>i.name==='Storm Core'&&i.type==='material'))});
