import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {livingWorldAI} from '../engine/LivingWorldAI.mjs';import {beginTelegraph,resolveTelegraph,addStagger,applyStatus,hasStatus,publicCombatState} from '../engine/CombatDepth.mjs';import {interiorSystem} from '../engine/InteriorSystem.mjs';import {WorldEventDirector,worldEventDirector,EVENT_98_TYPES} from '../engine/WorldEventDirector.mjs';import {validateQuestGraph,compileQuestGraph,nextQuestNodes} from '../engine/QuestFlowEngine.mjs';import {validateStudioRecord} from '../engine/ContentStudio.mjs';
const map={tiles:Array.from({length:20},()=>Array.from({length:20},()=>({walkable:true})))};const world={getMap:()=>map};
const db=(data)=>({get:k=>data[k]||[]});
test('9.8 NPC schedules patrol authoritatively and guards can pursue threats',()=>{const content=db({npcs:[{id:'guard',name:'Guard',mapId:'x',posX:5,posY:5,role:'guard',guardRadius:8,moveDelay:250,patrolRoute:[{x:8,y:5}],schedule:[{startHour:0,endHour:24,mode:'patrol'}]}]});livingWorldAI.sync(content);livingWorldAI.tickNpcs({contentDB:content,world,clock:{hour:12},players:[],monstersByMap:new Map([['x',[{id:'m',x:7,y:5,dead:false}]]]),now:1000});const g=livingWorldAI.publicNpcs('x',content)[0];assert.equal(g.mode,'guard');assert.ok(g.x>=5)});
test('9.8 monster AI supports leash flee packs patrol and boss phases',()=>{const m={id:'m',x:8,y:8,spawnX:5,spawnY:5,hp:10,maxHp:100,fleeAtHp:.2,leashRadius:20,speed:1};const step=livingWorldAI.decideMonsterMove(m,{x:9,y:8},{map,occupied:new Set(),now:1000,allies:[]});assert.equal(step.mode,'flee');assert.ok(step.x<=8);assert.equal(livingWorldAI.phase({type:'boss',hp:20,maxHp:100}),3)});
test('9.8 combat telegraph resolves after windup and stagger interrupts it',()=>{const m={id:'b',type:'boss',telegraphMs:300};const p={id:'p'};const t=beginTelegraph(m,p,1000);assert.equal(resolveTelegraph(m,p,1100).ready,false);const r=addStagger(m,200,100,1150);assert.equal(r.interrupted,true);assert.equal(resolveTelegraph(m,p,1400).ready,false);applyStatus(m,'burn',1000,4,1500);assert.equal(hasStatus(m,'burn',1600),true);assert.ok(publicCombatState(m,1600).status.some(s=>s.type==='burn'))});
test('9.8 interiors derive from housing and validate bounded entrances',()=>{const content=db({maps:[{id:'x',interiors:[{id:'inn',name:'Inn',width:8,height:6,entranceX:1,entranceY:5}]}],houses:[{id:'h',name:'Home',mapId:'x',width:7,height:6}]});interiorSystem.sync(content);assert.equal(interiorSystem.list('x').length,2);const player={};assert.equal(interiorSystem.enter(player,'x','inn').ok,true);assert.equal(interiorSystem.snapshot(player).inside,true);assert.equal(interiorSystem.exit(player).ok,true)});
test('9.8 world event director supports invasions bosses caravans defense weather and region events',()=>{for(const t of ['invasion','world_boss','caravan','city_defense','weather','region'])assert.ok(EVENT_98_TYPES.includes(t));const d=new WorldEventDirector();const content=db({events:[{id:'e',name:'Caravan',type:'caravan',mapId:'x',autoStart:true,durationMs:10000,count:2,target:'Wolf'}]});d.tick({contentDB:content,clock:{hour:12},now:1000});assert.equal(d.snapshot('x').length,1);assert.equal(d.recordKill('x',{name:'Wolf'})[0].progress,1)});
test('9.8 visual quest graph validates reachability compiles objectives and branches',()=>{const q={nodes:[{id:'a',type:'dialogue',next:['b']},{id:'b',type:'objective',target:'Wolf',count:3,next:['c']},{id:'c',type:'reward',next:[]}],startNode:'a',branches:[{from:'b',to:'c',condition:{key:'kills',op:'gte',value:3}}]};assert.equal(validateQuestGraph(q),null);const c=compileQuestGraph(q);assert.equal(c.target,'Wolf');assert.equal(c.count,3);assert.deepEqual(nextQuestNodes(q,'b',{kills:3}),['c']);assert.deepEqual(nextQuestNodes(q,'b',{kills:2}),[])});
test('9.8 authoring surfaces are modular and GameScreen budget is not increased',()=>{const editor=fs.readFileSync(new URL('../../src/components/GameEditor.tsx',import.meta.url),'utf8');const city=fs.readFileSync(new URL('../../src/components/CityDesigner98.tsx',import.meta.url),'utf8');const studio=fs.readFileSync(new URL('../engine/ContentStudio.mjs',import.meta.url),'utf8');const gs=fs.readFileSync(new URL('../engine/GameState.mjs',import.meta.url),'utf8');const screen=fs.readFileSync(new URL('../../src/components/GameScreen.tsx',import.meta.url));assert.match(editor,/City Designer 2\.0/);assert.match(editor,/Quest Graph 9\.8/);assert.match(city,/Undo/);assert.match(city,/Resize handle/);assert.match(city,/Protected overlay/);assert.match(studio,/patrolRoute/);assert.match(studio,/interiors/);assert.match(studio,/Quest graph nodes/);assert.match(studio,/Repeat every ms/);assert.match(gs,/livingWorldAI\.tickNpcs/);assert.match(gs,/combat_telegraph/);assert.ok(screen.length<=155000)});

test('9.8 Studio rejects unsafe AI event and graph authoring values',()=>{assert.match(validateStudioRecord('monsters',{id:'bad_monster',name:'Bad',type:'normal',aggroRadius:99})||'',/aggroRadius/);assert.match(validateStudioRecord('npcs',{id:'bad_npc',name:'Bad',role:'guard',mapId:'eldoria',patrolRoute:{}})||'',/patrolRoute/);assert.match(validateStudioRecord('maps',{id:'bad_map',name:'Bad',biome:'grass',interiors:{}})||'',/interiors/);assert.match(validateStudioRecord('events',{id:'bad_event',name:'Bad',type:'invasion',startHour:28})||'',/startHour/)})
