import { useMemo, useState } from 'react';
import { serverSync } from '../game/ServerSync';
import type { Player } from '../game/types';

interface Props { player: Player; official?: any; }
type View='realm'|'chronicle'|'craft'|'stable';
const fmt=(n:number)=>new Intl.NumberFormat().format(Number(n)||0);

export default function LivingRealmPlayerPanel916({player,official}:Props){
  const [view,setView]=useState<View>('realm');
  const [donation,setDonation]=useState(100);
  const [parentA,setParentA]=useState(''); const [parentB,setParentB]=useState('');
  const realm=official?.livingRealm; const mine=realm?.player; const factionId=mine?.faction?.id;
  const faction=(realm?.factions||[]).find((f:any)=>f.id===factionId);
  const node=(realm?.nodes||[]).find((n:any)=>n.mapId===player.mapId);
  const localSpecies=(realm?.tamingSpecies||[]).filter((s:any)=>s.mapId===player.mapId);
  const animals=mine?.taming?.animals||[];
  const breedPairs=useMemo(()=>animals.filter((a:any)=>animals.some((b:any)=>b.id!==a.id&&b.speciesId===a.speciesId)),[animals]);
  if(!realm)return <div className="mt-5 rounded-2xl border border-amber-300/15 bg-black/30 p-4 text-xs text-slate-400"><b className="text-amber-200">🏰 Living Realm 9.16</b><div className="mt-1">Connect to the authoritative MMO server to manage faction allegiance, Nodes, Chronicle, grand crafting and tamed beasts.</div></div>;
  const send=(action:string,payload:any={})=>serverSync.sendOfficial(action,payload);
  return <section className="mt-5 rounded-2xl border border-amber-300/20 bg-black/35 p-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] font-black tracking-[.25em] text-amber-300">THE LIVING REALM</div><div className="text-lg font-black">World Allegiance & Economy</div></div><div className="text-right text-[10px] text-slate-400"><div>{faction?`${faction.icon} ${faction.name}`:'⚪ Unaligned'}</div><div>{node?`${node.name} · ${node.stageName}`:'Outside a Node'}</div></div></div>
    <div className="mt-3 flex flex-wrap gap-1">{([['realm','🏰 Realm'],['chronicle','📰 Chronicle'],['craft','⚒ Craft'],['stable','🐾 Stable']] as [View,string][]).map(([id,label])=><button key={id} onClick={()=>setView(id)} className={`rounded-lg px-3 py-1.5 text-[10px] font-black ${view===id?'bg-amber-400 text-black':'bg-white/5 text-slate-300'}`}>{label}</button>)}</div>
    {view==='realm'&&<div className="mt-3 space-y-3">
      {!factionId?<div><div className="mb-2 text-xs font-bold text-amber-100">Choose your allegiance during the adventure</div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(realm.factions||[]).map((f:any)=><button key={f.id} onClick={()=>send('faction_join',{factionId:f.id})} className="rounded-xl border border-white/10 bg-white/[.03] p-3 text-left hover:bg-white/[.07]"><div className="font-black" style={{color:f.color}}>{f.icon} {f.name}</div><div className="mt-1 text-[9px] text-slate-400">{f.ideology}</div></button>)}</div></div>:<div className="rounded-xl border border-white/10 bg-white/[.03] p-3"><div className="flex justify-between text-xs"><b style={{color:faction?.color}}>{faction?.icon} {faction?.name}</b><span>Rank {mine.faction.rank} · Rep {fmt(mine.faction.reputation)}</span></div><div className="mt-1 text-[10px] text-slate-400">Defection is possible, but imposes reputation loss and a 24-hour political cooldown.</div></div>}
      {node&&<div className="rounded-xl border border-red-300/15 bg-red-950/10 p-3"><div className="flex flex-wrap justify-between gap-2"><div><b>{node.name}</b><div className="text-[9px] uppercase tracking-wider text-slate-500">{node.specialization} · {node.status}</div></div><div className="text-right text-[10px]"><div>XP {fmt(node.xp)} · Treasury {fmt(node.treasury)}</div><div>{node.controllerFactionId||'Neutral control'}</div></div></div><div className="mt-2 h-2 rounded bg-black"><div className="h-full rounded bg-red-500" style={{width:`${Math.max(0,Math.min(100,node.hp/Math.max(1,node.maxHp)*100))}%`}}/></div><div className="mt-2 flex flex-wrap items-center gap-2"><input type="number" min={10} max={100000} value={donation} onChange={e=>setDonation(Number(e.target.value)||10)} className="w-24 rounded bg-black/40 px-2 py-1 text-xs"/><button onClick={()=>send('node_donate',{nodeId:node.id,amount:donation})} className="rounded bg-emerald-700 px-2 py-1 text-[10px] font-bold">Donate</button>{factionId&&!node.controllerFactionId&&<button onClick={()=>send('node_claim',{nodeId:node.id})} className="rounded bg-amber-600 px-2 py-1 text-[10px] font-bold">Claim Node</button>}{factionId&&node.controllerFactionId!==factionId&&['peace','recovery'].includes(node.status)&&<button onClick={()=>send('node_declare_war',{nodeId:node.id})} className="rounded bg-red-700 px-2 py-1 text-[10px] font-bold">Declare War · 5,000g</button>}{node.status==='siege'&&node.attackerFactionId===factionId&&<button onClick={()=>send('node_attack',{nodeId:node.id})} className="rounded bg-red-600 px-2 py-1 text-[10px] font-black">⚔ Attack Node</button>}</div></div>}
    </div>}
    {view==='chronicle'&&<div className="mt-3 rounded-xl border border-amber-200/15 bg-[#17110c] p-4"><div className="font-serif text-xl font-black text-amber-100">The Mor'ia Chronicle</div><div className="mb-3 text-[9px] tracking-[.2em] text-amber-300/50">REAL EVENTS FROM THIS SERVER</div><div className="space-y-3">{(realm.chronicle||[]).slice(0,8).map((n:any)=><article key={n.id} className="border-b border-amber-100/10 pb-2"><div className="text-[8px] font-black uppercase tracking-wider text-red-300">{n.type} · {n.severity}</div><b className="font-serif text-sm text-amber-50">{n.headline}</b><div className="text-[10px] text-amber-100/55">{n.body}</div></article>)}</div></div>}
    {view==='craft'&&<div className="mt-3"><div className="mb-2 text-[10px] text-slate-400">Quality = material baseline + profession skill + station/Node + faction control − recipe difficulty + bounded server roll.</div><div className="grid gap-2 sm:grid-cols-2">{(realm.craftingRecipes||[]).map((r:any)=><div key={r.id} className="rounded-xl border border-white/10 bg-white/[.03] p-3"><div className="flex justify-between"><b className="text-xs">{r.name}</b><span className="text-[9px] text-amber-300">Diff {r.difficulty}</span></div><div className="mt-1 text-[9px] text-slate-400">{r.profession} · {r.stationType}</div><div className="mt-2 text-[9px] text-slate-500">{(r.inputs||[]).map((i:any)=>`${i.quantity}× ${i.name}`).join(' · ')}</div><button onClick={()=>send('craft_advanced',{recipeId:r.id})} className="mt-2 rounded bg-orange-700 px-2 py-1 text-[10px] font-bold">Craft</button></div>)}</div></div>}
    {view==='stable'&&<div className="mt-3 space-y-3"><div><div className="mb-2 text-xs font-bold">Creatures in this habitat</div><div className="flex flex-wrap gap-2">{localSpecies.length?localSpecies.map((s:any)=><button key={s.id} onClick={()=>send('tame_animal',{speciesId:s.id})} className="rounded-xl border border-emerald-300/15 bg-emerald-950/20 p-3 text-left"><b>{s.icon} {s.name}</b><div className="text-[9px] uppercase text-emerald-300">{s.rarity} · temperament {s.temperament}</div><div className="text-[9px] text-slate-500">Requires a matching live creature within 2 tiles.</div></button>):<div className="text-[10px] text-slate-500">No tameable species configured for this map.</div>}</div></div><div><div className="mb-2 text-xs font-bold">Stable · {animals.length}/40 · Taming skill {mine.taming.skill}</div><div className="grid gap-2 sm:grid-cols-2">{animals.map((a:any)=><button key={a.id} onClick={()=>send('tame_activate',{animalId:a.id})} className={`rounded-xl border p-2 text-left ${mine.taming.activeId===a.id?'border-emerald-400 bg-emerald-900/20':'border-white/10 bg-white/[.03]'}`}><b className="text-xs">{a.icon} {a.name}</b><div className="text-[9px] text-slate-400">Gen {a.generation} · {a.rarity}{a.mutation?` · MUTATION ${a.mutation}`:''}</div></button>)}</div></div>{breedPairs.length>=2&&<div className="rounded-xl border border-fuchsia-300/15 bg-fuchsia-950/15 p-3"><b className="text-xs text-fuchsia-200">Breeding Lab · 500g</b><div className="mt-2 flex flex-wrap gap-2"><select value={parentA} onChange={e=>setParentA(e.target.value)} className="rounded bg-black/50 p-1 text-[10px]"><option value="">Parent A</option>{breedPairs.map((a:any)=><option key={a.id} value={a.id}>{a.name} G{a.generation}</option>)}</select><select value={parentB} onChange={e=>setParentB(e.target.value)} className="rounded bg-black/50 p-1 text-[10px]"><option value="">Parent B</option>{breedPairs.map((a:any)=><option key={a.id} value={a.id}>{a.name} G{a.generation}</option>)}</select><button disabled={!parentA||!parentB||parentA===parentB} onClick={()=>send('breed_animals',{parentAId:parentA,parentBId:parentB})} className="rounded bg-fuchsia-700 px-2 py-1 text-[10px] font-bold disabled:opacity-40">Breed</button></div></div>}</div>}
  </section>;
}
