import { useState } from 'react';
const nodes=[['Eldoria Crownlands','Commercial','Village','Crown of Eldoria','82%'],['Frostpeak Bastion','Military','Fortress','Red Pact','41%'],['Ironwood Wild March','Wild','City','Children of the Wild','67%'],['Crystal Deep Conclave','Arcane','City','Arcane Conclave','55%']];
const news=[['WAR','Red Pact declares siege on Frostpeak','Defenders have entered the preparation window.'],['CRAFT','A relic-grade Arcane Focus was forged','The crafter used Crystal Deep station bonuses.'],['BEAST','A rare Frost Wolf was tamed','The server recorded the new beastmaster achievement.'],['POLITICS','Eldoria trade taxes reduced to 4%','The commercial node reached a new development stage.']];
const factions=[['♛','Crown of Eldoria','Order · Trade · Defense'],['⚔','Red Pact','Conquest · Siege · Martial'],['✦','Arcane Conclave','Relics · Magic · Knowledge'],['☾','Order of the Veil','Death · Shadow · Secrets'],['❧','Children of the Wild','Nature · Beasts · Taming'],['⚓','Free League','Trade · Exploration · Freedom']];
const recipes=[['Steel Longblade','Weaponsmithing','Forge','35'],['Dragon Scale Plate','Armorsmithing','Forge','70'],['Arcane Focus','Enchanting','Enchanter','55'],['Battering Ram Kit','Siege Engineering','Siegeworks','60']];
const beasts=[['🐺','Wild Wolf','Common','Combat · Scout'],['🐻','Brown Bear','Uncommon','Combat · Pack'],['❄','Frost Wolf','Rare','Mount · Combat · Scout'],['⚡','Storm Raptor','Epic','Mount · Combat'],['🌑','Shadow Panther','Legendary','Combat · Scout']];
type Tab='nodes'|'factions'|'chronicle'|'crafting'|'taming';
export default function LivingRealmDirector916(){const [tab,setTab]=useState<Tab>('nodes');return <div className="space-y-3 text-slate-100">
 <div className="rounded-xl border border-amber-300/30 bg-black/40 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="text-[10px] font-black tracking-[.28em] text-amber-300">MOR'IA 9.16</div><div className="text-xl font-black">THE LIVING REALM</div><div className="text-xs text-slate-400">Persistent nodes, factions, server chronicle, grand crafting and beast breeding.</div></div><div className="rounded-lg border border-emerald-400/30 bg-emerald-400/10 px-3 py-2 text-xs text-emerald-200">SERVER AUTHORITY · PERSISTENT</div></div></div>
 <div className="flex flex-wrap gap-2">{([['nodes','🏰 Nodes'],['factions','⚑ Factions'],['chronicle','📰 Chronicle'],['crafting','⚒ Grand Craft'],['taming','🐾 Taming']] as [Tab,string][]).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-lg px-3 py-2 text-xs font-black ${tab===id?'bg-amber-500 text-black':'bg-white/5 text-slate-300'}`}>{label}</button>)}</div>
 {tab==='nodes'&&<div className="grid grid-cols-2 gap-3"><div className="col-span-2 rounded-lg border border-red-400/30 bg-red-950/20 p-3"><div className="flex justify-between text-xs"><b className="text-red-300">⚔ NODE WAR CAMPAIGN</b><span>Declared → Preparation → Siege → Occupied → Recovery</span></div><div className="mt-2 h-2 overflow-hidden rounded bg-black"><div className="h-full w-[64%] bg-red-500"/></div></div>{nodes.map(n=><div key={n[0]} className="rounded-xl border border-white/10 bg-black/30 p-3"><div className="flex justify-between"><b>{n[0]}</b><span className="text-amber-300">{n[2]}</span></div><div className="mt-1 text-[10px] uppercase tracking-widest text-slate-500">{n[1]} NODE</div><div className="mt-3 flex justify-between text-xs"><span>{n[3]}</span><span>{n[4]} development</span></div><div className="mt-1 h-1.5 rounded bg-black"><div className="h-full w-2/3 rounded bg-emerald-500"/></div></div>)}</div>}
 {tab==='factions'&&<div className="grid grid-cols-3 gap-3">{factions.map(f=><div key={f[1]} className="rounded-xl border border-white/10 bg-black/30 p-4 text-center"><div className="text-3xl">{f[0]}</div><b className="mt-2 block">{f[1]}</b><div className="mt-1 text-[10px] text-slate-400">{f[2]}</div><div className="mt-3 rounded bg-white/5 px-2 py-1 text-[10px] text-amber-200">Chosen during gameplay · defection has consequences</div></div>)}</div>}
 {tab==='chronicle'&&<div className="rounded-xl border border-amber-200/20 bg-[#18120d] p-5"><div className="border-b border-amber-200/20 pb-3 text-center"><div className="font-serif text-3xl font-black tracking-wider text-amber-100">THE MOR'IA CHRONICLE</div><div className="text-[10px] tracking-[.35em] text-amber-300/60">SERVER HISTORY · POLITICS · ECONOMY · HEROES</div></div><div className="mt-4 grid grid-cols-2 gap-4">{news.map((n,i)=><article key={n[1]} className={`border-b border-amber-100/10 pb-4 ${i===0?'col-span-2':''}`}><div className="text-[9px] font-black tracking-[.25em] text-red-300">{n[0]}</div><h3 className={`${i===0?'text-xl':'text-base'} font-serif font-black text-amber-50`}>{n[1]}</h3><p className="mt-1 text-xs text-amber-100/60">{n[2]}</p></article>)}</div></div>}
 {tab==='crafting'&&<div className="grid grid-cols-[1.2fr_.8fr] gap-3"><div className="rounded-xl border border-orange-300/20 bg-black/30 p-4"><div className="mb-3 font-black text-orange-200">⚒ PRODUCTION CHAIN</div><div className="flex items-center justify-between rounded bg-white/5 p-3 text-xs"><span>Gathering</span><span>→</span><span>Processing</span><span>→</span><span>Components</span><span>→</span><span>Master Craft</span></div><div className="mt-3 space-y-2">{recipes.map(r=><div key={r[0]} className="grid grid-cols-4 rounded border border-white/5 bg-white/[.03] p-2 text-xs"><b>{r[0]}</b><span>{r[1]}</span><span>{r[2]}</span><span className="text-right text-amber-300">Difficulty {r[3]}</span></div>)}</div></div><div className="rounded-xl border border-purple-300/20 bg-purple-950/20 p-4"><b>QUALITY ENGINE</b><div className="mt-3 space-y-2 text-xs text-slate-300"><div>Material quality</div><div>Crafter skill</div><div>Recipe difficulty</div><div>Station / Node level</div><div>Industrial faction control</div><div>Critical variance</div></div><div className="mt-4 rounded bg-black/30 p-3 text-center text-sm font-black text-purple-200">Crude → Common → Fine → Masterwork → Epic → Relic</div></div></div>}
 {tab==='taming'&&<div className="grid grid-cols-5 gap-2">{beasts.map(b=><div key={b[1]} className="rounded-xl border border-emerald-300/15 bg-emerald-950/15 p-3 text-center"><div className="text-3xl">{b[0]}</div><b className="mt-2 block text-sm">{b[1]}</b><div className="text-[10px] font-black uppercase text-emerald-300">{b[2]}</div><div className="mt-2 text-[10px] text-slate-400">{b[3]}</div><div className="mt-3 border-t border-white/5 pt-2 text-[9px] text-slate-500">Temperament · Strength · Speed · Endurance · Intelligence · Loyalty · Wildness</div></div>)}<div className="col-span-5 rounded-lg border border-fuchsia-300/20 bg-fuchsia-950/15 p-3 text-xs"><b className="text-fuchsia-200">BREEDING:</b> offspring inherit bounded parental traits; rare server-side mutations can improve one trait and are recorded in the Chronicle.</div></div>}
 </div>}
