import { useMemo, useState } from 'react';
import { serverSync } from '../game/ServerSync';
import type { Player } from '../game/types';

interface Props{player:Player;official?:any}
type View='summary'|'economy'|'professions'|'beasts'|'politics'|'warfare'|'dungeons'|'quests'|'housing';
const fmt=(v:any)=>new Intl.NumberFormat().format(Number(v)||0);
const button='rounded bg-cyan-700 px-2 py-1 text-[10px] font-bold hover:bg-cyan-600 disabled:opacity-40';

export default function RoadToTenPlayerPanel926({player,official}:Props){
 const [view,setView]=useState<View>('summary');const [amount,setAmount]=useState(500);const [candidate,setCandidate]=useState(player.name);const [target,setTarget]=useState('');const [bounty,setBounty]=useState(500);const [dipTarget,setDipTarget]=useState('free_league');const [dipStatus,setDipStatus]=useState('neutral');const road=official?.roadToTen;const realm=official?.livingRealm;const mapId=serverSync.getMapId();const region=road?.regions?.[mapId];const mine=road?.player;const livingMine=realm?.player;const factionId=livingMine?.faction?.id;const faction=(realm?.factions||[]).find((f:any)=>f.id===factionId);const node=(realm?.nodes||[]).find((n:any)=>n.mapId===mapId);const fort=node?road?.warfare?.nodes?.[node.id]:null;const send=(action:string,payload:any={})=>serverSync.sendOfficial(action,payload);
 const animals=livingMine?.taming?.animals||[];const assets=fort?.assets||[];const choices=mine?.quests?.choices||{};
 const localDungeons=useMemo(()=>(road?.content?.dungeonBlueprints||[]).filter((d:any)=>d.mapId===mapId),[road,mapId]);
 if(!road)return <div className="mt-4 rounded-2xl border border-cyan-300/15 bg-black/30 p-4 text-xs text-slate-400"><b className="text-cyan-200">✦ Road to 10 · 9.26</b><div className="mt-1">Connect to the authoritative server to see economy, politics, dynamic-world and progression integration.</div></div>;
 return <section className="mt-4 rounded-2xl border border-cyan-300/20 bg-black/35 p-4" data-road-player="9.26">
  <div className="flex flex-wrap items-center justify-between gap-2"><div><div className="text-[10px] font-black tracking-[.25em] text-cyan-300">ROAD TO 10 · 9.26</div><div className="text-lg font-black">Living World Operating Layer</div></div><div className="text-right text-[9px] text-slate-400"><div>{faction?`${faction.icon} ${faction.name}`:'Unaligned'}</div><div>{node?`${node.name} · ${node.stageName}`:mapId}</div></div></div>
  <div className="mt-3 flex flex-wrap gap-1">{([['summary','🔗 Summary'],['economy','🪙 Economy'],['professions','⚒ Professions'],['beasts','🐾 Beasts'],['politics','⚑ Politics'],['warfare','🏹 Warfare'],['dungeons','☠ Dungeons'],['quests','🕸 Quests'],['housing','🏠 Housing']] as [View,string][]).map(([id,l])=><button key={id} onClick={()=>setView(id)} className={`rounded px-2 py-1.5 text-[9px] font-black ${view===id?'bg-cyan-400 text-black':'bg-white/5 text-slate-300'}`}>{l}</button>)}</div>

  {view==='summary'&&<div className="mt-3 grid gap-2 sm:grid-cols-4">{[['Price index',`×${Number(region?.modifiers?.priceMultiplier||1).toFixed(2)}`],['Craft bonus',`+${Number(region?.modifiers?.craftQualityBonus||0).toFixed(1)}`],['Spawn pressure',`×${Number(region?.modifiers?.spawnThreatMultiplier||1).toFixed(2)}`],['Prosperity',`${fmt(region?.economy?.prosperity)}/100`],['Supply',`${fmt(region?.economy?.supply)}/100`],['Ecology',`${fmt(region?.dynamic?.ecology)}/100`],['Corruption',`${fmt(region?.dynamic?.corruption)}/100`],['World events',String((road.dynamicEvents||[]).filter((e:any)=>e.mapId===mapId).length)]].map(x=><div key={x[0]} className="rounded-xl border border-white/10 bg-white/[.03] p-3"><div className="text-[9px] text-slate-500">{x[0]}</div><b className="text-cyan-200">{x[1]}</b></div>)}</div>}

  {view==='economy'&&<div className="mt-3 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-white/10 bg-white/[.03] p-3"><b>Regional Market</b><div className="mt-2 space-y-1 text-[10px] text-slate-300"><div>Price index: ×{Number(region?.economy?.priceIndex||1).toFixed(3)}</div><div>Trade volume: {fmt(region?.economy?.tradeVolume)}g</div><div>Supply: {fmt(region?.economy?.supply)}</div><div>Demand: {fmt(region?.economy?.demand)}</div><div>Prosperity: {fmt(region?.economy?.prosperity)}</div></div></div><div className="rounded-xl border border-amber-300/15 bg-amber-950/10 p-3 text-[10px] text-slate-300"><b className="text-amber-200">Live integration</b><p className="mt-2">Official shop purchases use this regional multiplier server-side. Taxes feed the active Node treasury; trade shifts supply, demand and prosperity.</p></div></div>}

  {view==='professions'&&<div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(road.content?.professionSpecializations||[]).map((s:any)=>{const chosen=mine?.professions?.specializations?.[String(s.profession).toLowerCase().replace(/[^a-z0-9]+/g,'_')];return <div key={s.id} className="rounded-xl border border-white/10 bg-white/[.03] p-3"><b>{s.icon} {s.name}</b><div className="mt-1 text-[9px] text-slate-400">{s.profession} · requires skill {s.requiredLevel}</div><div className="text-[9px] text-purple-300">Quality +{s.qualityBonus} · {(s.tags||[]).join(' · ')}</div><button disabled={Boolean(chosen)} onClick={()=>send('profession_specialize',{specId:s.id})} className={`${button} mt-2`}>{chosen===s.id?'Selected':chosen?'Path locked':'Specialize'}</button></div>})}<div className="sm:col-span-2 lg:col-span-3 rounded-xl border border-purple-300/15 bg-purple-950/10 p-3 text-[10px]">Discovered recipes: {(mine?.professions?.discoveries||[]).length?mine.professions.discoveries.join(' · '):'None yet — high-skill crafting can discover recipes server-side.'}</div></div>}

  {view==='beasts'&&<div className="mt-3 grid gap-2 sm:grid-cols-2">{animals.map((a:any)=>{const care=mine?.beastCare?.animals?.[a.id]||{};return <div key={a.id} className="rounded-xl border border-emerald-300/15 bg-emerald-950/10 p-3"><div className="flex justify-between"><b>{a.icon} {a.name}</b><span className="text-[9px] text-emerald-300">Bond {fmt(a.bond)}/100</span></div><div className="mt-1 text-[9px] text-slate-400">Happiness {fmt(care.happiness||60)} · Health {fmt(care.health||100)} · Training {fmt(care.training||0)} · Role {care.role||'none'}</div><div className="mt-2 flex flex-wrap gap-1"><button onClick={()=>send('beast_care',{animalId:a.id,kind:'feed'})} className={button}>Feed · 25g</button><button onClick={()=>send('beast_care',{animalId:a.id,kind:'train'})} className={button}>Train · 80g</button>{(a.roles||[]).map((r:string)=><button key={r} onClick={()=>send('beast_role',{animalId:a.id,role:r})} className="rounded bg-emerald-700 px-2 py-1 text-[9px]">{r}</button>)}</div></div>})}{!animals.length&&<div className="text-[10px] text-slate-500">Tame animals in Living Realm first; Road-to-10 care and training then attach to the same persistent bloodline.</div>}</div>}

  {view==='politics'&&<div className="mt-3 space-y-3">{factionId?<><div className="grid gap-2 sm:grid-cols-3"><div className="rounded-xl border border-white/10 p-3"><div className="text-[9px] text-slate-500">Treasury</div><b className="text-emerald-300">{fmt(road.politics?.factions?.[factionId]?.treasury)}g</b></div><div className="rounded-xl border border-white/10 p-3"><div className="text-[9px] text-slate-500">Leader</div><b className="text-amber-200">{road.politics?.factions?.[factionId]?.leader||'No elected leader'}</b></div><div className="rounded-xl border border-white/10 p-3"><div className="text-[9px] text-slate-500">Your influence</div><b className="text-cyan-200">{fmt(mine?.politics?.influence)}</b></div></div><div className="flex flex-wrap gap-2"><input type="number" value={amount} onChange={e=>setAmount(Number(e.target.value)||100)} className="w-24 rounded bg-black/40 px-2 py-1 text-xs"/><button onClick={()=>send('faction_treasury_donate',{amount})} className={button}>Fund faction</button><input value={candidate} onChange={e=>setCandidate(e.target.value)} className="rounded bg-black/40 px-2 py-1 text-xs"/><button onClick={()=>send('faction_vote',{candidate})} className={button}>Vote · 5 influence</button></div><div className="mt-2 flex flex-wrap gap-2"><select value={dipTarget} onChange={e=>setDipTarget(e.target.value)} className="rounded bg-black/40 px-2 py-1 text-xs">{(realm?.factions||[]).filter((f:any)=>f.id!==factionId).map((f:any)=><option key={f.id} value={f.id}>{f.name}</option>)}</select><select value={dipStatus} onChange={e=>setDipStatus(e.target.value)} className="rounded bg-black/40 px-2 py-1 text-xs"><option value="allied">allied</option><option value="neutral">neutral</option><option value="rival">rival</option><option value="war">war</option></select><button onClick={()=>send('faction_diplomacy',{targetFactionId:dipTarget,status:dipStatus})} className={button}>Set diplomacy · leader only</button></div><div className="rounded-xl border border-red-300/15 bg-red-950/10 p-3"><b className="text-xs">Bounty Board</b><div className="mt-2 flex flex-wrap gap-2"><input placeholder="Target character" value={target} onChange={e=>setTarget(e.target.value)} className="rounded bg-black/40 px-2 py-1 text-xs"/><input type="number" value={bounty} onChange={e=>setBounty(Number(e.target.value)||500)} className="w-24 rounded bg-black/40 px-2 py-1 text-xs"/><button disabled={!target} onClick={()=>send('bounty_place',{targetName:target,reward:bounty})} className={button}>Post bounty</button></div></div></>:<div className="text-[10px] text-slate-500">Choose a Living Realm faction before participating in politics.</div>}</div>}

  {view==='warfare'&&<div className="mt-3 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-red-300/15 bg-red-950/10 p-3"><b>{node?.name||'No local Node'}</b><div className="mt-2 text-[10px] text-slate-300">Walls {fmt(fort?.wallHp)}/{fmt(fort?.wallMax)} · Gate {fmt(fort?.gateHp)}/{fmt(fort?.gateMax)} · Towers {fmt(fort?.towerHp)}/{fmt(fort?.towerMax)} · Supply {fmt(fort?.supply)}</div><div className="mt-3 flex flex-wrap gap-1">{node&&(road.content?.siegeAssets||[]).map((a:any)=><button key={a.id} onClick={()=>send('siege_build',{nodeId:node.id,assetId:a.id})} className="rounded bg-red-800 px-2 py-1 text-[9px]">{a.icon} Build {a.name}</button>)}</div></div><div className="rounded-xl border border-white/10 bg-white/[.03] p-3"><b>Field Assets</b><div className="mt-2 space-y-1">{assets.map((a:any)=><button key={a.id} onClick={()=>send('siege_use',{nodeId:node.id,builtAssetId:a.id})} className="block w-full rounded bg-white/5 p-2 text-left text-[9px]">{a.assetId} · durability {a.durability} · use</button>)}{!assets.length&&<div className="text-[9px] text-slate-500">No siege assets deployed.</div>}</div></div></div>}

  {view==='dungeons'&&<div className="mt-3 grid gap-2 sm:grid-cols-2">{localDungeons.map((d:any)=><div key={d.id} className="rounded-xl border border-purple-300/15 bg-purple-950/10 p-3"><div className="flex justify-between"><b>{d.icon} {d.name}</b><span className="text-[9px] text-purple-300">Lv {d.minLevel} · Node {d.requiredNodeStage}+</span></div><div className="mt-1 text-[9px] text-slate-400">Boss {d.boss} · puzzle {d.puzzle}</div><button onClick={()=>send('dungeon_blueprint_start',{blueprintId:d.id})} className={`${button} mt-2`}>Enter blueprint</button><div className="mt-2 flex gap-1">{(d.paths||[]).map((p:string)=><button key={p} onClick={()=>send('dungeon_path',{path:p})} className="rounded bg-purple-800 px-2 py-1 text-[9px]">{p}</button>)}</div>{mine?.dungeon?.blueprintId===d.id&&mine?.dungeon?.puzzle&&!mine?.dungeon?.puzzleSolved&&<div className="mt-2 rounded bg-cyan-500/10 p-2"><div className="text-[9px] text-cyan-200">Puzzle {mine.dungeon.puzzle} · sequence {mine.dungeon.puzzleProgress||0}/3</div><div className="mt-1 flex gap-1">{[0,1,2,3].map(r=><button key={r} onClick={()=>send('dungeon_puzzle',{runeIndex:r})} className="rounded bg-cyan-800 px-2 py-1 text-[9px]">Rune {r+1}</button>)}</div></div>}</div>)}{!localDungeons.length&&<div className="text-[10px] text-slate-500">No Road-to-10 dungeon blueprint is configured for this region.</div>}</div>}

  {view==='quests'&&<div className="mt-3 grid gap-2 sm:grid-cols-2">{(road.content?.questConsequences||[]).map((c:any)=><div key={c.id} className="rounded-xl border border-amber-300/15 bg-amber-950/10 p-3"><b>{c.label}</b><div className="mt-1 text-[9px] text-slate-400">Quest {c.questId} · choice {c.choice}</div><div className="mt-1 text-[9px] text-amber-200/70">{c.chronicle}</div><button disabled={Boolean(choices[c.questId])} onClick={()=>send('quest_consequence',{consequenceId:c.id})} className={`${button} mt-2`}>{choices[c.questId]?'Decision recorded':'Choose consequence'}</button></div>)}</div>}

  {view==='housing'&&<div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(road.content?.housingUpgrades||[]).map((u:any)=>{const owned=(mine?.housing?.upgrades||[]).includes(u.id);return <div key={u.id} className="rounded-xl border border-white/10 bg-white/[.03] p-3"><b>{u.icon} {u.name}</b><div className="mt-1 text-[9px] text-slate-400">{u.category} · level {u.level} · {fmt(u.goldCost)}g</div><div className="mt-2 text-[9px] text-emerald-300">{Object.entries(u.benefits||{}).map(([k,v])=>`${k} ${v}`).join(' · ')}</div><button disabled={owned} onClick={()=>send('housing_upgrade',{upgradeId:u.id})} className={`${button} mt-2`}>{owned?'Installed':'Install upgrade'}</button></div>})}</div>}
 </section>
}
