import { useState } from 'react';

type Tab='integration'|'economy'|'professions'|'beasts'|'politics'|'warfare'|'world'|'dungeons'|'quests'|'housing';
const tabs:[Tab,string][]=[['integration','🔗 9.17 Integration'],['economy','🪙 9.18 Economy'],['professions','⚒ 9.19 Professions'],['beasts','🐾 9.20 Taming 2.0'],['politics','⚑ 9.21 Politics'],['warfare','🏹 9.22 Warfare'],['world','🌍 9.23 Dynamic World'],['dungeons','☠ 9.24 Dungeons'],['quests','🕸 9.25 Quests'],['housing','🏠 9.26 Housing']];
const card='rounded-xl border border-white/10 bg-black/30 p-3';
const meter=(value:number,label:string)=><div><div className="mb-1 flex justify-between text-[9px] text-slate-400"><span>{label}</span><b>{value}%</b></div><div className="h-1.5 rounded bg-black"><div className="h-full rounded bg-emerald-500" style={{width:`${value}%`}}/></div></div>;

export default function RoadToTenDirector926(){const [tab,setTab]=useState<Tab>('integration');return <div className="space-y-3 text-slate-100" data-road-to-ten="9.26">
  <div className="rounded-xl border border-cyan-300/30 bg-black/45 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] font-black tracking-[.28em] text-cyan-300">MOR'IA 9.17 → 9.26</div><h2 className="text-xl font-black">ROAD TO 10 · WORLD OPERATING LAYER</h2><p className="text-xs text-slate-400">Economy, politics, warfare, ecology, dungeons, consequences and housing consume the same authoritative Living Realm state.</p></div><div className="rounded-lg border border-emerald-400/30 bg-emerald-400/10 px-3 py-2 text-xs font-black text-emerald-200">CONTENT STUDIO · SERVER AUTHORITY · PERSISTENT</div></div></div>
  <div className="flex flex-wrap gap-1.5">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-lg px-2.5 py-2 text-[10px] font-black ${tab===id?'bg-cyan-400 text-black':'bg-white/5 text-slate-300'}`}>{label}</button>)}</div>

  {tab==='integration'&&<div className="grid grid-cols-3 gap-3"><div className={`${card} col-span-3`}><b className="text-cyan-200">🔗 ONE WORLD STATE</b><div className="mt-3 grid grid-cols-5 gap-2 text-center text-[10px]"><span className="rounded bg-white/5 p-2">Node state</span><span className="rounded bg-white/5 p-2">Faction allegiance</span><span className="rounded bg-white/5 p-2">Regional economy</span><span className="rounded bg-white/5 p-2">Dynamic pressure</span><span className="rounded bg-white/5 p-2">Player decisions</span></div><div className="mt-3 text-center text-xs text-slate-400">↓ authoritative modifiers feed shops · crafting · spawns · taming · quests · sieges · housing ↓</div></div>{[['Commercial Node','Price ×0.92','Trade +15%'],['Industrial Node','Craft +6','Demand +18%'],['Wild Node','Taming +8%','Ecology +12']].map(x=><div key={x[0]} className={card}><b>{x[0]}</b><div className="mt-3 text-sm text-emerald-300">{x[1]}</div><div className="text-xs text-slate-400">{x[2]}</div></div>)}</div>}

  {tab==='economy'&&<div className="grid grid-cols-[1.1fr_.9fr] gap-3"><div className={card}><b className="text-amber-200">REGIONAL MARKET INDEX</b><div className="mt-3 grid grid-cols-4 gap-2 text-xs">{[['Eldoria','0.93','72','64'],['Frostpeak','1.18','31','78'],['Ironwood','0.97','66','51'],['Crystal Deep','1.08','47','69']].map(r=><div key={r[0]} className="rounded border border-white/5 bg-white/[.03] p-2"><b>{r[0]}</b><div className="mt-2 text-amber-300">Price ×{r[1]}</div><div className="text-[9px] text-slate-500">Supply {r[2]} · Demand {r[3]}</div></div>)}</div></div><div className={card}><b>ECONOMIC SINKS & FLOWS</b><div className="mt-3 space-y-2 text-xs text-slate-300"><div>Node taxes → territorial treasury</div><div>Auction / shops → regional demand</div><div>Crafting → industrial pressure</div><div>War → scarcity and military demand</div><div>Prosperity → Chronicle headlines</div></div></div></div>}

  {tab==='professions'&&<div className="grid grid-cols-3 gap-3">{[['⚔','Weaponsmith','Weapon mastery · signatures'],['🛡','Armorsmith','Plate · shields · fortification'],['ᚱ','Runesmith','Runes · enchantments · relics'],['🏗','Siege Engineer','Siege engines · field repair'],['⚗','Alchemical Master','Reagents · elixirs · transmutation'],['🐾','Beast Artificer','Saddles · harnesses · beast gear']].map(x=><div className={card} key={x[1]}><div className="text-2xl">{x[0]}</div><b>{x[1]}</b><div className="mt-1 text-[10px] text-slate-400">{x[2]}</div><div className="mt-3 rounded bg-purple-500/10 p-2 text-[9px] text-purple-200">Recipe discoveries · quality bonus · crafter identity</div></div>)}</div>}

  {tab==='beasts'&&<div className="grid grid-cols-[.8fr_1.2fr] gap-3"><div className={card}><b>BEAST CARE LOOP</b><div className="mt-3 space-y-2 text-xs"><div>🍖 Feed → happiness / health</div><div>🎯 Train → bounded trait growth</div><div>❤ Bond → companion effectiveness</div><div>🧬 Breed → inherited bloodlines</div><div>🏷 Assign role → combat / mount / pack / scout</div></div></div><div className={card}><div className="flex justify-between"><b>ICEFANG WOLF · GEN 3</b><span className="text-purple-300">rare bloodline</span></div><div className="mt-3 grid grid-cols-2 gap-3">{meter(84,'Speed')}{meter(72,'Strength')}{meter(79,'Endurance')}{meter(68,'Loyalty')}{meter(91,'Happiness')}{meter(64,'Training')}</div><div className="mt-3 rounded bg-emerald-500/10 p-2 text-[10px] text-emerald-200">Assigned role: Scout · mutation: enhanced_speed</div></div></div>}

  {tab==='politics'&&<div className="grid grid-cols-3 gap-3"><div className={`${card} col-span-2`}><b>FACTION COUNCIL</b><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div className="rounded bg-white/5 p-3"><span className="text-slate-500">Leader</span><b className="block text-amber-200">Ser Kael</b></div><div className="rounded bg-white/5 p-3"><span className="text-slate-500">Treasury</span><b className="block text-emerald-300">248,500g</b></div><div className="rounded bg-white/5 p-3"><span className="text-slate-500">Influence</span><b className="block text-cyan-300">8,420</b></div></div><div className="mt-3 text-[10px] text-slate-400">Player voting · treasury donations · weekly objectives · leadership-gated diplomacy.</div></div><div className={card}><b>DIPLOMACY</b><div className="mt-3 space-y-2 text-xs"><div className="text-emerald-300">Crown ↔ Free League · ALLIED</div><div className="text-red-300">Crown ↔ Red Pact · WAR</div><div>Conclave ↔ Wild · NEUTRAL</div><div className="text-orange-300">Veil ↔ Conclave · RIVAL</div></div></div><div className={`${card} col-span-3`}><b>BOUNTY BOARD</b><div className="mt-2 grid grid-cols-3 gap-2 text-xs"><div className="rounded bg-red-500/10 p-2">ShadowRook · 12,000g</div><div className="rounded bg-red-500/10 p-2">Varka · 8,500g</div><div className="rounded bg-red-500/10 p-2">Black Tide · 20,000g</div></div></div></div>}

  {tab==='warfare'&&<div className="grid grid-cols-2 gap-3"><div className={card}><div className="flex justify-between"><b>FROSTPEAK FORTIFICATION</b><span className="text-red-300">SIEGE</span></div><div className="mt-3 space-y-3">{meter(74,'Walls')}{meter(38,'Gate')}{meter(61,'Towers')}{meter(52,'Supply')}</div></div><div className={card}><b>SIEGE FIELD</b><div className="mt-3 grid grid-cols-2 gap-2 text-xs">{[['🪵','Battering Ram','Gate'],['☄','Catapult','Wall'],['➶','Ballista','Tower'],['🧰','Repair Crew','Defense']].map(x=><div key={x[1]} className="rounded border border-white/5 bg-white/[.03] p-2"><span className="text-xl">{x[0]}</span><b className="ml-2">{x[1]}</b><div className="text-[9px] text-slate-500">Target: {x[2]}</div></div>)}</div></div></div>}

  {tab==='world'&&<div className="grid grid-cols-3 gap-3"><div className={`${card} col-span-2`}><b>WORLD SIMULATION · IRONWOOD</b><div className="mt-3 grid grid-cols-3 gap-3">{meter(68,'Ecology')}{meter(24,'Threat')}{meter(7,'Corruption')}{meter(71,'Prosperity')}{meter(63,'Supply')}{meter(15,'Crime')}</div></div><div className={card}><b>ACTIVE THRESHOLDS</b><div className="mt-3 space-y-2 text-xs"><div className="rounded bg-emerald-500/10 p-2 text-emerald-200">Beast Bloom · 14m</div><div className="rounded bg-slate-500/10 p-2 text-slate-400">Famine · inactive</div><div className="rounded bg-slate-500/10 p-2 text-slate-400">Shadow Corruption · inactive</div></div></div><div className={`${card} col-span-3 text-xs text-slate-300`}>Monster pressure, trade, Node supply, quests and world bosses continuously push these values. Crossing authored thresholds creates real server events and Chronicle articles.</div></div>}

  {tab==='dungeons'&&<div className="grid grid-cols-2 gap-3">{[['☠','Crypt of Echoes','Nightfall','Ossuary / Catacombs','Gravebound Abbot'],['⚡','Storm Vault','Stormwatch','Conduits / Sky Bridge','Tempest Engine'],['◇','Crystal Labyrinth','Crystal Deep','Prism / Void Glass','The Refraction'],['❧','Ironroot Depths','Ironwood','Roots / Fungal Halls','Old Bark Maw']].map(x=><div className={card} key={x[1]}><div className="flex gap-3"><span className="text-3xl">{x[0]}</span><div><b>{x[1]}</b><div className="text-[9px] text-slate-500">{x[2]}</div></div></div><div className="mt-3 text-xs text-cyan-200">Branch: {x[3]}</div><div className="text-xs text-red-300">Boss: {x[4]}</div><div className="mt-2 text-[9px] text-slate-500">Node-stage gate · puzzle · branching path · world impact · first-defeat record</div></div>)}</div>}

  {tab==='quests'&&<div className="grid grid-cols-2 gap-3"><div className={card}><b>QUEST CONSEQUENCE RUNTIME</b><div className="mt-3 rounded bg-white/5 p-3"><div className="text-[9px] text-slate-500">THE CROWN ROADS</div><b>What becomes of the trade route?</b><div className="mt-3 grid grid-cols-2 gap-2 text-[10px]"><span className="rounded bg-cyan-500/10 p-2">Open Trade<br/><em>Prosperity +8 · Supply +4</em></span><span className="rounded bg-amber-500/10 p-2">Crown Control<br/><em>Morale +6 · Influence +18</em></span></div></div></div><div className={card}><b>WORLD MEMORY</b><div className="mt-3 text-xs text-slate-300">Choices are persistent, once-only and can modify Node supply/morale, regional economy/ecology, faction influence and Chronicle history.</div><div className="mt-3 rounded bg-purple-500/10 p-3 text-[10px] text-purple-200">Quest Graph 9.8 → Consequence Runtime 9.25 → Living Realm state</div></div></div>}

  {tab==='housing'&&<div className="grid grid-cols-3 gap-3">{[['⚒','Artisan Workshop','Craft quality +3'],['🏪','Player Shopfront','Commerce service + tax relief'],['🐎','Private Stable','Stable slots + breeding bonus'],['📚','Research Library','Recipe discovery +5%'],['🏰','Guild Hall Annex','Guild storage + rally'],['🏗','Siege Foundry','Siege quality + repair']].map(x=><div className={card} key={x[1]}><div className="text-2xl">{x[0]}</div><b>{x[1]}</b><div className="mt-2 text-[10px] text-emerald-300">{x[2]}</div><div className="mt-2 text-[9px] text-slate-500">Requires owned housing · server-persisted functional upgrade</div></div>)}</div>}
</div>}
