from pathlib import Path


def rep(path, old, new, count=1):
    p=Path(path); s=p.read_text()
    if old not in s: raise SystemExit(f'anchor missing {path}: {old[:100]!r}')
    p.write_text(s.replace(old,new,count))

# versions
for path in ['package.json','package-lock.json','server/package.json','server/package-lock.json']:
    p=Path(path); s=p.read_text(); p.write_text(s.replace('"version": "9.10.0"','"version": "9.16.0"',1))

# Content DB — new editable catalogs + v4 migration
rep('server/engine/ContentDB.mjs',"import { ALPHA_SYSTEMS_CONTENT } from './AlphaSystemsContent.mjs';\n","import { ALPHA_SYSTEMS_CONTENT } from './AlphaSystemsContent.mjs';\nimport { LIVING_REALM_CONTENT } from './LivingRealmContent.mjs';\n")
rep('server/engine/ContentDB.mjs',"const COLLECTION_KEYS = Object.freeze(['items', 'monsters', 'npcs', 'quests', 'spells', 'maps', 'worldEvents', 'shops', 'lootTables', 'gmRoster', 'taskQuests', 'houses', 'housingDecor', 'outfits', 'mounts']);","const COLLECTION_KEYS = Object.freeze(['items', 'monsters', 'npcs', 'quests', 'spells', 'maps', 'worldEvents', 'shops', 'lootTables', 'gmRoster', 'taskQuests', 'houses', 'housingDecor', 'outfits', 'mounts', 'nodes', 'factions', 'materials', 'craftingRecipes', 'tamingSpecies']);")
rep('server/engine/ContentDB.mjs',"    worldEvents: [], shops: [], lootTables: [], gmRoster: [], taskQuests: [], houses: [], housingDecor: [], outfits: [], mounts: [],\n","    worldEvents: [], shops: [], lootTables: [], gmRoster: [], taskQuests: [], houses: [], housingDecor: [], outfits: [], mounts: [],\n    nodes: [], factions: [], materials: [], craftingRecipes: [], tamingSpecies: [],\n")
rep('server/engine/ContentDB.mjs',"    else { this.migrateAlphaV2(); this.migrateAlphaV3(); }","    else { this.migrateAlphaV2(); this.migrateAlphaV3(); this.migrateLivingRealmV4(); }")
anchor="""  save() {\n"""
migration="""  migrateLivingRealmV4() {\n    if (Number(this.data.version) >= 4) return false;\n    const hasExistingContent = COLLECTION_KEYS.some(key => Array.isArray(this.data[key]) && this.data[key].length > 0);\n    if (hasExistingContent) {\n      this.data.nodes = mergeById(LIVING_REALM_CONTENT.nodes, this.data.nodes);\n      this.data.factions = mergeById(LIVING_REALM_CONTENT.factions, this.data.factions);\n      this.data.materials = mergeById(LIVING_REALM_CONTENT.materials, this.data.materials);\n      this.data.craftingRecipes = mergeById(LIVING_REALM_CONTENT.craftingRecipes, this.data.craftingRecipes);\n      this.data.tamingSpecies = mergeById(LIVING_REALM_CONTENT.tamingSpecies, this.data.tamingSpecies);\n    }\n    this.data.version = 4;\n    this.save();\n    return true;\n  }\n\n"""+anchor
rep('server/engine/ContentDB.mjs',anchor,migration)
rep('server/engine/ContentDB.mjs',"    this.data.version = 3;\n\n    this.save();","    this.data.nodes = mergeById(this.data.nodes, LIVING_REALM_CONTENT.nodes);\n    this.data.factions = mergeById(this.data.factions, LIVING_REALM_CONTENT.factions);\n    this.data.materials = mergeById(this.data.materials, LIVING_REALM_CONTENT.materials);\n    this.data.craftingRecipes = mergeById(this.data.craftingRecipes, LIVING_REALM_CONTENT.craftingRecipes);\n    this.data.tamingSpecies = mergeById(this.data.tamingSpecies, LIVING_REALM_CONTENT.tamingSpecies);\n    this.data.version = 4;\n\n    this.save();")

# Studio schemas
rep('server/engine/ContentStudio.mjs',"const NAMEPLATE_MODES = Object.freeze(['nearby','always','hidden']);\n","const NAMEPLATE_MODES = Object.freeze(['nearby','always','hidden']);\nconst NODE_SPECIALIZATIONS = Object.freeze(['military','commercial','arcane','religious','industrial','wild','neutral']);\nconst TAME_RARITIES = Object.freeze(['common','uncommon','rare','epic','legendary','mythical']);\n")
insert="""  nodes: Object.freeze([\n    field('id','ID'), field('name','Name'), field('mapId','Map'), field('specialization','Specialization'),\n    field('x','Center X','number'), field('y','Center Y','number'), field('radius','Influence radius','number'), field('enabled','Enabled','boolean'),\n    field('maxHp','Base siege HP','number'), field('stageThresholds','Stage XP thresholds','json'), field('taxRate','Tax %','number'),\n  ]),\n  factions: Object.freeze([\n    field('id','ID'), field('name','Name'), field('icon','Icon'), field('color','Color'), field('ideology','Ideology','textarea'),\n    field('hqMapId','HQ map'), field('bonuses','Bonuses','json'), field('enemies','Enemy faction IDs','json'),\n  ]),\n  materials: Object.freeze([\n    field('id','ID'), field('name','Name'), field('icon','Icon'), field('category','Category'), field('tier','Tier','number'), field('baseQuality','Base quality','number'),\n  ]),\n  craftingRecipes: Object.freeze([\n    field('id','ID'), field('name','Name'), field('profession','Profession'), field('stationType','Station'), field('difficulty','Difficulty','number'),\n    field('levelRequired','Required level','number'), field('inputs','Inputs','json'), field('output','Output','json'),\n  ]),\n  tamingSpecies: Object.freeze([\n    field('id','ID'), field('name','Name'), field('icon','Icon'), field('monsterId','Monster ID'), field('rarity','Rarity'), field('levelRequired','Required level','number'),\n    field('mapId','Habitat map'), field('temperament','Temperament','number'), field('favoriteFood','Favorite food'), field('breedable','Breedable','boolean'),\n    field('roles','Roles','json'), field('baseTraits','Base traits','json'),\n  ]),\n"""
rep('server/engine/ContentStudio.mjs',"  gmRoster: Object.freeze([\n",insert+"  gmRoster: Object.freeze([\n")
validation="""  if (type === 'nodes') {\n    if (!NODE_SPECIALIZATIONS.includes(String(record.specialization || 'neutral'))) return 'node specialization is not supported';\n    for (const [key,min,max] of [['x',1,78],['y',1,78],['radius',2,30],['maxHp',500,1000000],['taxRate',0,25]]) { const e=numberIn(record,key,min,max,{required:true}); if(e)return e; }\n    if (record.enabled !== undefined && typeof record.enabled !== 'boolean') return 'enabled must be boolean';\n    if (!Array.isArray(record.stageThresholds) || record.stageThresholds.length < 7) return 'stageThresholds must contain 7 XP thresholds';\n    return null;\n  }\n  if (type === 'factions') {\n    if (record.enemies !== undefined && !Array.isArray(record.enemies)) return 'enemies must be an array';\n    if (record.bonuses !== undefined && (!record.bonuses || typeof record.bonuses !== 'object' || Array.isArray(record.bonuses))) return 'bonuses must be an object';\n    return optionalColor(record);\n  }\n  if (type === 'materials') { let e=numberIn(record,'tier',1,10,{required:true,integer:true}); if(e)return e; return numberIn(record,'baseQuality',1,100,{required:true}); }\n  if (type === 'craftingRecipes') { let e=numberIn(record,'difficulty',1,100,{required:true}); if(e)return e; e=numberIn(record,'levelRequired',1,100000,{required:true,integer:true}); if(e)return e; if(!Array.isArray(record.inputs)||!record.inputs.length)return 'inputs must be a non-empty array'; if(!record.output||typeof record.output!=='object'||Array.isArray(record.output))return 'output must be an object'; return null; }\n  if (type === 'tamingSpecies') { if(!TAME_RARITIES.includes(String(record.rarity||'')))return 'taming rarity is not supported'; let e=numberIn(record,'levelRequired',1,100000,{required:true,integer:true}); if(e)return e; e=numberIn(record,'temperament',0,100,{required:true}); if(e)return e; if(record.roles!==undefined&&!Array.isArray(record.roles))return 'roles must be an array'; if(record.baseTraits!==undefined&&(!record.baseTraits||typeof record.baseTraits!=='object'||Array.isArray(record.baseTraits)))return 'baseTraits must be an object'; if(record.breedable!==undefined&&typeof record.breedable!=='boolean')return 'breedable must be boolean'; return null; }\n\n"""
rep('server/engine/ContentStudio.mjs',"  if (type === 'monsters') {\n",validation+"  if (type === 'monsters') {\n",1)

# Official persistent state: preserve living realm player/global structures safely.
rep('server/engine/OfficialStateSchema.mjs',"export const OFFICIAL_STATE_SCHEMA_VERSION = 1;","export const OFFICIAL_STATE_SCHEMA_VERSION = 2;")
rep('server/engine/OfficialStateSchema.mjs',"    lastGatherAt: 0, lastMailAt: 0, lastPvpAttack: 0,\n","    lastGatherAt: 0, lastMailAt: 0, lastPvpAttack: 0,\n    livingRealm: { faction:{id:null,reputation:0,rank:0,joinedAt:0,defectionUntil:0,history:[]}, crafting:{skills:{},crafted:0,masterworks:0,log:[]}, taming:{skill:1,xp:0,animals:[],activeId:null,breedingCount:0}, lastNodeAttackAt:0 },\n")
rep('server/engine/OfficialStateSchema.mjs',"    auctions: [], mail: [], credits: {}, eventRewards: {}, event: null, eventSequence: 0,\n","    auctions: [], mail: [], credits: {}, eventRewards: {}, event: null, eventSequence: 0,\n    livingRealm: { nodes:{}, chronicle:[], sequence:0 },\n")
player_norm="""  if (isRecord(saved.livingRealm)) {\n    const lr=saved.livingRealm;\n    base.livingRealm.faction={\n      id:text(lr.faction?.id,100)||null, reputation:int(lr.faction?.reputation,-5000,100000,0), rank:int(lr.faction?.rank,0,5,0),\n      joinedAt:Math.max(0,Number(lr.faction?.joinedAt)||0), defectionUntil:Math.max(0,Number(lr.faction?.defectionUntil)||0),\n      history:Array.isArray(lr.faction?.history)?lr.faction.history.filter(isRecord).slice(-10).map(entry=>({id:text(entry.id,100),leftAt:Math.max(0,Number(entry.leftAt)||0)})):[],\n    };\n    const skills={}; if(isRecord(lr.crafting?.skills)) for(const [id,skill] of Object.entries(lr.crafting.skills).slice(0,40)){const key=slug(id);if(key)skills[key]={level:int(skill?.level,1,100,1),xp:int(skill?.xp,0,1000000,0)}}\n    base.livingRealm.crafting={skills,crafted:int(lr.crafting?.crafted,0,100000000,0),masterworks:int(lr.crafting?.masterworks,0,100000000,0),log:Array.isArray(lr.crafting?.log)?lr.crafting.log.filter(isRecord).slice(-100).map(clone):[]};\n    const animals=Array.isArray(lr.taming?.animals)?lr.taming.animals.filter(isRecord).slice(-40).map(clone):[];\n    base.livingRealm.taming={skill:int(lr.taming?.skill,1,100,1),xp:int(lr.taming?.xp,0,1000000,0),animals,activeId:animals.some(a=>a.id===lr.taming?.activeId)?lr.taming.activeId:null,breedingCount:int(lr.taming?.breedingCount,0,1000000,0)};\n    base.livingRealm.lastNodeAttackAt=Math.max(0,Number(lr.lastNodeAttackAt)||0);\n  }\n"""
rep('server/engine/OfficialStateSchema.mjs',"  base.welcomeMailSent = Boolean(saved.welcomeMailSent);\n  return base;","  base.welcomeMailSent = Boolean(saved.welcomeMailSent);\n"+player_norm+"  return base;")
global_norm="""\n  if (isRecord(raw.livingRealm)) {\n    const lr=raw.livingRealm; const nodes={};\n    if(isRecord(lr.nodes)) for(const [id,node] of Object.entries(lr.nodes).slice(0,200)){const key=text(id,100);if(key&&isRecord(node))nodes[key]=clone(node)}\n    base.livingRealm={nodes,chronicle:Array.isArray(lr.chronicle)?lr.chronicle.filter(isRecord).slice(-250).map(clone):[],sequence:int(lr.sequence,0,999999999,0)};\n  }\n"""
rep('server/engine/OfficialStateSchema.mjs',"  base.eventSequence = int(raw.eventSequence, 0, 999_999, 0);\n  return base;","  base.eventSequence = int(raw.eventSequence, 0, 999_999, 0);"+global_norm+"  return base;")
rep('server/engine/OfficialStateSchema.mjs',"    welcomeMailSent: s.welcomeMailSent,\n","    welcomeMailSent: s.welcomeMailSent,\n    livingRealm: s.livingRealm,\n")

# Official systems integration
rep('server/engine/OfficialSystems.mjs',"import { officialRuntimeCoordinator } from './OfficialRuntimeCoordinator.mjs';\n","import { officialRuntimeCoordinator } from './OfficialRuntimeCoordinator.mjs';\nimport { livingRealmDomain } from './LivingRealmDomain.mjs';\nimport { contentDB } from './ContentDB.mjs';\n")
rep('server/engine/OfficialSystems.mjs',"    this.contentEvents = [];\n    this.load();","    this.contentEvents = [];\n    this.livingRealmContent = {};\n    this.load();\n    this.syncLivingRealmContent();")
rep('server/engine/OfficialSystems.mjs',"  syncWorldEvents(events = []) {\n","  syncLivingRealmContent() { return livingRealmDomain.syncContent(this,{nodes:contentDB.get('nodes'),factions:contentDB.get('factions'),materials:contentDB.get('materials'),craftingRecipes:contentDB.get('craftingRecipes'),tamingSpecies:contentDB.get('tamingSpecies')}); }\n\n  syncWorldEvents(events = []) {\n")
methods="""\n  livingRealmTick(now=Date.now()){ return livingRealmDomain.tick(this,now); }\n  livingRealmSnapshot(player=null){ return livingRealmDomain.publicRealm(this,player); }\n  joinFaction(player,factionId){ return livingRealmDomain.joinFaction(this,player,factionId); }\n  defectFaction(player,factionId){ return livingRealmDomain.defectFaction(this,player,factionId); }\n  donateNode(player,nodeId,amount){ return livingRealmDomain.donateNodeGold(this,player,nodeId,amount); }\n  declareNodeWar(player,nodeId){ return livingRealmDomain.declareNodeWar(this,player,nodeId); }\n  attackNode(player,nodeId){ return livingRealmDomain.attackNode(this,player,nodeId); }\n  claimNode(player,nodeId){ return livingRealmDomain.claimNeutralNode(this,player,nodeId); }\n  advancedCraft(player,recipeId){ return livingRealmDomain.advancedCraft(this,player,recipeId); }\n  tameAnimal(player,speciesId){ return livingRealmDomain.tame(this,player,speciesId); }\n  breedAnimals(player,parentAId,parentBId){ return livingRealmDomain.breed(this,player,parentAId,parentBId); }\n  activateTamedAnimal(player,animalId){ return livingRealmDomain.activateAnimal(this,player,animalId); }\n  livingRealmMonsterKill(player,monster){ return livingRealmDomain.onMonsterKill(this,player,monster); }\n"""
rep('server/engine/OfficialSystems.mjs',"  snapshot(player, nearbyPlayers = []) {\n",methods+"\n  snapshot(player, nearbyPlayers = []) {\n")

# Actions
insert_actions="""  faction_join: { run:(systems,player,payload)=>detailWithOk(systems.joinFaction(player,payload.factionId)) },\n  faction_defect: { run:(systems,player,payload)=>detailWithOk(systems.defectFaction(player,payload.factionId)) },\n  node_donate: { run:(systems,player,payload)=>detailWithOk(systems.donateNode(player,payload.nodeId,payload.amount)) },\n  node_declare_war: { run:(systems,player,payload)=>detailWithOk(systems.declareNodeWar(player,payload.nodeId)) },\n  node_attack: { run:(systems,player,payload)=>detailWithOk(systems.attackNode(player,payload.nodeId)) },\n  node_claim: { run:(systems,player,payload)=>detailWithOk(systems.claimNode(player,payload.nodeId)) },\n  craft_advanced: { run:(systems,player,payload)=>detailWithOk(systems.advancedCraft(player,payload.recipeId)) },\n  tame_animal: { run:(systems,player,payload)=>detailWithOk(systems.tameAnimal(player,payload.speciesId)) },\n  breed_animals: { run:(systems,player,payload)=>detailWithOk(systems.breedAnimals(player,payload.parentAId,payload.parentBId)) },\n  tame_activate: { run:(systems,player,payload)=>detailWithOk(systems.activateTamedAnimal(player,payload.animalId||null)) },\n"""
rep('server/engine/OfficialActionRegistry.mjs',"const ACTIONS = Object.freeze({\n","const ACTIONS = Object.freeze({\n"+insert_actions)

# Snapshot exposes living realm
rep('server/engine/OfficialSnapshotReadModel.mjs',"      nearbyPvp: projectNearbyPvp(host, player, nearbyPlayers),\n","      nearbyPvp: projectNearbyPvp(host, player, nearbyPlayers),\n      livingRealm: typeof host.livingRealmSnapshot === 'function' ? clone(host.livingRealmSnapshot(player)) : null,\n")

# GameState: keep content sync + world tick + node contribution on kills
rep('server/engine/GameState.mjs',"    livingWorldAI.sync(contentDB); interiorSystem.sync(contentDB);\n","    livingWorldAI.sync(contentDB); interiorSystem.sync(contentDB); officialSystems.syncLivingRealmContent?.();\n")
# tick hook after world event director tick if present
needle="worldEventDirector.tick"
p=Path('server/engine/GameState.mjs'); s=p.read_text()
idx=s.find(needle)
if idx<0: raise SystemExit('worldEventDirector.tick anchor missing')
line_end=s.find('\n',idx)
s=s[:line_end+1]+"    officialSystems.livingRealmTick?.(now);\n"+s[line_end+1:]
p.write_text(s)
# monster kill integration: attach after existing officialSystems.onMonsterKill first occurrence
p=Path('server/engine/GameState.mjs'); s=p.read_text(); old="officialSystems.onMonsterKill(player, monster);"
if old not in s: raise SystemExit('onMonsterKill anchor missing')
s=s.replace(old,old+"\n      officialSystems.livingRealmMonsterKill?.(player, monster);",1);p.write_text(s)

# Client director
Path('src/components/LivingRealmDirector916.tsx').write_text(r'''import { useState } from 'react';
const nodes=[['Eldoria Crownlands','Commercial','Village','Crown of Eldoria','82%'],['Frostpeak Bastion','Military','Fortress','Red Pact','41%'],['Ironwood Wild March','Wild','City','Children of the Wild','67%'],['Crystal Deep Conclave','Arcane','City','Arcane Conclave','55%']];
const news=[['WAR','Red Pact declares siege on Frostpeak','Defenders have entered the preparation window.'],['CRAFT','A relic-grade Arcane Focus was forged','The crafter used Crystal Deep station bonuses.'],['BEAST','A rare Frost Wolf was tamed','The server recorded the new beastmaster achievement.'],['POLITICS','Eldoria trade taxes reduced to 4%','The commercial node reached a new development stage.']];
const factions=[['♛','Crown of Eldoria','Order · Trade · Defense'],['⚔','Red Pact','Conquest · Siege · Martial'],['✦','Arcane Conclave','Relics · Magic · Knowledge'],['☾','Order of the Veil','Death · Shadow · Secrets'],['❧','Children of the Wild','Nature · Beasts · Taming'],['⚓','Free League','Trade · Exploration · Freedom']];
const recipes=[['Steel Longblade','Weaponsmithing','Forge','35'],['Dragon Scale Plate','Armorsmithing','Forge','70'],['Arcane Focus','Enchanting','Enchanter','55'],['Battering Ram Kit','Siege Engineering','Siegeworks','60']];
const beasts=[['🐺','Wild Wolf','Common','Combat · Scout'],['🐻','Brown Bear','Uncommon','Combat · Pack'],['❄','Frost Wolf','Rare','Mount · Combat · Scout'],['⚡','Storm Raptor','Epic','Mount · Combat'],['🌑','Shadow Panther','Legendary','Combat · Scout']];
type Tab='nodes'|'factions'|'chronicle'|'crafting'|'taming';
export default function LivingRealmDirector916(){const [tab,setTab]=useState<Tab>('nodes');return <div className="space-y-3 text-slate-100">
 <div className="rounded-xl border border-amber-300/30 bg-black/40 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="text-[10px] font-black tracking-[.28em] text-amber-300">MOR'IA 9.16</div><div className="text-xl font-black">THE LIVING REALM</div><div className="text-xs text-slate-400">Persistent nodes, factions, server chronicle, grand crafting and beast breeding.</div></div><div className="rounded-lg border border-emerald-400/30 bg-emerald-400/10 px-3 py-2 text-xs text-emerald-200">SERVER AUTHORITY · PERSISTENT</div></div></div>
 <div className="flex flex-wrap gap-2">{([['nodes','🏰 Nodes'],['factions','⚑ Factions'],['chronicle','📰 Chronicle'],['crafting','⚒ Grand Craft'],['taming','🐾 Taming']] as [Tab,string][]).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-lg px-3 py-2 text-xs font-black ${tab===id?'bg-amber-500 text-black':'bg-white/5 text-slate-300'}`}>{label}</button>)}</div>
 {tab==='nodes'&&<div className="grid grid-cols-2 gap-3"><div className="col-span-2 rounded-lg border border-red-400/30 bg-red-950/20 p-3"><div className="flex justify-between text-xs"><b className="text-red-300">⚔ NODE WAR CAMPAIGN</b><span>Declared → Preparation → Siege → Occupied → Recovery</span></div><div className="mt-2 h-2 overflow-hidden rounded bg-black"><div className="h-full w-[64%] bg-red-500"/></div></div>{nodes.map(n=><div key={n[0]} className="rounded-xl border border-white/10 bg-black/30 p-3"><div className="flex justify-between"><b>{n[0]}</b><span className="text-amber-300">{n[2]}</span></div><div className="mt-1 text-[10px] uppercase tracking-widest text-slate-500">{n[1]} NODE</div><div className="mt-3 flex justify-between text-xs"><span>{n[3]}</span><span>{n[4]} development</span></div><div className="mt-1 h-1.5 rounded bg-black"><div className="h-full w-2/3 rounded bg-emerald-500"/></div></div>)}</div>}
 {tab==='factions'&&<div className="grid grid-cols-3 gap-3">{factions.map(f=><div key={f[1]} className="rounded-xl border border-white/10 bg-black/30 p-4 text-center"><div className="text-3xl">{f[0]}</div><b className="mt-2 block">{f[1]}</b><div className="mt-1 text-[10px] text-slate-400">{f[2]}</div><div className="mt-3 rounded bg-white/5 px-2 py-1 text-[10px] text-amber-200">Chosen during gameplay · defection has consequences</div></div>)}</div>}
 {tab==='chronicle'&&<div className="rounded-xl border border-amber-200/20 bg-[#18120d] p-5"><div className="border-b border-amber-200/20 pb-3 text-center"><div className="font-serif text-3xl font-black tracking-wider text-amber-100">THE MOR'IA CHRONICLE</div><div className="text-[10px] tracking-[.35em] text-amber-300/60">SERVER HISTORY · POLITICS · ECONOMY · HEROES</div></div><div className="mt-4 grid grid-cols-2 gap-4">{news.map((n,i)=><article key={n[1]} className={`border-b border-amber-100/10 pb-4 ${i===0?'col-span-2':''}`}><div className="text-[9px] font-black tracking-[.25em] text-red-300">{n[0]}</div><h3 className={`${i===0?'text-xl':'text-base'} font-serif font-black text-amber-50`}>{n[1]}</h3><p className="mt-1 text-xs text-amber-100/60">{n[2]}</p></article>)}</div></div>}
 {tab==='crafting'&&<div className="grid grid-cols-[1.2fr_.8fr] gap-3"><div className="rounded-xl border border-orange-300/20 bg-black/30 p-4"><div className="mb-3 font-black text-orange-200">⚒ PRODUCTION CHAIN</div><div className="flex items-center justify-between rounded bg-white/5 p-3 text-xs"><span>Gathering</span><span>→</span><span>Processing</span><span>→</span><span>Components</span><span>→</span><span>Master Craft</span></div><div className="mt-3 space-y-2">{recipes.map(r=><div key={r[0]} className="grid grid-cols-4 rounded border border-white/5 bg-white/[.03] p-2 text-xs"><b>{r[0]}</b><span>{r[1]}</span><span>{r[2]}</span><span className="text-right text-amber-300">Difficulty {r[3]}</span></div>)}</div></div><div className="rounded-xl border border-purple-300/20 bg-purple-950/20 p-4"><b>QUALITY ENGINE</b><div className="mt-3 space-y-2 text-xs text-slate-300"><div>Material quality</div><div>Crafter skill</div><div>Recipe difficulty</div><div>Station / Node level</div><div>Industrial faction control</div><div>Critical variance</div></div><div className="mt-4 rounded bg-black/30 p-3 text-center text-sm font-black text-purple-200">Crude → Common → Fine → Masterwork → Epic → Relic</div></div></div>}
 {tab==='taming'&&<div className="grid grid-cols-5 gap-2">{beasts.map(b=><div key={b[1]} className="rounded-xl border border-emerald-300/15 bg-emerald-950/15 p-3 text-center"><div className="text-3xl">{b[0]}</div><b className="mt-2 block text-sm">{b[1]}</b><div className="text-[10px] font-black uppercase text-emerald-300">{b[2]}</div><div className="mt-2 text-[10px] text-slate-400">{b[3]}</div><div className="mt-3 border-t border-white/5 pt-2 text-[9px] text-slate-500">Temperament · Strength · Speed · Endurance · Intelligence · Loyalty · Wildness</div></div>)}<div className="col-span-5 rounded-lg border border-fuchsia-300/20 bg-fuchsia-950/15 p-3 text-xs"><b className="text-fuchsia-200">BREEDING:</b> offspring inherit bounded parental traits; rare server-side mutations can improve one trait and are recorded in the Chronicle.</div></div>}
 </div>}
''')

# GameEditor tab
rep('src/components/GameEditor.tsx',"import WorldDirector98 from './WorldDirector98';\n","import WorldDirector98 from './WorldDirector98';\nimport LivingRealmDirector916 from './LivingRealmDirector916';\n")
rep('src/components/GameEditor.tsx',"type EditorTab = 'items' | 'spells' | 'classes' | 'maps' | 'quests98' | 'interiors98' | 'director98' | 'books' | 'npcs' | 'monsters';","type EditorTab = 'items' | 'spells' | 'classes' | 'maps' | 'quests98' | 'interiors98' | 'director98' | 'realm916' | 'books' | 'npcs' | 'monsters';")
rep('src/components/GameEditor.tsx',"    { id: 'director98', label: 'World Director 9.8', icon: '🌍' },\n","    { id: 'director98', label: 'World Director 9.8', icon: '🌍' },\n    { id: 'realm916', label: 'Living Realm 9.16', icon: '🏰' },\n")
rep('src/components/GameEditor.tsx',"          {tab === 'director98' && <WorldDirector98 />}\n","          {tab === 'director98' && <WorldDirector98 />}\n          {tab === 'realm916' && <LivingRealmDirector916 />}\n")

# tests
Path('server/test/living-realm-9-11-16.test.mjs').write_text(r'''import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'fs';
import { LivingRealmDomain, NODE_STAGES, CRAFT_GRADES } from '../engine/LivingRealmDomain.mjs';
import { LIVING_REALM_CONTENT } from '../engine/LivingRealmContent.mjs';
import { freshGlobalState, freshPlayerState, normalizeGlobalState, normalizePlayerState } from '../engine/OfficialStateSchema.mjs';
import { OFFICIAL_ACTION_NAMES } from '../engine/OfficialActionRegistry.mjs';
import { CONTENT_STUDIO_SCHEMAS, validateStudioRecord } from '../engine/ContentStudio.mjs';

function host(){const h={global:freshGlobalState(),livingRealmContent:structuredClone(LIVING_REALM_CONTENT),ensurePlayer(p){p.official??=freshPlayerState();return p.official;}};return h}
function player(mapId='eldoria',level=30){return {name:'Tester',level,mapId,gold:100000,attack:60,inventory:[],official:freshPlayerState()}}
const add=(p,name,q=1,type='material')=>p.inventory.push({id:`i_${p.inventory.length}`,name,type,quantity:q});

test('9.11 living nodes advance through server-owned XP stages',()=>{const d=new LivingRealmDomain(),h=host(),p=player();const n=LIVING_REALM_CONTENT.nodes[0];let r=d.contributeNode(h,p,n.id,500,'quest',1000);assert.equal(r.ok,true);assert.ok(r.node.stage>=2);assert.equal(NODE_STAGES[r.node.stage],r.node.stageName)});
test('9.12 factions are chosen during gameplay and defection is consequential',()=>{const d=new LivingRealmDomain(),h=host(),p=player();let r=d.joinFaction(h,p,'crown_eldoria',100);assert.equal(r.ok,true);assert.equal(p.official.livingRealm.faction.id,'crown_eldoria');r=d.defectFaction(h,p,'free_league',200);assert.equal(r.ok,true);assert.equal(p.official.livingRealm.faction.reputation,-100);assert.ok(p.official.livingRealm.faction.defectionUntil>200);assert.equal(d.defectFaction(h,p,'red_pact',201).ok,false)});
test('9.13 node war declares, opens siege and can be claimed by attackers',()=>{const d=new LivingRealmDomain(),h=host(),p=player('eldoria',50);d.joinFaction(h,p,'red_pact',1);const nodeId='node_eldoria';d.contributeNode(h,p,nodeId,1000,'activity',2);h.global.livingRealm.nodes[nodeId].controllerFactionId='crown_eldoria';const war=d.declareNodeWar(h,p,nodeId,1000);assert.equal(war.ok,true);d.tick(h,war.node.siegeStartsAt);assert.equal(h.global.livingRealm.nodes[nodeId].status,'siege');h.global.livingRealm.nodes[nodeId].hp=1;p.official.livingRealm.lastNodeAttackAt=0;const hit=d.attackNode(h,p,nodeId,war.node.siegeStartsAt+2000);assert.equal(hit.ok,true);assert.equal(hit.node.controllerFactionId,'red_pact');assert.equal(hit.node.status,'occupied')});
test('9.14 Chronicle records bounded real server events',()=>{const d=new LivingRealmDomain(),h=host();for(let i=0;i<300;i++)d.chronicle(h,'world',`Headline ${i}`,'body',{},i+1);assert.equal(h.global.livingRealm.chronicle.length,250);assert.equal(d.publicRealm(h).chronicle.length,50);assert.match(d.publicRealm(h).chronicle[0].headline,/Headline 299/)});
test('9.15 grand crafting consumes a production chain and generates quality',()=>{const d=new LivingRealmDomain(),h=host(),p=player('emberhold',30);add(p,'Steel Ingot',10);add(p,'Treated Lumber',3);const r=d.advancedCraft(h,p,'steel_longblade',100,()=>0.9);assert.equal(r.ok,true);assert.ok(CRAFT_GRADES.includes(r.grade));assert.ok(r.quality>=1&&r.quality<=100);assert.ok(p.inventory.some(i=>i.name==='Crafted Steel Longblade'));assert.ok(p.official.livingRealm.crafting.skills.weaponsmithing)});
test('9.16 taming creates bounded trait animals and breeding inherits traits',()=>{const d=new LivingRealmDomain(),h=host(),p=player('ironwood',40);const a=d.tame(h,p,'wild_wolf',100,()=>0.01);const b=d.tame(h,p,'wild_wolf',200,()=>0.01);assert.equal(a.ok,true);assert.equal(b.ok,true);const child=d.breed(h,p,a.animal.id,b.animal.id,300,()=>0.5);assert.equal(child.ok,true);assert.equal(child.animal.generation,2);assert.ok(Object.values(child.animal.traits).every(v=>v>=1&&v<=100))});
test('9.11-9.16 persistent schema round-trips living realm state',()=>{const d=new LivingRealmDomain(),h=host(),p=player();d.joinFaction(h,p,'crown_eldoria',10);d.chronicle(h,'world','Persistent headline','body',{},11);const ps=normalizePlayerState(p.official);const gs=normalizeGlobalState(h.global);assert.equal(ps.livingRealm.faction.id,'crown_eldoria');assert.equal(gs.livingRealm.chronicle.at(-1).headline,'Persistent headline')});
test('9.11-9.16 action gateway and Studio expose every living realm surface',()=>{for(const name of ['faction_join','faction_defect','node_donate','node_declare_war','node_attack','node_claim','craft_advanced','tame_animal','breed_animals','tame_activate'])assert.ok(OFFICIAL_ACTION_NAMES.includes(name));for(const type of ['nodes','factions','materials','craftingRecipes','tamingSpecies'])assert.ok(CONTENT_STUDIO_SCHEMAS[type]?.length);assert.equal(validateStudioRecord('nodes',{id:'n1',name:'Node',mapId:'eldoria',specialization:'military',x:40,y:40,radius:12,enabled:true,maxHp:5000,stageThresholds:[0,1,2,3,4,5,6],taxRate:5}),null)});
test('9.16 authoring UI stays modular and GameScreen budget is untouched',()=>{const ui=fs.readFileSync(new URL('../../src/components/LivingRealmDirector916.tsx',import.meta.url),'utf8');const editor=fs.readFileSync(new URL('../../src/components/GameEditor.tsx',import.meta.url),'utf8');const game=fs.readFileSync(new URL('../../src/components/GameScreen.tsx',import.meta.url));assert.match(ui,/THE LIVING REALM/);assert.match(ui,/THE MOR'IA CHRONICLE/);assert.match(ui,/BREEDING/);assert.match(editor,/Living Realm 9\.16/);assert.ok(game.length<=155000)});
''')
print('Mor\'ia 9.11-9.16 Living Realm applied')
