from pathlib import Path
import json

CATALOG = Path('src/i18n/pt-BR.928.json')
catalog = json.loads(CATALOG.read_text(encoding='utf-8'))
catalog.update({
    # Adventure Board UI
    'MVP ADVENTURE LOOP': 'CICLO DE AVENTURA',
    'HUNT BOARD': 'QUADRO DE CAÇAS',
    'Choose one hunt, chain kills to build Momentum, then claim escalating rewards. Every third contract awards an equipment cache.': 'Escolha uma caçada, encadeie abates para acumular Impulso e então resgate recompensas crescentes. A cada três contratos, você recebe um baú de equipamento.',
    'Hunts are server-authoritative': 'As caçadas são controladas pelo servidor',
    "Connect to the Mor'ia server to start contracts. Progress, Momentum, gold, XP and cache items are all verified and persisted by the server.": "Conecte-se ao servidor de Mor'ia para iniciar contratos. Progresso, Impulso, ouro, XP e itens de baú são verificados e persistidos pelo servidor.",
    'Synchronizing Hunt Board…': 'Sincronizando Quadro de Caças…',
    'STREAK': 'SEQUÊNCIA',
    'MOMENTUM': 'IMPULSO',
    'COMPLETED': 'CONCLUÍDOS',
    'NEXT CACHE': 'PRÓXIMO BAÚ',
    'next reward': 'na próxima recompensa',
    'kill XP': 'XP por abate',
    'Chain kills within 8s': 'Encadeie abates em até 8s',
    'Best combo': 'Melhor combo',
    'contracts remaining': 'contratos restantes',
    'ACTIVE HUNT': 'CAÇA ATIVA',
    'Defeat': 'Derrote',
    'CLAIM': 'RESGATAR',
    'Abandon': 'Abandonar',
    'SILVER': 'PRATA',
    'GOLD': 'OURO',
    'MYTHIC': 'MÍTICO',
    'VOID': 'VAZIO',
    'No Hunt Board contracts are available in this region yet.': 'Ainda não há contratos de caça disponíveis nesta região.',

    # Adventure contracts from the authoritative server
    'Vermin Sweep': 'Varredura de Vermes',
    'Clear the alleys around Eldoria before the vermin spread.': 'Limpe os becos ao redor de Eldoria antes que as pragas se espalhem.',
    'Snake Nest': 'Ninho de Serpentes',
    'Snakes': 'Serpentes',
    'Thin the snakes stalking the roads outside the capital.': 'Reduza as serpentes que espreitam as estradas fora da capital.',
    'Wolf Pack': 'Matilha de Lobos',
    'Break the pack before it closes the mountain road.': 'Desfaça a matilha antes que ela bloqueie a estrada da montanha.',
    'Bear Hunt': 'Caçada aos Ursos',
    'Bears': 'Ursos',
    'Bring down the great bears roaming the frozen pass.': 'Derrube os grandes ursos que vagam pela passagem congelada.',
    'Orc Patrol': 'Patrulha Orc',
    'Ambush the patrols gathering in the cursed marsh.': 'Embosque as patrulhas que se reúnem no pântano amaldiçoado.',
    'Bone Cleanup': 'Limpeza de Ossos',
    'Put the restless dead back beneath the swamp.': 'Devolva os mortos inquietos às profundezas do pântano.',
    'Demon Purge': 'Expurgo Demoníaco',
    'Demons': 'Demônios',
    "Purge the fiends feeding on Emberhold's volcanic scars.": 'Expurgue os demônios que se alimentam das cicatrizes vulcânicas de Emberhold.',
    'Dragon Trial': 'Provação do Dragão',
    'Dragon Lords': 'Senhores Dragão',
    'Face a Dragon Lord and return with proof of victory.': 'Enfrente um Senhor Dragão e retorne com a prova da vitória.',
    'Ghost Hunt': 'Caçada aos Fantasmas',
    'Ghosts': 'Fantasmas',
    'Silence the shades haunting the edge of reality.': 'Silencie as sombras que assombram os limites da realidade.',
    'Lich Bounty': 'Recompensa pelo Lich',
    'Liches': 'Liches',
    'Destroy a Lich before its ritual tears the Voidlands open.': 'Destrua um Lich antes que seu ritual rasgue as Terras do Vazio.',

    # Adventure authoritative error surfaces
    'Finish or abandon your current hunt first.': 'Conclua ou abandone sua caçada atual primeiro.',
    'Unknown hunt contract.': 'Contrato de caça desconhecido.',
    'No active hunt to abandon.': 'Não há caçada ativa para abandonar.',
    'No active hunt.': 'Não há caçada ativa.',
    'Hunt objective is not complete yet.': 'O objetivo da caçada ainda não foi concluído.',
    'Requires level': 'Requer nível',
    'Travel to': 'Viaje para',
    'to start this hunt.': 'para iniciar esta caçada.',

    # Quest journal UI
    'Adventure journal': 'Diário de aventuras',
    'Quest Log': 'Registro de Missões',
    'Close quest log': 'Fechar registro de missões',
    'ACTIVE': 'ATIVAS',
    'No active quests. Talk to NPCs!': 'Nenhuma missão ativa. Fale com NPCs!',
    'Authoritative server quest': 'Missão oficial do servidor',
    'Complete Quest': 'Concluir Missão',
    'AVAILABLE': 'DISPONÍVEIS',
    'No quests available right now.': 'Nenhuma missão disponível agora.',
    'Accept': 'Aceitar',
    'None yet': 'Nenhuma ainda',
    'ACHIEVEMENTS': 'CONQUISTAS',
    'STATISTICS': 'ESTATÍSTICAS',
    'Lv': 'Nv.',
    'Monsters Killed': 'Monstros Abatidos',
    'Bosses Killed': 'Chefes Derrotados',
    'Damage Dealt': 'Dano Causado',
    'Damage Taken': 'Dano Recebido',
    'Healing Done': 'Cura Realizada',
    'Gold Earned': 'Ouro Obtido',
    'Distance': 'Distância',
    'Spells Cast': 'Magias Conjuradas',
    'Deaths': 'Mortes',
    'Level Ups': 'Níveis Alcançados',

    # Built-in quests
    'Rat Infestation': 'Infestação de Ratos',
    'Captain Thane asked you to clear the rats near the town.': 'O Capitão Thane pediu que você elimine os ratos próximos da cidade.',
    'Rats': 'Ratos',
    'Wolf Menace': 'Ameaça dos Lobos',
    'Thin the wolf population in the eastern forest.': 'Reduza a população de lobos na floresta oriental.',
    'Wolves': 'Lobos',
    'Orc Invasion': 'Invasão Orc',
    'The orcs are amassing in the south. Defeat them!': 'Os orcs estão se reunindo ao sul. Derrote-os!',
    'Orcs': 'Orcs',
    'Orc Warriors': 'Guerreiros Orc',
    'Undead Rising': 'Ascensão dos Mortos-vivos',
    'Skeletons are haunting the graveyard. Put them to rest.': 'Esqueletos estão assombrando o cemitério. Faça-os descansar.',
    'Skeletons': 'Esqueletos',
    'Slay the Orc King': 'Derrote o Rei Orc',
    'The Orc King must fall for peace to return.': 'O Rei Orc deve cair para que a paz retorne.',
    'The ultimate challenge: defeat the Dragon Lord!': 'O desafio supremo: derrote o Senhor Dragão!',

    # Achievements
    'First Blood': 'Primeiro Sangue',
    'Kill your first monster': 'Abata seu primeiro monstro',
    'Novice Hunter': 'Caçador Novato',
    'Kill 10 monsters': 'Abata 10 monstros',
    'Master Hunter': 'Mestre Caçador',
    'Kill 100 monsters': 'Abata 100 monstros',
    'Slayer': 'Exterminador',
    'Kill 500 monsters': 'Abata 500 monstros',
    'Boss Killer': 'Matador de Chefes',
    'Defeat your first boss': 'Derrote seu primeiro chefe',
    'Dragon Slayer': 'Matador de Dragões',
    'Defeat the Dragon Lord': 'Derrote o Senhor Dragão',
    'Adventurer': 'Aventureiro',
    'Reach level 5': 'Alcance o nível 5',
    'Veteran': 'Veterano',
    'Reach level 10': 'Alcance o nível 10',
    'Hero': 'Herói',
    'Reach level 20': 'Alcance o nível 20',
    'Legend': 'Lenda',
    'Reach level 30': 'Alcance o nível 30',
    'Wealthy': 'Abastado',
    'Accumulate 1000 gold': 'Acumule 1000 de ouro',
    'Millionaire': 'Milionário',
    'Accumulate 10000 gold': 'Acumule 10000 de ouro',
    'Explorer': 'Explorador',
    'Walk 500 tiles': 'Caminhe 500 espaços',
    'Wanderer': 'Andarilho',
    'Walk 2000 tiles': 'Caminhe 2000 espaços',
    'Iron Hide': 'Pele de Ferro',
    'Take 1000 damage': 'Receba 1000 de dano',
    'Destroyer': 'Destruidor',
    'Deal 5000 damage': 'Cause 5000 de dano',
    'Healer': 'Curandeiro',
    'Heal 500 HP': 'Cure 500 de Vida',
    'Survivor': 'Sobrevivente',
    'Die 3 times': 'Morra 3 vezes',
    'Spellcaster': 'Conjurador',
    'Cast 100 spells': 'Conjure 100 magias',
})
CATALOG.write_text(json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=True) + '\n', encoding='utf-8')


def patch(path: str, replacements: list[tuple[str, str]]) -> None:
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    for old, new in replacements:
        if old in text:
            text = text.replace(old, new)
        elif new not in text:
            print(f'optional anchor not found in {path}: {old[:100]}')
    p.write_text(text, encoding='utf-8')


patch('src/components/AdventureBoard.tsx', [
    ("export interface AdventureContractView {", "import { t as tr } from '../i18n';\n\nexport interface AdventureContractView {"),
    ('<div className="moria-eyebrow text-amber-200/70">MVP ADVENTURE LOOP</div>', '<div className="moria-eyebrow text-amber-200/70">{tr(\'MVP ADVENTURE LOOP\')}</div>'),
    ('<h2 className="moria-title mt-1 text-2xl font-black tracking-[0.14em] text-amber-100">⚔ HUNT BOARD</h2>', '<h2 className="moria-title mt-1 text-2xl font-black tracking-[0.14em] text-amber-100">⚔ {tr(\'HUNT BOARD\')}</h2>'),
    ('<p className="mt-1 max-w-2xl text-xs text-slate-400">Choose one hunt, chain kills to build Momentum, then claim escalating rewards. Every third contract awards an equipment cache.</p>', '<p className="mt-1 max-w-2xl text-xs text-slate-400">{tr(\'Choose one hunt, chain kills to build Momentum, then claim escalating rewards. Every third contract awards an equipment cache.\')}</p>'),
    ('<div className="mt-3 font-bold text-sky-100">Hunts are server-authoritative</div>', '<div className="mt-3 font-bold text-sky-100">{tr(\'Hunts are server-authoritative\')}</div>'),
    ("<p className=\"mx-auto mt-2 max-w-lg text-xs leading-5 text-slate-400\">Connect to the Mor'ia server to start contracts. Progress, Momentum, gold, XP and cache items are all verified and persisted by the server.</p>", "<p className=\"mx-auto mt-2 max-w-lg text-xs leading-5 text-slate-400\">{tr(\"Connect to the Mor'ia server to start contracts. Progress, Momentum, gold, XP and cache items are all verified and persisted by the server.\")}</p>"),
    ('<div className="py-12 text-center text-sm text-slate-400">Synchronizing Hunt Board…</div>', '<div className="py-12 text-center text-sm text-slate-400">{tr(\'Synchronizing Hunt Board…\')}</div>'),
    ('<Stat icon="🔥" label="STREAK" value={`${state.streak}`} note={`+${Math.min(state.streak, 5) * 10}% next reward`} />', '<Stat icon="🔥" label={tr(\'STREAK\')} value={`${state.streak}`} note={`+${Math.min(state.streak, 5) * 10}% ${tr(\'next reward\')}`} />'),
    ('<Stat icon="⚡" label="MOMENTUM" value={state.combo.count > 0 ? `${state.combo.count}x` : \'—\'} note={state.combo.count > 1 ? `+${Math.round((state.combo.multiplier - 1) * 100)}% kill XP` : \'Chain kills within 8s\'} />', '<Stat icon="⚡" label={tr(\'MOMENTUM\')} value={state.combo.count > 0 ? `${state.combo.count}x` : \'—\'} note={state.combo.count > 1 ? `+${Math.round((state.combo.multiplier - 1) * 100)}% ${tr(\'kill XP\')}` : tr(\'Chain kills within 8s\')} />'),
    ('<Stat icon="🏆" label="COMPLETED" value={`${state.completed}`} note={`Best combo ${state.bestCombo}x`} />', '<Stat icon="🏆" label={tr(\'COMPLETED\')} value={`${state.completed}`} note={`${tr(\'Best combo\')} ${state.bestCombo}x`} />'),
    ('<Stat icon="🎁" label="NEXT CACHE" value={`${state.nextCacheIn}`} note="contracts remaining" />', '<Stat icon="🎁" label={tr(\'NEXT CACHE\')} value={`${state.nextCacheIn}`} note={tr(\'contracts remaining\')} />'),
    ('<div className="text-[9px] font-black tracking-[0.18em] text-sky-300/70">ACTIVE HUNT</div>', '<div className="text-[9px] font-black tracking-[0.18em] text-sky-300/70">{tr(\'ACTIVE HUNT\')}</div>'),
    ('<div className="text-lg font-black text-slate-100">{active.title}</div>', '<div className="text-lg font-black text-slate-100">{tr(active.title)}</div>'),
    ('<div className="mt-1 flex items-center justify-between text-[10px] text-slate-400"><span>Defeat {active.targetLabel}</span><span>{active.progress}/{active.count}</span></div>', '<div className="mt-1 flex items-center justify-between text-[10px] text-slate-400"><span>{tr(\'Defeat\')} {tr(active.targetLabel)}</span><span>{active.progress}/{active.count}</span></div>'),
    ('>🏆 CLAIM</button>', ">🏆 {tr('CLAIM')}</button>"),
    ('>Abandon</button>', ">{tr('Abandon')}</button>"),
    ('<div className="font-black text-slate-100">{contract.title}</div>', '<div className="font-black text-slate-100">{tr(contract.title)}</div>'),
    ('>{tier.label}</span>', '>{tr(tier.label)}</span>'),
    ('<p className="mt-1 text-[11px] leading-4 text-slate-400">{contract.description}</p>', '<p className="mt-1 text-[11px] leading-4 text-slate-400">{tr(contract.description)}</p>'),
    ('>⚔ {contract.count} {contract.targetLabel}</span>', '>⚔ {contract.count} {tr(contract.targetLabel)}</span>'),
    ('{state.board.length === 0 && <div className="rounded-2xl border border-white/10 bg-black/20 p-8 text-center text-sm text-slate-400">No Hunt Board contracts are available in this region yet.</div>}', "{state.board.length === 0 && <div className=\"rounded-2xl border border-white/10 bg-black/20 p-8 text-center text-sm text-slate-400\">{tr('No Hunt Board contracts are available in this region yet.')}</div>}"),
])


patch('src/components/QuestLog.tsx', [
    ("import { ACHIEVEMENTS } from '../game/achievements';", "import { ACHIEVEMENTS } from '../game/achievements';\nimport { t as tr } from '../i18n';"),
    ('<div><div className="moria-eyebrow">Adventure journal</div><h2 className="moria-title mt-1 text-2xl font-black">📜 Quest Log</h2></div>', '<div><div className="moria-eyebrow">{tr(\'Adventure journal\')}</div><h2 className="moria-title mt-1 text-2xl font-black">📜 {tr(\'Quest Log\')}</h2></div>'),
    ('aria-label="Close quest log"', "aria-label={tr('Close quest log')}"),
    ('>🔥 ACTIVE ({activeQuests.length})</h3>', ">🔥 {tr('ACTIVE')} ({activeQuests.length})</h3>"),
    ('>No active quests. Talk to NPCs!</div>', ">{tr('No active quests. Talk to NPCs!')}</div>"),
    ('>{quest?.name || aq.questId}</div>', '>{tr(quest?.name || aq.questId)}</div>'),
    (">{quest?.description || 'Authoritative server quest'}</div>", ">{tr(quest?.description || 'Authoritative server quest')}</div>"),
    ('{o.current >= o.count ? \'✅\' : \'○\'} {o.targetName}', "{o.current >= o.count ? '✅' : '○'} {tr(o.targetName)}"),
    ('>✅ Complete Quest\n                        </button>', ">✅ {tr('Complete Quest')}\n                        </button>"),
    ('>📋 AVAILABLE ({availableQuests.length})</h3>', ">📋 {tr('AVAILABLE')} ({availableQuests.length})</h3>"),
    ('>No quests available right now.</div>', ">{tr('No quests available right now.')}</div>"),
    ('>{q.name}</div>', '>{tr(q.name)}</div>'),
    ('>✓ Accept\n                        </button>', ">✓ {tr('Accept')}\n                        </button>"),
    ('>Lv {q.levelRequired}+</div>', ">{tr('Lv')} {q.levelRequired}+</div>"),
    ('>{q.description}</div>', '>{tr(q.description)}</div>'),
    ('>✅ COMPLETED ({completedQuests.length})</h3>', ">✅ {tr('COMPLETED')} ({completedQuests.length})</h3>"),
    ('✅ {q?.name || qid}', '✅ {tr(q?.name || qid)}'),
    ('>None yet</div>', ">{tr('None yet')}</div>"),
    ('>🏆 ACHIEVEMENTS ({achievements.length}/{ACHIEVEMENTS.length})</h3>', ">🏆 {tr('ACHIEVEMENTS')} ({achievements.length}/{ACHIEVEMENTS.length})</h3>"),
    ('{a.name}', '{tr(a.name)}'),
    ('>{a.description}</div>', '>{tr(a.description)}</div>'),
    ('>📊 STATISTICS</h3>', ">📊 {tr('STATISTICS')}</h3>"),
    ('>{s.icon} {s.label}</div>', '>{s.icon} {tr(s.label)}</div>'),
])

print("Mor'ia 9.30 adventure + quest PT-BR upgrade applied")
